src/main/java/sirius/web/templates/RythmConfig.java

Improved name for cache dir

---

src/main/java/sirius/web/health/Cluster.java
src/main/java/sirius/web/health/HipChat.java
src/main/java/sirius/web/health/Slack.java
src/main/resources/component-web.conf

Added Slack integration

---

src/main/java/sirius/web/controller/ControllerDispatcher.java

Removing trailing slash of uri to better route requests

Removing trailing slash of uri to better route requests

---

src/main/java/sirius/web/health/Cluster.java
src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/WebServerHandler.java
src/main/java/sirius/web/http/WebServerInitializer.java
src/main/java/sirius/web/templates/ExcelExport.java

Added some additional URLs for monitoring purposes and reduced logging

Added some additional URLs for monitoring purposes and reduced logging

---

src/main/java/sirius/web/health/console/HelpCommand.java

Sorted commands in 'help' command

Sorted commands in 'help' command

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java

Updated toSaneFileName usage to new return type

Updated toSaneFileName usage to new return type

---

src/main/resources/default/view/system/info.html

Fixed exception on rendering the info page

Fixed exception on rendering the info page

---

src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/security/ConfigUserManager.java
src/main/java/sirius/web/security/GenericUserManager.java
src/main/resources/component-web.conf
src/main/resources/web_de.properties

Possibility to keep a login saved (Remember me)

Possibility to keep a login saved (Remember me)

---

src/main/resources/default/view/wondergem/parts/modal.html
src/main/resources/default/view/wondergem/parts/modalBody.html
src/main/resources/default/view/wondergem/parts/modalFooter.html
src/main/resources/default/view/wondergem/template-dialogs.html

Change danger modal to work with Bootstrap 3

Change danger modal to work with Bootstrap 3

---

src/main/resources/default/view/parts/colorpicker.html
src/main/resources/default/view/wondergem/template-script.html

Adds colorpicker template part
Also removes most of the logic for colorpicker fields in the template script, because it is not needed anymore

Adds colorpicker template part

---

src/main/resources/default/assets/wondergem/stylesheets/code.scss

Remove \<pre> CSS customizations to better match BS3

Remove <pre> CSS customizations to better match BS3

---

pom.xml

Update sirius-kernel version to 2.4.2

Update sirius-kernel version to 2.4.2

---

src/main/resources/default/view/parts/helpbox.html

Add labelKey Parameter to helpbox template part

Add labelKey Parameter to helpbox template part

---

src/main/resources/default/view/parts/modalFooter.html
src/main/resources/default/view/wondergem/template-script.html

Fix danger modal script under Bootstrap 3

Fix danger modal script under Bootstrap 3

---

src/main/resources/default/assets/wondergem/stylesheets/code.scss

Remove border and background for pre's with plain class

Remove border and background for pre's with plain class

---

src/main/resources/default/view/parts/modalFooter.html

Dont fire action click event when cancel-button of modal is clicked

Dont fire action click event when cancel-button of modal is clicked

---

src/main/resources/default/view/wondergem/template-script.html

Simplify autoScroll logic by removing option to disable keepScrollPosition

Simplify autoScroll logic by removing option to disable keepScrollPosition

---

src/main/resources/default/view/parts/textfield.html

Add adminonly option to textfield template part

Add adminonly option to textfield template part

---

src/main/resources/default/view/parts/fileUpload.html
src/main/resources/default/view/parts/imageUpload.html
src/main/resources/default/view/wondergem/template-script.html

Add allowedExtensions option to fileupload boxes

Add allowedExtensions option to fileupload boxes

---

src/main/resources/default/view/parts/helpbox.html
src/main/resources/default/view/parts/pagination.html
src/main/resources/default/view/parts/table.html
src/main/resources/web_de.properties

This will render a table (within its body) or show an appropriate message
if the given Page or Collection is empty

Adds a table part

---

src/main/resources/default/view/wondergem/template-script.html

Submit an editForm after successful file upload if page contains one

Submit an editForm after successful file upload if page contains one

---

src/main/resources/default/view/parts/navbox.html

Add optional headerKey paramter to navbox template part
Enables an easier use of the often used nav-header item in a navbox.

Add optional headerKey paramter to navbox template part

---

src/main/resources/default/view/parts/autocompleteMultiSelect.html
src/main/resources/default/view/parts/autocompleteSingleSelect.html
src/main/resources/default/view/parts/multiSelect.html
src/main/resources/default/view/parts/singleSelect.html

Adds forceFullWidth parameter to select2 parts, so the width inside of bootstrap modals can be fixed

Adds forceFullWidth parameter to select2 parts, so the width inside of bootstrap modals can be fixed

---

src/main/resources/default/assets/wondergem/stylesheets/forms.scss
src/main/resources/default/assets/wondergem/stylesheets/variables.scss

Add some margin between legend border-bottom and btn

Use and set variable for headings line-height

---

pom.xml
src/main/java/sirius/web/controller/BasicController.java

Controllers now able to get default Route from Superclass

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/pagination.scss
src/main/resources/web_de.properties

Fixes the length of the pagination input
The current length is too short to show two 4 digit values like 1000 - 1025

Fixes the length of the pagination input

---

pom.xml

Updates server-sass to the latest version

Updates server-sass to the latest version

---

pom.xml
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/security/ConfigUserManager.java
src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/LDAPUserManager.java
src/main/java/sirius/web/security/PublicUserManager.java
src/main/java/sirius/web/security/SSOUserManager.java
src/main/java/sirius/web/security/ScopeDefaultConfigController.java
src/main/java/sirius/web/security/ScopeInfo.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/security/UserManager.java
src/main/resources/component-web.conf
src/main/resources/default/view/system/scope-config.html
src/main/resources/web_de.properties
src/main/resources/web_en.properties
src/test/java/sirius/web/security/ScopeInfoSpec.groovy
src/test/resources/scope-conf/test.conf

Changes the source of the default config for scopes.
Previously the default config was nested in the application config.
But since there will be a lot config values, we now load the scope
default from files in scope/*.conf. Also each customization
can provide a scope-settings.conf. Furthermore a GUI was
created to view the default files as a source of inspiration when
provides a custom scope config.

Changes the source of the default config for scopes.

---

pom.xml
src/main/resources/default/view/parts/autocompleteMultiSelect.html
src/main/resources/default/view/parts/autocompleteSingleSelect.html
src/main/resources/default/view/parts/checkbox.html
src/main/resources/default/view/parts/colorpicker.html
src/main/resources/default/view/parts/datefield.html
src/main/resources/default/view/parts/multiSelect.html
src/main/resources/default/view/parts/singleSelect.html
src/main/resources/default/view/parts/textarea.html
src/main/resources/default/view/parts/textfield.html

To avoid trying to look up an i18n key with an empty string

Checks if i18n keys are filled with Strings::isFilled now

---

pom.xml
src/main/java/sirius/web/security/UserContext.java

Merge remote-tracking branch 'origin/master' into aha/TestFixx

Fixes the behaviour of the UserContext across several threads

---

pom.xml
src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/templates/rythm/RythmConfig.java

Merge remote-tracking branch 'origin/master' into aha/RythmFixxes

Rythm Fixxes

---

pom.xml
src/main/java/sirius/web/http/Response.java

Merge remote-tracking branch 'origin/master' into aha/RythmFixxes

Memory leak

---

pom.xml
src/test/java/sirius/web/http/TestRequest.java

Fixes the simulation of POST requests in test-environments

Fixes the simulation of POST requests in test-environments

---

pom.xml
src/main/java/sirius/web/http/HttpPipeliningHandler.java
src/main/java/sirius/web/http/WebsocketHandler.java

Merge remote-tracking branch 'origin/master' into aha/TestFix

Websocket Fixx

---

pom.xml
src/main/resources/default/view/parts/textfield.html

Permits to add an untranslated label to a textfield

Permits to add an untranslated label to a textfield

---

src/main/java/sirius/web/tools/TranslationController.java
src/main/resources/component-web.conf

tags: admintools, NLS, babelfish

Adds a simple xls export for all loaded translations

---

.gitignore
pom.xml
src/main/java/sirius/web/crunchlog/Crunchlog.java
src/main/java/sirius/web/crunchlog/CrunchlogKernel.java
src/main/java/sirius/web/crunchlog/DeleteOldCrunchlogs.java
src/main/resources/component-web.conf

Provides a simple but scalabe facility to store records with varying fields for later processing

Provides a simple but scalabe facility to store records with varying fields for later processing

---

pom.xml
src/main/resources/default/view/parts/pagination.html

This allows the user to browse through the pageinated view by pressing Shift+Left or Shift+Right.
The corresponding event handlers are only added if there is more or less content in the provided Page object.

Adds keyboard shortcuts to the pagination template part

---

pom.xml
src/main/java/sirius/web/tasks/ManagedTaskContext.java
src/main/java/sirius/web/tasks/ManagedTaskExecution.java

This information is needed to implement fallbacks in case of errors occuring in jobs.

Adds a function to determine if the current task is marked as erroneous.

---

pom.xml
src/main/java/sirius/web/crunchlog/Crunchlog.java
src/main/java/sirius/web/crunchlog/CrunchlogKernel.java
src/main/java/sirius/web/security/MaintenanceInfo.java
src/main/java/sirius/web/security/ScopeInfo.java
src/main/java/sirius/web/security/UserInfo.java

Merge remote-tracking branch 'origin/master' into aha/boilerplate

Refactoring - Adapter support and minor fixes

---

pom.xml
src/main/resources/default/view/wondergem/template-script.html

This prevents select from calculating an inline width which is not updated on orienation change or resize
tags: select2

Sets select2 width to 100% to make it responsive

---

pom.xml
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/services/ServiceCall.java

Makes the .require() of ServiceCall available in WebContext
This greatly simplifies JSON calls implemented in controllers.

Makes the .require() of ServiceCall available in WebContext

---

pom.xml
src/main/java/sirius/web/templates/Resources.java

Provides a possibility to flush a cached resource URL

Provides a possibility to flush a cached resource URL

---

pom.xml
src/main/java/sirius/web/tasks/ManagedTask.java
src/main/java/sirius/web/tasks/ManagedTaskExecution.java

Now managed tasks are accessible to every user in the same tenant if filled.

Make managed tasks accessible to same tenant user

---

pom.xml
src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/templates/rythm/RythmConfig.java

Improves the name of the cache directory used for web-cache and rythm files
Both contained Optional[node-name] instead of the node-name...

Improves the name of the cache directory used for web-cache and rythm files

---

src/main/resources/default/assets/wondergem/stylesheets/buttons.scss
src/main/resources/default/assets/wondergem/stylesheets/scaffolding.scss

Btn color on hover used to be body copy color. Changed btn:hover color to white for better readability.

Fixes btn hover color

---

pom.xml
src/main/java/sirius/web/security/Helper.java
src/main/java/sirius/web/security/ScopeInfo.java

Merge remote-tracking branch 'origin/master' into aha/HelperFriends

Helper Friends

---

pom.xml
src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/health/console/ConsoleService.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/http/WebServer.java
src/main/java/sirius/web/security/ScopeInfo.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/services/ServiceDispatcher.java
src/main/java/sirius/web/templates/DefaultContentContextExtender.java
src/main/java/sirius/web/templates/LineBasedProcessor.java
src/main/java/sirius/web/templates/NamedRowProcessor.java
src/main/java/sirius/web/templates/RowProcessor.java
src/main/java/sirius/web/templates/SmartLineBasedProcessor.java
src/main/java/sirius/web/templates/Templates.java
src/test/java/sirius/web/templates/LineBasedProcessorSpec.groovy
src/test/java/sirius/web/templates/SmartLineBasedProcessorSpec.groovy
src/test/resources/smart-test1.csv
src/test/resources/smart-test2.csv

Merge remote-tracking branch 'origin/master' into aha/smartInput
#	pom.xml

smart input

---

src/main/java/sirius/web/http/Response.java
src/test/java/sirius/web/controller/TestController.java
src/test/java/sirius/web/http/WebServerSpec.groovy

Adds the possibility to provide a fallback handler if a tunnel fails.

Adds the possibility to provide a fallback handler if a tunnel fails.

---

pom.xml

Merge remote-tracking branch 'origin/master' into aha/TunnelFallback

Increments the release version

---

pom.xml
src/main/java/sirius/web/dispatch/DefaultDispatcher.java

Updates to the latest sirius-kernel

Updates to the latest sirius-kernel

---

src/main/java/sirius/web/http/Response.java

Fixes the javadocs provided for Response.tunnel

Fixes the javadocs provided for Response.tunnel

---

pom.xml
src/main/java/sirius/web/dispatch/DefaultDispatcher.java
src/main/java/sirius/web/templates/ContentHelper.java
src/main/resources/velocity/standard.vm

Adds a helper method to replace XML characters with appropriate entities.
This is also made visible in velocity as #xml macro to safely generate XML and HTML content.

Adds a helper method to replace XML characters with appropriate entities.

---

pom.xml
src/main/java/sirius/web/security/ScopeInfo.java

Fixes an accessibility issue when injecting other helpers of the same scope using @Helper

Fixes an accessibility issue when injecting other helpers of the same scope using @Helper

---

pom.xml
src/main/java/sirius/web/mails/Mails.java
src/main/resources/component-web.conf

Provides support to sign messages using DKIM

Provides support to sign messages using DKIM

---

pom.xml
src/main/java/sirius/web/dispatch/HelpDispatcher.java
src/main/resources/default/help/help.html
src/main/resources/default/help/index.html

so we don't have to tunnel it through the other templates

Write the helpSystemHomeURI into the WebContext

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/utilities.scss
src/main/resources/default/view/parts/formBar.html
src/main/resources/default/view/wondergem/template-script.html
src/main/resources/default/view/wondergem/template.html

This is to prevent forms from being submitted twice if the submit button gets double-clicked accidently

Enables the possibility to make submit buttons single-clickable

---

pom.xml
src/main/java/sirius/web/security/UserContext.java
src/main/resources/default/view/parts/textfield.html

Expands textfield by an error message

Textfield errormessages

---

pom.xml
src/main/java/sirius/web/templates/MultimapSmartRow.java
src/main/java/sirius/web/templates/SmartLineBasedProcessor.java
src/main/java/sirius/web/templates/SmartRow.java
src/main/resources/web_de.properties

- `fillField` also fills the field if the column does not exist
- `fillField` and `fillFieldIfPresent` return boolean whether the column exists
- better error message if a row (except the first one) contains too many columns, so the column mapping would throw an IndexOutOfBoundsException

Minor improvements of the SmartLineBasedProcessor

---

pom.xml
src/main/java/sirius/web/templates/MultimapSmartRow.java
src/main/java/sirius/web/templates/SmartRow.java

`SmartRow#contains(String)` now only returns true if the column is present *and filled*

Minor improvements of the SmartRow

---

pom.xml
src/main/java/sirius/web/http/Response.java

Now supports "and" in media-queries

Use the current version of server-sass

---

src/test/java/sirius/web/http/CORSSpec.groovy

Fix CORSSpec

---

pom.xml
src/main/resources/default/view/parts/checkbox.html

In case you want to display raw label or help Strings and not have them translated there are two new parameters in the checkbox template.
Bumps Versionnumber.

Modified CheckBoxTemplate

---

pom.xml
src/main/java/sirius/web/crunchlog/Crunchlog.java

We only want to persist the URI not the whole request
(which doesn't work anyway).

Fixes the crunchlog.

---

pom.xml
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/http/session/UserAgent.java
src/test/java/sirius/web/http/UserAgentSpec.groovy

From now on it is possible to determine if the current request was created by a deskop client or a mobile client. It is possible to distinguish between phones and tablets for mobile requests. Furthermore it is also possible to determine if a request was made by an Android device or an iOS device.

User agent detection

---

src/main/resources/default/assets/wondergem/featherlight/featherlight.css
src/main/resources/default/assets/wondergem/featherlight/featherlight.gallery.css
src/main/resources/default/assets/wondergem/featherlight/featherlight.gallery.js
src/main/resources/default/assets/wondergem/featherlight/featherlight.js

which fixes scrollbar appearing on big images

Updates featherLight to 1.7.6 + Custom changes from scireum-incubator/featherlight

---

src/main/resources/default/taglib/w/textarea.html.pasta

The old textarea did extend over the whole span so the Tagliatelle textarea should do the same.

Fixing widh of Tagliatelle textarea

---

src/main/resources/default/taglib/w/datefield.html.pasta

the input group class will mess up our css configuration for the input datefield

Removes an unnecessary div

---

src/main/resources/default/assets/wondergem/dragMe/dragMe.js
src/main/resources/default/taglib/w/page.html.pasta
src/main/resources/default/view/wondergem/template.html

Adds dragMe jQuery plugin to base template

---

src/main/resources/default/assets/wondergem/dragMe/dragMe.js

only works with left mouse button now

updates dragMe.js

---

src/main/resources/default/taglib/w/datefield.html.pasta

Make no past dates for date fields an option

---

src/main/java/sirius/tagliatelle/macros/LimitMacro.java

Macro for Tagliatelle to call the limit function of the Strings class.

Limit macro

---

src/main/java/sirius/tagliatelle/Template.java

Otherwise, constant null was used despite of an existing default value.

Permits to use default args when rendering with a context or arguments.

---

src/main/java/sirius/tagliatelle/macros/FormatByteSizeMacro.java

Macro for Tagliatelle to call the formatSize function of the NLS class.

Format byte size macro

---

src/main/java/sirius/web/controller/BasicController.java

Use Tagliatelle error page on controller fail

---

src/main/java/sirius/web/security/UserContext.java

added / in url in system state warning message that was missing because of Tagliatelle related changes

Fixes url in system state warning message (because of pasta changes)

---

pom.xml
src/main/java/sirius/web/data/ExcelExport.java

Amount can now be processed by ExcelExport and is handled as numeric. Futhermore, BigDecimal is also handled as numeric from now on.

Handling of Amount in ExcelExport

---

pom.xml
src/main/java/sirius/web/controller/Facet.java

This adds functionality to make the filter facets collapsible.

Allow filter facet collapsing

---

pom.xml
src/main/resources/default/templates/system/tag.html.pasta

Also fixes the breadcrumb link to the taglib itself

Outputs the description within a i:raw to allow html within the descriptions

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/utilities.scss
src/main/resources/default/taglib/w/imageUpload.html.pasta
src/main/resources/web_de.properties

Enables the image upload box to accept URLs

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/utilities.scss
src/main/resources/default/taglib/w/fileUpload.html.pasta
src/main/resources/default/taglib/w/imageUpload.html.pasta
src/main/resources/default/templates/wondergem/page-script.html.pasta

Also displays a link to the uploaded file.

Adds optional reset buttons to the upload taglibs and allow URLs in the file upload

---

pom.xml
src/main/java/sirius/tagliatelle/expression/MethodCall.java
src/main/java/sirius/web/controller/Controller.java
src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/Response.java

Forward port of https://github.com/scireum/sirius-web/pull/347

Supports calling varargs methods in Tagliatelle templates

---

pom.xml
src/main/java/sirius/web/mails/MailLog.java
src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/mails/SendMailTask.java

... which can be quite useful for filtering logged mails

Allows for specifying the type of a mail

---

pom.xml
src/main/resources/default/taglib/w/radio.html.pasta

 Allows passing HTML in the label Parameter of the radiobutton taglib

---

pom.xml
src/main/resources/default/help/footer.html.pasta
src/main/resources/default/help/menu.html.pasta
src/main/resources/default/taglib/h/page.html.pasta
src/main/resources/default/taglib/w/page.html.pasta

+ show helpsystem in disaster mode

 Adds posibility to add custom menu and footer for the helpsystem

---

pom.xml
src/main/resources/default/templates/wondergem/page-script.html.pasta

the function preventBubble() does not exist

Fix wrong js-function name

---

pom.xml
src/main/resources/default/taglib/h/backButton.html.pasta

Adds the possibility to add additional buttons to the form bar

Render body in h:backButton

---

pom.xml
src/main/resources/default/assets/wondergem/autocomplete/autocomplete.css

- better highlighting of active rows
- smaller preview imgs
- less padding between rows

Improves styling of default autocomplete plugin. Uses less space:

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

Only positions the div again if necessary
Also uses the outerHeight instead of height

Corrects the reposition method

---

pom.xml
src/main/java/sirius/tagliatelle/macros/SplitAtLastMacro.java
src/main/java/sirius/tagliatelle/macros/SplitMacro.java

The split methods from the Strings class are now available in templates.

Macros for accessing split methods

---

pom.xml
src/test/java/sirius/web/http/TestResponse.java

Depending on the ResponseType, different fields needed to be checked for emptiness. The new helper method chooses the right field automatically.

Creates a helper method to find out if a TestResponse contains response data

---

pom.xml
src/main/java/sirius/tagliatelle/macros/DateComparingMacro.java
src/main/java/sirius/tagliatelle/macros/IsAfterMacro.java
src/main/java/sirius/tagliatelle/macros/IsBeforeMacro.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/resources/templates/timeMacros.html
src/test/resources/templates/timeMacros.html.pasta

The provided macros can determine if a given date as a String, LocalDate or LocalDateTime is before or after another given date or now if no secons date is given. This can be used render certain parts in a limited time frame.

Macros for comparing dates

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Uses the configured delimiter for the initialization of the tokenfield input as well

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/polyfill.html.pasta

IE requires that one for the image upload 
- Fixes: SE-3904

Adds startsWith to the polyfill script

---

pom.xml
src/main/java/sirius/web/dispatch/AssetsDispatcher.java

If a patch is applied, the id will change and the new resource
will be loaded.

Cached assets loaded via a dynamic ID infinitely long.

---

pom.xml
src/main/java/sirius/web/dispatch/HelpDispatcher.java
src/main/java/sirius/web/http/Response.java
src/main/resources/web_de.properties
src/main/resources/web_en.properties

We now render the index template and
express our regrets to the user instead of
failing with an stacktrace straight from hell.

Handles missing help topics gracefully.

---

pom.xml
src/main/java/sirius/tagliatelle/macros/FormatDateMacro.java
src/main/java/sirius/tagliatelle/macros/FormatTimeMacro.java

* Adds @formatDate and @formatTime

Date&Time Macros

---

pom.xml
src/main/java/sirius/web/crunchlog/CrunchlogKernel.java

Changes the default file extension, to make them easier to open
Adds command to close the currently open crunchlog file so it can be viewed instantly.

Improves crunchlog, so they can be more easily debugged

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/plugins.scss
src/main/resources/default/taglib/w/autocompleteSingleSelect.html.pasta
src/main/resources/default/templates/wondergem/page-script.html.pasta

 Allows results inside autocompleteSingleSelect to be multiline

---

pom.xml
src/main/resources/default/taglib/w/autocompleteSingleSelect.html.pasta
src/main/resources/default/templates/wondergem/page-script.html.pasta

This allowes user defined input which was not suggested.

Extends the autocompleteSingleSelect taglib

---

src/main/java/sirius/tagliatelle/compiler/Parser.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/java/sirius/tagliatelle/InnerClassTestObject.java
src/test/resources/templates/inner-class.html.pasta

E.g. via "obj.as(path.to.class$innerclass.class)"

Allow to cast objects to inner classes

---

src/main/java/sirius/web/http/UserAgent.java
src/main/resources/default/templates/wondergem/page-script.html.pasta

Also fixes an issue where IE can not unselect a selected value because it can not select
an empty value on its own (This is also a safari issue)
- Fixes: SE-4768

Provides a fix for IE Placeholder Bug for select2

---

src/main/resources/default/taglib/w/deleteButton.html.pasta

Offers the delete link also as button

---

src/main/resources/default/assets/wondergem/stylesheets/wells.scss
src/main/resources/default/taglib/w/infobox.html.pasta

Improves the design of infobox wells

---

src/main/java/sirius/web/http/LangHelper.java

- currentLang can be null, if we are not able to parse the acceptLanguage
- add a private constructor as we are using the class as a helper

Use ofNullable, add private constructor

---

src/main/java/sirius/web/http/WebContext.java

Adds the ability to set the domain attribute for cookies in .conf file

---

src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/IPRange.java
src/main/java/sirius/web/http/WebServer.java
src/main/resources/component-web.conf
src/test/java/sirius/web/http/IPRangeTest.java

Improves metrics output to match the expectations of prometheus.io

Better statistics output for prometheus.

---

src/main/java/sirius/web/mails/SMTPConfiguration.java

For better versioning.
Tags: smtp

Add deprecation until next major release

---

src/main/resources/default/taglib/w/autocompleteMultiSelect.html.pasta
src/main/resources/default/taglib/w/multiSelect.html.pasta
src/main/resources/default/templates/wondergem/page-script.html.pasta

Dynamically adds and removes placeholders from the tokenfield, since the underlying lib will always show it

Don't show placeholder in tokenfield if token is present

---

src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Adds an onCreatedToken event handler to tokenfield

---

src/main/resources/default/templates/wondergem/page-script.html.pasta
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

When the user entered a search and then selected a suggestion from the autocomplete, the suggestion was not added as token

Fixes Internet Explorer bug in MultiSelect

---

src/main/resources/default/mail/mail-footer.html.pasta
src/main/resources/default/mail/mail-header-styles-default.html.pasta
src/main/resources/default/mail/mail-header.html.pasta
src/main/resources/default/taglib/mail/button.html.pasta
src/main/resources/default/taglib/mail/greeting.html.pasta
src/main/resources/default/taglib/mail/hr.html.pasta
src/main/resources/default/taglib/mail/link.html.pasta
src/main/resources/default/taglib/mail/subHeading.html.pasta
src/main/resources/default/taglib/mail/table.html.pasta
src/main/resources/default/taglib/mail/tableContent.html.pasta
src/main/resources/default/taglib/mail/tableFullWidth.html.pasta
src/main/resources/default/taglib/mail/tableHeader.html.pasta
src/main/resources/default/taglib/mail/tableInline.html.pasta
src/main/resources/default/taglib/mail/template.html.pasta
src/main/resources/default/taglib/mail/text.html.pasta

Fixes: SIRI-18
moved from https://github.com/scireum/sirius-biz/pull/241

Creates mail taglibs and a default template

---

src/main/resources/default/templates/wondergem/page-script.html.pasta
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Prevents wrong token autcreations in autocomplete tokenfield

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

This allows JS to change the selection and have the tokenfield represent this change. Also send change-events if the selection is changed.

SIRI-43 Mirror changes on the original select

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

Or else there will be a row with no text and function in the autocomplete dropdown

Don't add option as suggestion, if label and value is empty

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

This gives the possibility to handle errors given by the server

Add 'onServiceError' event to MultiSelects

---

src/main/resources/default/taglib/w/datefield.html.pasta

If we set the mindate with the current time it becomes impossible to set the current day.

Set the correct mindate

---

src/main/resources/default/taglib/w/autocompleteMultiSelect.html.pasta
src/main/resources/default/taglib/w/autocompleteSingleSelect.html.pasta
src/main/resources/default/taglib/w/multiSelect.html.pasta
src/main/resources/default/taglib/w/singleSelect.html.pasta
src/main/resources/default/taglib/w/textfield.html.pasta

 Stops double posting of singleSelect&multiSelect values

---

src/main/resources/default/taglib/w/textfield.html.pasta

Add tabindex to textfield taglib.

Adds a tabindex parameter to the textfield

---

src/main/java/sirius/web/security/UserInfo.java

This is used in the new Method UserInfo.getProtocolName(), used to further identify a user.

Adds an optional appendix for the username in UserInfo.

---

src/main/java/sirius/web/health/SystemController.java

Otherwise the "login" template will not be shown once the user
has been logged out :(

Properly delivers the console template without caching.

---

src/main/java/sirius/web/data/CSVProcessor.java
src/main/java/sirius/web/data/XLSProcessor.java

When using processes of sirius biz, this is quite an expensive operation.

Limits the excessive updates of the task context state.

---

src/main/resources/default/templates/wondergem/page-script.html.pasta

This is called "right" and is auto added if needed.

Permits to specify an additional axis per dataset.

---

src/main/resources/default/taglib/w/menuDropdown.html.pasta
src/main/resources/default/taglib/w/menuItem.html.pasta

to be consistent with icon parameters in other templates

 Removes prefix from menu icons template parameter

---

src/main/resources/default/taglib/w/textfield.html.pasta

- Adds option to force appearance of a text-field's (empty) label

Textfield with Forced Label

---

src/main/java/sirius/tagliatelle/emitter/BlockEmitter.java
src/main/java/sirius/tagliatelle/emitter/DynamicInvokeTemplateEmitter.java
src/main/java/sirius/tagliatelle/emitter/Emitter.java
src/main/java/sirius/tagliatelle/emitter/InvokeTemplateEmitter.java
src/main/java/sirius/tagliatelle/rendering/GlobalRenderContext.java
src/main/java/sirius/tagliatelle/rendering/LocalRenderContext.java
src/main/java/sirius/tagliatelle/tags/IncludeTag.java
src/main/java/sirius/web/http/Response.java
src/test/java/sirius/tagliatelle/DebugSpec.groovy
src/test/resources/templates/debug/debug-args.html.pasta
src/test/resources/templates/debug/debug-css1.html.pasta
src/test/resources/templates/debug/debug-css2.html.pasta
src/test/resources/templates/debug/debug-expected.html
src/test/resources/templates/debug/debug-page.html.pasta
src/test/resources/templates/debug/debug-script1.html.pasta
src/test/resources/templates/debug/debug-script2.html.pasta
src/test/resources/templates/debug/debug.html.pasta

Core backend functionality to enable rendering trace in tagliatelle.
- active for `i:invoke`, `i:dynamicInvoke`, `i:render`;
- cookie setting from UI will be implemented separately.

Tagliatelle rendering debug/trace functionality

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

This enables to select a suggestion by calling _select.val('value').change()
if the given value is available as a suggestion.

Adds suggestion as non-selected options to select field

---

src/main/java/sirius/web/controller/Message.java
src/main/java/sirius/web/controller/MessageLevel.java
src/main/resources/default/templates/wondergem/page-messages.html.pasta

and uses the enum instead of string constants in the message class
- Fixes: SE-9177

Creates a message level enum

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/TunnelHandler.java

SIRI-156
See: https://blog.abelotech.com/posts/json-jsonp-correct-mime-type/

Uses the correct mime type for JSONP responses 

---

src/main/java/sirius/tagliatelle/macros/EpochTimeInDaysMacro.java
src/main/java/sirius/tagliatelle/macros/UnixtimeInDaysMacro.java

Adds a template macro to get the current unixtime in days

---

pom.xml
src/main/resources/default/assets/wondergem/autocomplete/multiselect.js
src/main/resources/default/taglib/w/multiSelect.html.pasta
src/main/resources/default/taglib/w/singleSelect.html.pasta

As the only thing it did was not transparent
Fixes: SIRI-186

Removes multiselect optional parameter

---

src/main/java/sirius/web/http/DispatcherPipeline.java

We now have less nested blocks and no longer
manipulate the loop variable (which is permitted
in Java but a terrible idea...).

Refactors the dispatch loop to avoid code inspections.

---

src/main/java/sirius/web/http/Response.java
src/test/java/sirius/web/controller/TestController.java
src/test/java/sirius/web/http/WebServerSpec.groovy

We now support tunneling POST requests and also adding custom headers
using the newly provided requestTuner.

Permits to fine-tune requests being tunneled.

---

src/main/java/sirius/web/http/MimeHelper.java

> https://scireum.myjetbrains.com/youtrack/issue/MIO-5373
- Adds media types for HEIC/HEIF

Media Types for HEIC/HEIF (MIO-5373)

---

src/main/java/sirius/web/http/WebContext.java

We already do this for the query string, so it makes sense to do the same for post parameters.

Fetches all available post parameters in a list in WebContext.get

---

pom.xml
src/main/java/sirius/web/services/JSONStructuredOutput.java
src/test/java/sirius/web/http/TestResponse.java
src/test/java/sirius/web/service/JsonOutputSpec.groovy

Required changes for the next kernel version

Version bump

---

pom.xml
src/main/java/sirius/web/data/XLSProcessor.java

SIRI-262: poi streaming lib change

---

src/main/java/sirius/web/resources/Resource.java

Allows to save a resource to a physical file

---

src/main/resources/default/taglib/w/checkbox.html.pasta
src/main/resources/default/taglib/w/multiSelect.html.pasta

Offers more optional parameters in the checkbox tag

---

pom.xml

Bumps sirius-kernel dev-19.10 -> dev-19.11 (fix translated date format)
- Fixes: SIRI-274

Bumps sirius libraries

---

src/main/java/sirius/tagliatelle/TagliatelleController.java
src/main/java/sirius/web/ErrorCodeException.java
src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/controller/Controller.java
src/main/java/sirius/web/controller/ControllerDispatcher.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/util/QRCodeController.java
src/test/java/sirius/web/controller/TestController.java
src/test/java/sirius/web/http/CompletionPromiseTestController.java
src/test/java/sirius/web/http/TestPipeliningController.java

This extends the HTTP status handling for JSON calls.

SE-10167: OMD HTTP status codes

---

src/main/java/sirius/web/health/console/CommandParser.java
src/main/java/sirius/web/health/console/ConsoleService.java

This now supports parameters which contain whitespaces.

Provides a robust command parser and uses it for the /system/console

---

src/main/java/sirius/web/controller/Route.java
src/main/java/sirius/web/controller/SubScope.java
src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/UserInfo.java

This permits to grand users only access to partial areas of an application.
E.g. this could be used to create "API only" users. Also this will be used
by sirius-biz to create "FTP only" users.

Permits to split an authentication scope into "sub scopes".

---

src/main/java/sirius/web/mails/SendMailTask.java
src/main/resources/component-web.conf
src/main/resources/scope-conf/mail.conf

- Trusts CA-signed mail servers by default

Fix: Mail Server Trust

---

pom.xml

sirius-kernel dev-20.2 -> dev-20.3

version bump sirius-kernel

---

src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java

Throwing a HandledException out of nowhere comes pretty
unexpected. We therefore collect up to 250 errors/warnings
and ignore/reject any further messages (without crashing).

Improves error handling.

---

src/main/java/sirius/web/security/UserContext.java

Until a clean solution has been made with SIRI-335.
Fixes: SIRI-333

Adds javadoc to reduce caveats by the misleading method name.

---

src/main/resources/default/assets/wondergem/datetimepicker/js/bootstrap-datetimepicker.js

Fixes readonly Datefield Bug that would enable to open the date picker (SIRI-337)

---

src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

Fixes a NPE when an image URL returns 404 when generating a PDF

---

pom.xml
src/main/java/sirius/web/services/JSONStructuredOutput.java

Uses the newly toMachineString of Amount and always prefers
NLS.toMachineString instead of value.toString().
This way we get proper formatting for numbers (Amount) and also e.g.
constant formatting for dates etc.

BREAKING CHANGE: Uses proper machine formats when outputting JSON.

---

src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/taglib/t/dropdownItem.html.pasta
src/main/resources/default/taglib/t/menuItem.html.pasta

Tycho: Allows to display an optional admin lock icon in tycho menu entries

---

pom.xml
src/main/java/sirius/pasta/noodle/compiler/CompileError.java
src/main/java/sirius/pasta/noodle/compiler/InputProcessor.java
src/main/java/sirius/pasta/tagliatelle/compiler/IfHandler.java
src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
src/main/java/sirius/web/ErrorCodeException.java
src/main/java/sirius/web/controller/Page.java
src/main/java/sirius/web/health/console/CommandParser.java

This is marked as breaking, as the parsii update was breaking (isWhitespace was previously isWhitepace).

Updates to the latest sirius-kernel, parsii and fixes intendation in CompileError.

---

src/main/java/sirius/web/controller/AutocompleteHelper.java

This is marked as breaking, as the API change might have some negative implications. However, almost all methods
were just deprecated and not removed yet.

Enhances the autocomplete helper and its suggestions.

---

src/main/resources/default/assets/wondergem/stylesheets/forms.scss

Multiselect:
Singleselect:
Fixes: SIRI-369

Customizes token autocomplete styling to match bootstrap

---

src/main/java/sirius/web/controller/Facet.java
src/main/java/sirius/web/controller/Page.java

- needs to be changed in products first

Undo page and facet deprecations

---

.drone.yml
README.md

actives a message to memoio if nightly test or build fails

---

pom.xml

Includes deprecations in NLS
Fixes: SIRI-368

Bumps sirius-kernel

---

src/main/resources/default/assets/wondergem/stylesheets/alerts.scss
src/main/resources/default/templates/wondergem/page-footer.html.pasta

extend wondergem footer like in tycho, fix color for success-alerts

---

src/main/resources/default/assets/tycho/styles/forms.scss
src/main/resources/default/taglib/t/booleanSelect.html.pasta
src/main/resources/default/taglib/t/checkbox.html.pasta
src/main/resources/default/taglib/t/datefield.html.pasta
src/main/resources/default/taglib/t/textfield.html.pasta

Tycho: Adds admin-only form field style & small bugfix

---

src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/assets/tycho/styles/typeface.scss
src/main/resources/default/taglib/t/modal.html.pasta

Instead of three seperate tags as in wondergem, the whole modal can now be constructed using the t:modal tag

Adds a tag for bootstrap modals 

---

src/main/resources/default/assets/tycho/styles/forms.scss
src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/taglib/t/page.html.pasta

Fixed Header & Footer on large screens & error color

---

src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/dispatch/DefaultDispatcher.java
src/main/resources/component-web.conf
src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/assets/tycho/styles/tag.scss
src/main/resources/default/taglib/t/datacard.html.pasta
src/main/resources/default/taglib/t/filterbox.html.pasta
src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
src/main/resources/default/taglib/t/infoLine.html.pasta
src/main/resources/default/taglib/t/navboxLink.html.pasta
src/main/resources/default/taglib/t/smartFormatTemporal.html.pasta
src/main/resources/default/taglib/t/tags.html.pasta

Ports some Wondergem templates to Tycho and fixes some existing ones.

---

src/main/resources/default/assets/tycho/scripts/form.js
src/main/resources/default/taglib/t/deleteLink.html.pasta

Ports delete link template to tycho

---

src/main/resources/default/assets/tycho/styles/page.scss

Prevents long navbar menus from being cut off

---

src/main/resources/default/assets/tycho/styles/typeface.scss

Adds a helper class for setting whitespace to pre line

---

src/test/resources/test.conf

Removes a deprecated NLS setting

---

src/main/resources/default/assets/common/common.js.pasta

+ Removed 1 empty line as the file ends with 2 empty lines

Fixes scoping in common.js

---

src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js

Includes https://github.com/scireum/token-autocomplete/pull/49 and https://github.com/scireum/token-autocomplete/pull/50.
Fixes: SIRI-475

Upgrades to the latest token-autocomplete.

---

src/main/java/sirius/web/http/InputStreamHandler.java
src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

Also increases buffer and default read write timeouts
SIRI-476

Improves error handling of file & image upload tags 

---

src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

Only reloads after all files have completed uploading

---

src/main/resources/default/assets/tycho/styles/buttons.scss
src/main/resources/default/assets/tycho/styles/forms.scss
src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/taglib/t/imageUpload.html.pasta

Improves styles of imageUpload tag and gives it a fixed height

---

src/main/resources/default/taglib/t/radio.html.pasta

Provides a radio button taglib for Tycho templates

---

src/main/resources/default/assets/tycho/scripts/overlay.js.pasta
src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
src/main/resources/default/assets/tycho/styles/overlay.scss
src/main/resources/default/assets/tycho/styles/tycho.scss

This is a slightly modified copy of the component currently located in core.
Fixes: OX-7634

Introduces overlay JS component for Tycho

---

src/main/resources/component-web.conf

Adds new languages

---

src/main/resources/default/taglib/t/pageHeader.html.pasta

This completes #989 where one of the branches has been missed.

Tycho Page Header: Ellipsis 2

---

src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java

If a template in "default/extensions/name" and one in "extensions/name"
exists, we now only load the second (in accordance with all other places
where default templates are overwritten by ordinary ones with the same
name).
This way a default extension in a library can be provided which can be
overwritten in a product).

Properly implements the "default-template" mechanism for extensions.

---

src/main/java/sirius/web/util/BarcodeController.java

Fixes Barcode Generation for Code 128 and Data Matrix as they allow alphanumeric values or even raw data

---

src/main/resources/default/assets/common/styles/slider.scss

Shrinks the dots of the slider a little and fixes their padding.

---

src/main/resources/default/assets/common/scripts/slider.js.pasta
src/main/resources/default/assets/common/styles/overlay.scss

- Regularly resets slider view offsets
- Uses pixels for styling the overlay

Slider and Overlay

---

src/main/java/sirius/pasta/noodle/compiler/NoodleCompiler.java
src/main/java/sirius/pasta/tagliatelle/compiler/IncludeHandler.java
src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompilationContext.java
src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
src/main/java/sirius/web/health/Cluster.java
src/main/java/sirius/web/health/SystemController.java
src/main/resources/default/taglib/t/dot.html.pasta
src/main/resources/default/taglib/t/menuDropdown.html.pasta
src/main/resources/default/templates/system/load.html.pasta
src/main/resources/default/templates/system/state.html.pasta
src/main/resources/default/templates/tycho/page-dialogs.html.pasta
src/main/resources/default/templates/tycho/page-menu.html.pasta
src/main/resources/default/templates/wondergem/page-menu.html.pasta

some simple beautifying html-fixes

---

src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta

This will put a small lock icon next to it.

Allows to mark a delete dropdown item as admin only

---

src/main/resources/default/taglib/w/heading.html.pasta

Add parameter "adminOnly" to w:headline

---

src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/resources/scope-conf/mail.conf

SIRI-548 allow encoding of mails with umlauts to idn

---

src/main/resources/default/templates/system/console.html.pasta

> https://scireum.myjetbrains.com/youtrack/issue/SIRI-559

Console Scrolling (SIRI-559)

---

src/main/resources/default/assets/tycho/scripts/charts.js.pasta

Improves the rendering of charts.

---

src/main/resources/default/assets/tycho/styles/forms.scss
src/main/resources/default/taglib/t/datacard.html.pasta
src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

Adds a dropzone on hover to file & image upload

---

pom.xml
src/main/java/sirius/web/services/JSONStructuredOutput.java

By implementing the new `AbstractStructuredObject.writeAmount` method.
Needs:
- https://github.com/scireum/sirius-kernel/pull/394
Fixes: OX-8608

Handles Amounts in JSON Output

---

src/main/resources/default/assets/common/common-polyfills.js.pasta

Object.entries polyfill

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/SendFile.java
src/main/java/sirius/web/http/TunnelHandler.java

[OX-8755](https://scireum.myjetbrains.com/youtrack/issue/OX-8755)

Fixes buffer / pipeline management when tunneling responses through Netty.

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/taglib/t/page.html.pasta

Moves/applies a proper styling for the sticky footer of Tycho pages.

---

src/main/resources/default/assets/common/scripts/accordion.js.pasta

> https://scireum.myjetbrains.com/youtrack/issue/OX-8816

Accordion: Only Assign a Max-Height During Animation (OX-8816)

---

src/main/resources/default/assets/common/scripts/accordion.js.pasta

> https://scireum.myjetbrains.com/youtrack/issue/OX-8816

Accordion: Fixes Non-Animated Toggling (OX-8816)

---

pom.xml
src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/mails/SendMailTask.java
src/test/java/sirius/web/mails/MailsMock.java

Requires:
* https://github.com/scireum/sirius-kernel/pull/400

Retries sending emails up to 3 total attempts.

---

src/main/resources/default/assets/common/ie-polyfill.js.pasta
src/main/resources/default/assets/common/libs/url-search-params/url-search-params.js
src/main/resources/default/assets/common/scripts/continuity.js
src/main/resources/default/assets/common/scripts/continuity.js.pasta

Sample usage:
```javascript
continuity = new sirius.Continuity({
stateParameterName: 'history',
entryTypes: {
page: {
excludeFromParameter: true
},
navPro: {
excludeFromParameter: false
},
overlay: {
excludeFromParameter: false
}
}
});
continuity.registerStateEntryHandler('navPro', {
restore: function (entry) {
// Restore view by reading the entry properties
},
destroy: function () {
// Do something to clear the NavPro
}
});
continuity.registerStateEntryHandler('overlay', {
restore: function (entry) {
// Open the overlay with contents of the entry
},
destroy: function () {
// Close the overlay
}
});
function openOverlay() {
// Open the actual overlay element
// Allow the user to close the overlay when pressing back button
continuity.pushStateEntry('overlay', {
view: 'catalog',
catalogId: …
```

Provides JS Component for Handling History State and Deeplinks

---

src/main/resources/default/assets/tycho/styles/sirius-colors.scss

> [OX-8816](https://scireum.myjetbrains.com/youtrack/issue/OX-8816)

Design System (OX-8816)

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/common/scripts/overlay.js.pasta
src/main/resources/default/assets/common/styles/overlay.scss

To make it more flexible and usable in the OXOMI frontend.
Fixes: OX-8917

Overlay: Improvements and Adaptations

---

pom.xml
src/main/resources/default/assets/common/scripts/slider.js.pasta

> https://scireum.myjetbrains.com/youtrack/issue/OX-8881

Slider (OX-8881)

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/tycho/scripts/form.js.pasta

Breaking: `sirius.getFormData` -> `getFormData`
Careful: This is used in sirius biz!

Fix for IE11, which does not support for-of

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Continuity: Allows to force the creation of a new state when popping a state entry

---

src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/dispatch/SassFunction.java

Permits to provide custom SASS functions.

---

src/main/resources/default/assets/common/core.js.pasta

Fixes: [SIRI-608](https://scireum.myjetbrains.com/youtrack/issue/SIRI-608)

Adds read and write local store methods

---

src/main/resources/default/assets/tycho/styles/page.scss

improve layout for tycho on small views and for autocompletes

---

src/main/java/sirius/web/http/WebsocketDispatcher.java
src/main/resources/default/assets/common/scripts/slider.js.pasta
src/main/resources/default/assets/common/styles/slider.scss

> https://scireum.myjetbrains.com/youtrack/issue/OX-9113

Slider: Bugfix (OX-9113)

---

src/main/resources/default/assets/common/scripts/slider.js.pasta

Fixes: [OX-9133](https://scireum.myjetbrains.com/youtrack/issue/OX-9133)

Changes the z-index of the slider

---

pom.xml
src/main/java/sirius/web/http/WebServer.java
src/main/java/sirius/web/mails/Mails.java
src/main/resources/component-web.conf

Depends on:
* https://github.com/scireum/sirius-kernel/pull/406

Shortens some metric names a bit.

---

src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/templates/tycho/page-footer.html.pasta

For the visual effect, see: 
* https://github.com/scireum/sirius-biz/pull/1513

add margin/padding/border to node-info in footer

---

pom.xml
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/WebServer.java

Also renames it to RFC9110_INSTANT (RFC 9110 being the most current HTTP Semantics RFC), as RFC 822 actually allows single digit days.

Moves the new date time formatter to kernel

---

src/main/java/sirius/pasta/noodle/macros/InlineSvgMacro.java

> [OX-9299](https://scireum.myjetbrains.com/youtrack/issue/OX-9299)
Or combine with `inlineResource`?

Macro for Inlining SVG Files

---

src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/controller/ControllerDispatcher.java

This reverts commit 8a7940db28a4a955736ae1de47be4d018d115c7e.
This re-introduces a change from #1126 that was removed by #1128

Re-introduce correct HTTP error codes when reporting exceptions / errors for services.

---

pom.xml
src/main/java/sirius/pasta/noodle/macros/Base64ResourceMacro.java
src/main/java/sirius/web/dispatch/SiriusSassGenerator.java

> [SIRI-597](https://scireum.myjetbrains.com/youtrack/issue/SIRI-597)

Error Check in Base64 Macro (SIRI-597)

---

src/main/java/sirius/web/http/ChunkedOutputStream.java

NIO and Netty commonly use this exception to signal, that the underlying channel has been closed. We therefore throw the same exception, so that our handling code (e.g. in ContollerDispatcher.java) can detect this and properly ignore such errors (or at least not write them to the syslog) as this is an behavioral error, not a system error itself.

Throws a proper exception if the underlying channel is closed

---

src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/services/ServiceCall.java

> [OX-9400](https://scireum.myjetbrains.com/youtrack/issue/OX-9400)

`ServiceCall`: Logging of Exceptions (OX-9400)

---

src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/services/ApiResponsesFrom.java
src/main/java/sirius/web/services/DefaultErrorResponsesJson.java
src/main/java/sirius/web/services/DefaultErrorResponsesXml.java
src/main/java/sirius/web/services/PublicServices.java
src/main/java/sirius/web/services/SharedParameters.java
src/main/java/sirius/web/services/SharedResponses.java

...and adds some error code documentations.
Fixes: [OX-9330](https://scireum.myjetbrains.com/youtrack/issue/OX-9330)

Provides Shared Responses for API Docs

---

src/main/java/sirius/web/services/JSONCall.java

Fixes: [SE-12307](https://scireum.myjetbrains.com/youtrack/issue/SE-12307)

Enhances getInput according to sirius-kernel#423

---

src/main/resources/default/taglib/t/booleanSelect.html.pasta

Fixes: [9321](https://scireum.myjetbrains.com/youtrack/issue/OX-9321/Video-Modernisierung-Backend-User-Interface-Teil-3-Weitere-Seiten)

Adds the optional argument to the booleanSelect tag in order to be able to enforce a user to actively select a state

---

src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/taglib/t/booleanSelect.html.pasta
src/main/resources/default/taglib/t/dropdownItem.html.pasta
src/main/resources/default/taglib/t/menuItem.html.pasta
src/main/resources/default/taglib/t/multiSelect.html.pasta
src/main/resources/default/taglib/t/singleSelect.html.pasta
src/main/resources/default/taglib/t/textarea.html.pasta
src/main/resources/default/taglib/t/textfield.html.pasta

Fixes: [OX-9321](https://scireum.myjetbrains.com/youtrack/issue/OX-9321)

Adds a way to add an admin lock icon to multiple fields by introducing a @labelClass argument and the respective css class

---

src/main/java/sirius/pasta/noodle/compiler/SourceCodeInfo.java
src/main/java/sirius/pasta/noodle/compiler/ir/PopField.java
src/main/java/sirius/pasta/noodle/compiler/ir/PushField.java
src/main/java/sirius/web/controller/Route.java

Minor SonarQube Cleanup

---

src/main/java/sirius/web/services/JSONCall.java

~~Needs https://github.com/scireum/sirius-kernel/pull/438~~

SIRI-724: improve logging for jsoncall

---

pom.xml
src/main/java/sirius/web/health/SystemController.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/TunnelHandler.java

Fixes: [SIRI-731](https://scireum.myjetbrains.com/youtrack/issue/SIRI-731/NLS-convertDuration-refactorn)

Bumps up sirius-kernel and fixes breaking changes

---

src/main/java/sirius/web/services/JSONStructuredOutput.java

Fixes: [SIRI-758](https://scireum.myjetbrains.com/youtrack/issue/SIRI-758)

JSONStructuredOutput: Properly handles ClosedChannelException.

---

src/main/resources/default/taglib/t/navboxLink.html.pasta

In order to implement [OX-9654](https://scireum.myjetbrains.com/youtrack/issue/OX-9654), we need some more attributes.

More attributes for Navbox Links

---

src/main/resources/assets/design-system/icons.scss
src/main/resources/assets/design-system/misc.scss

Fixes: [OX-9768](https://scireum.myjetbrains.com/youtrack/issue/OX-9768)

CSS Design System: Icon and Tag Sizes

---

src/main/resources/default/taglib/t/datacard.html.pasta

> https://scireum.myjetbrains.com/youtrack/issue/OX-9666

Datacards: Mutual Alignment when Header is on the Left

---

src/main/resources/default/taglib/t/pageHeader.html.pasta

Permits extending the pageHeader tag

---

src/main/resources/default/taglib/t/additionalActions.html.pasta
src/main/resources/default/taglib/t/dropdown.html.pasta
src/main/resources/default/taglib/t/pageHeader.html.pasta

Tycho: Fixes height of the dropdown button

---

src/main/resources/default/templates/http/error.html.pasta
src/main/resources/default/templates/http/not-found.html.pasta

The UserAssistant from biz might otherwise perform pointless lookup for potentially dangerous URLs

Prevents any help lookups for error pages

---

src/main/resources/default/taglib/t/additionalActions.html.pasta

add text-nowrap to additionalActions ... to not break the layout

---

pom.xml
src/main/java/sirius/pasta/noodle/macros/JsonMacro.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/services/JSONCall.java
src/main/java/sirius/web/services/JSONStructuredOutput.java
src/main/java/sirius/web/util/JSONPath.java
src/test/java/sirius/web/http/TestRequest.java
src/test/java/sirius/web/http/TestResponse.java
src/test/java/sirius/web/http/UploadSpec.groovy
src/test/java/sirius/web/http/WebServerNightlySpec.groovy
src/test/java/sirius/web/http/WebServerSpec.groovy
src/test/resources/templates/define.html.pasta

Fixes: [SIRI-736](https://scireum.myjetbrains.com/youtrack/issue/SIRI-736)

Switches usage of FastJSON to Jackson for Handling JSONs

---

src/main/java/sirius/web/services/ApiResponsesFrom.java
src/main/java/sirius/web/services/ApiResponsesFromList.java

Fixes: [OX-9942](https://scireum.myjetbrains.com/youtrack/issue/OX-9942)

Allows multiple @ApiResponsesFrom annotations in a method

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta

Fixes: [OX-9378](https://scireum.myjetbrains.com/youtrack/issue/OX-9378)

Dialogs: Allows to add primary buttons to the footer

---

src/main/resources/default/assets/tycho/styles/tag.scss
src/main/resources/default/taglib/t/dot.html.pasta

Revises `<t:dot…` to:
- Maintain round shape under layout pressure
- Allow modifiable bottom margin
- Reduce DOM tree footprint

Renovation of `<t:dot…`

---

src/main/resources/default/taglib/t/checkbox.html.pasta
src/main/resources/default/taglib/t/modal.html.pasta

Fixes: [OX-8902](https://scireum.myjetbrains.com/youtrack/issue/OX-8902)

Tycho: Makes modal submit behavior configurable and checkbox labels clickable

---

src/main/java/sirius/web/security/Permissions.java

Permits to determine if a translation for a permission name is present.

---

src/main/resources/default/taglib/t/heading.html.pasta
src/main/resources/default/taglib/t/tag.html.pasta

Fixes: [SIRI-606](https://scireum.myjetbrains.com/youtrack/issue/SIRI-606)

Tycho: Allows ids for tags

---

src/main/resources/assets/design-system/text.scss

Fixes: [OX-10140](https://scireum.myjetbrains.com/youtrack/issue/OX-10140)

Adds some helper classes for defining the white-space handling

---

src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/Permissions.java
src/main/java/sirius/web/security/Profile.java
src/test/java/sirius/web/security/PermissionsSpec.groovy
src/test/resources/component-test-web.conf

Fixes: [OX-9955](https://scireum.myjetbrains.com/youtrack/issue/OX-9955)

Allows exclusions when applying profiles

---

src/main/resources/default/taglib/t/fileUpload.html.pasta

Before:
After:
Fixes: OX-10158

Fixes html containing error messages not being displayed properly for the t:fileUpload tag

---

src/main/resources/default/assets/common/core.js.pasta

Fixes the sirius.isEmpty method to work properly with js objects

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta

Replaces the append by appendChild in order to make the method IE11 compatible; and therefore enables the dialog to show up

---

src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta

Enhances the dropdownDeleteItem template by adding two parameters for better customization

---

src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/templates/system/console.html.pasta

minor css height-fixes for tycho and system/console

---

src/main/java/sirius/web/security/oauth/OAuth.java
src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
src/main/java/sirius/web/security/oauth/OAuthUtils.java

- some constants
- some helper function
- specific OAuth client and server functionality might be extended in the future

Adds initial support for OAuth2

---

src/main/resources/default/taglib/t/datacard.html.pasta

see https://github.com/scireum/sirius-biz/pull/1816
fixes: OX-10216

Optimizes user UI

---

pom.xml
src/main/java/sirius/web/security/oauth/OAuth.java
src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
src/main/java/sirius/web/security/oauth/ReceivedTokens.java

- adds support for our currently needed refresh call format
- parses received tokes from json into object

OAuth2 token refreshing util  

---

src/main/resources/assets/design-system/icons.scss
src/main/resources/default/assets/common/scripts/dialog.js.pasta
src/main/resources/default/assets/common/styles/dialog.scss

Fixes: [OX-9376](https://scireum.myjetbrains.com/youtrack/issue/OX-9376)

Dialog Wizard

---

src/main/resources/assets/design-system/margin-padding.scss
src/main/resources/default/assets/common/core.js.pasta

Adds sirius.deepExtend a plain ie11 compatible js alternative to jQuery's $.extend

---

src/main/resources/default/assets/common/core.js.pasta

Adds a sirius.postJSONFile js function which call the given URL, post the given params and file and retrieves the resulting JSON

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta
src/main/resources/default/assets/common/styles/dialog.scss

* Blocks skipping steps with invalid forms
* A bunch of helpers for working with validated wizard steps
* Different styling for disabled/blocked wizard steps
Fixes: [OX-9376](https://scireum.myjetbrains.com/youtrack/issue/OX-9376)

Dialogs: Improves Wizard Capability

---

src/main/resources/default/taglib/t/datacard.html.pasta

add additionalTags to datacards to provide information

---

src/main/resources/assets/design-system/flex.scss
src/main/resources/assets/design-system/misc.scss

Fixes: [OX-9771](https://scireum.myjetbrains.com/youtrack/issue/OX-9771)

Adds some more small css helper classes

---

src/main/java/sirius/web/controller/Page.java

Relates to:
- https://github.com/scireum/sirius-biz/pull/1803
Fixes: [SIRI-802](https://scireum.myjetbrains.com/youtrack/issue/SIRI-802)

Also set the DEFAULT_PAGE_SIZE to 24 in Page.

---

src/main/resources/assets/design-system/text.scss

Fixes: [OX-10460](https://scireum.myjetbrains.com/youtrack/issue/OX-10460)

Design System: Introduces text transform CSS helper classes

---

src/main/resources/default/assets/common/core.js.pasta

...due to an empty request body. The issue was caused by the polyfill. Sadly there is no better alternative.
Fixes: [OX-10439](https://scireum.myjetbrains.com/youtrack/issue/OX-10439)

Fixes an IE11 related issue where uploading a file was not possible

---

src/main/resources/assets/design-system/button.scss

Adds an active state for each sci button

---

src/main/resources/assets/design-system/misc.scss

Fixes: [OX-10460](https://scireum.myjetbrains.com/youtrack/issue/OX-10460)

Adds styles for thicker borders

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/tycho/scripts/form.js.pasta
src/main/resources/default/taglib/t/pagination.html.pasta

drive-by: fix (for me not known and not working due to a typo) feature for pagination.
you can use pagination via pressing SHIFT + Arrow-keys.
- fixes: SIRI-900

introduce variables for keys and use them on tycho pages

---

src/main/resources/default/assets/common/scripts/slider.js.pasta

- Fixes the slider's _fading/blending_ transition
- Generally animates switch between views when navigating via dots in single-column-mode

Slider: Fixes (OX-10502)

---

src/main/resources/default/taglib/t/sidebar.html.pasta

...the flag is true by default -> therefore the sidebar behaves like before -> not breaking
Fixes: SIRI-890

Adds a flag to the sidebar which permits to disable the sidebar if it is empty

---

src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css

This includes the changes of:
- https://github.com/scireum/token-autocomplete/pull/71

Updates token autocomplete to latest version

---

src/main/resources/default/templates/system/info.html.pasta

small design enhancement for system/info

---

pom.xml
src/main/java/sirius/pasta/tagliatelle/macros/GenerateIdMacro.java
src/main/java/sirius/web/http/CSRFHelper.java
src/main/java/sirius/web/http/DispatcherPipeline.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/http/WebServerHandler.java
src/main/java/sirius/web/http/WebsocketHandler.java
src/main/java/sirius/web/security/SAMLHelper.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/templates/LegacyDefaultGlobalsHandler.java
src/main/resources/default/taglib/t/page.html.pasta
src/main/resources/default/taglib/w/page.html.pasta
src/test/java/sirius/web/http/TestRequest.java
src/test/kotlin/sirius/web/controller/PageTest.kt

Fixes: [OX-10601](https://scireum.myjetbrains.com/youtrack/issue/OX-10601)

Replaces calls to deprecated methods

---

src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

Generating PDFs with images often led to OOM exceptions. The reason for this is the way we resolve the resources.
This PR uses a different method, which is much more economical. Therefore we have to upscale the image source more often instead of downscaling.
Fixes: SE-13196
Memory usage Old vs New:

Reduces memory usage of resolving the resource

---

src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

For very large images that would fall out of the box in both height and width, both must be scaled down.

Fixes scaling of images

---

src/main/resources/default/assets/tycho/styles/sidebar.scss

https://github.com/scireum/sirius-web/assets/36069303/90b1796b-1f37-4787-ad5f-c4c534db0504

Fix: Transition Animation of Bootstrap Nav Links

---

src/main/resources/default/taglib/t/textfield.html.pasta

Implements a new regex pattern by adding a new attribute and checking if it has been filled

Implements a regex pattern for input in tycho textfields

---

src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css

This includes changes of:
- https://github.com/scireum/token-autocomplete/pull/72
- https://github.com/scireum/token-autocomplete/commit/8e838daba348b505a899833f177cf50604bfc5c6
Fixes: [OX-10841](https://scireum.myjetbrains.com/youtrack/issue/OX-10841)

Update token autocomplete to latest version

---

pom.xml
src/main/java/sirius/web/security/oauth/ReceivedTokens.java

Update sirius parent to version with Jackson downgrade

---

src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
src/main/resources/default/taglib/t/inlineInfo.html.pasta

Fixes erroneous class attributes.

Fix: Icon Info

---

pom.xml
src/test/kotlin/sirius/web/http/FirewallTest.kt

This is an up to date implementation of the Jakarta mail and activation APIs.

Switch to Eclipse Angus for running Jakarta mail implementation

---

src/main/resources/default/taglib/t/timefield.html.pasta

- This PR fixes or works on following ticket(s): [SE-13639](https://scireum.myjetbrains.com/youtrack/issue/SE-13639)

add a tycho tag for render timefields in tycho pages

---

src/main/resources/default/assets/common/core.js.pasta

- This PR fixes or works on following ticket(s): [SIRI-965](https://scireum.myjetbrains.com/youtrack/issue/SIRI-965)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/1998

SIRI-965: Moved methods from sirius-biz to sirius-web to reuse common methods

---

pom.xml

Mostly to fix flyingsaucer logging issue
- This PR fixes or works on following ticket(s): [SE-13656](https://scireum.myjetbrains.com/youtrack/issue/SE-13656)

Upgrades library versions

---

src/main/resources/default/taglib/t/singleSelect.html.pasta

- This PR fixes or works on following ticket(s): [OX-11038](https://scireum.myjetbrains.com/youtrack/issue/OX-11038)

SingleSelect - Fixes a warning that occurred when no dependencyFieldId was given

---

pom.xml

- This PR is related to PR: 
https://github.com/scireum/sirius-kernel/pull/534

BREAKING: update kernel-version to use new Value#ignore

---

src/main/resources/default/taglib/t/searchHeader.html.pasta

- This PR fixes or works on following ticket(s): [OX-11093](https://scireum.myjetbrains.com/youtrack/issue/OX-11093)

Allows the searchHeader to be sticky

---

src/main/java/sirius/pasta/noodle/macros/Base64Macro.java
src/main/java/sirius/pasta/noodle/macros/Base64ResourceMacro.java
src/main/java/sirius/pasta/noodle/macros/InlineSvgMacro.java
src/main/java/sirius/pasta/noodle/macros/InlineSvgResourceMacro.java
src/main/java/sirius/pasta/noodle/macros/SvgMacro.java
src/main/java/sirius/pasta/noodle/macros/SvgResourceMacro.java
src/test/kotlin/sirius/pasta/noodle/macros/InlineSvgMacroTest.kt
src/test/kotlin/sirius/pasta/noodle/macros/InlineSvgResourceMacroTest.kt

These can then be implemented for custom data sources.
- This PR fixes or works on following ticket(s): [SE-13745](https://scireum.myjetbrains.com/youtrack/issue/SE-13745)
- This PR is related to PR: scireum/scireum-core/pull/1113

Extract some common code into abstract macros

---

src/main/resources/default/templates/tycho/page-menu.html.pasta

(both displayed here only to have a look)
- This PR fixes or works on following ticket(s): [SIRI-1040](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1040)

outputs if a system is started as dev or staging.

---

pom.xml
src/main/java/sirius/web/http/Response.java
src/main/resources/default/templates/tycho/page-menu.html.pasta

also fix breaking usage of setRequestTimeout
- This PR fixes or works on following ticket(s): [SIRI-1043](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1043)

SIRI-1043 updates async-http-client to newest version as suggested by dependabot

---

src/main/resources/assets/design-system/button.scss
src/main/resources/assets/design-system/misc.scss
src/main/resources/assets/design-system/table.scss

- This PR fixes or works on following ticket(s): [SE-13735](https://scireum.myjetbrains.com/youtrack/issue/SE-13735)

SE-13735 Small fixes for the design system

---

src/main/resources/assets/design-system/icons.scss

Example Use-Case:
- This PR fixes or works on following ticket(s): [OX-11760](https://scireum.myjetbrains.com/youtrack/issue/OX-11760)

Adds plus and minus icons in text-soft and blue style

---

src/main/resources/assets/design-system/icons.scss

Before:
After:
- This PR fixes or works on following ticket(s): [OX-11886](https://scireum.myjetbrains.com/youtrack/issue/OX-11886)

CSS Design System - Centers the image when the actual SVG is not perfectly square

---

src/main/resources/assets/design-system/icons.scss

* Adds hover effects for multiple blue icons
* Adds white variants for multiple icons
* Adds text-soft variants for multiple icons
- This PR fixes or works on following ticket(s): [OX-11759](https://scireum.myjetbrains.com/youtrack/issue/OX-11759)

Adds icon variants for multiple icons

---

src/main/resources/assets/design-system/misc.scss

- This PR fixes or works on following ticket(s): [OX-11759](https://scireum.myjetbrains.com/youtrack/issue/OX-11759)

Adds overflow auto classes for y and x

---

src/main/resources/default/assets/common/scripts/sidebar-overlay.js.pasta
src/main/resources/default/assets/common/styles/sidebar-overlay.scss
src/main/resources/default/assets/common/templates/sidebar-overlay.html.mustache

- This PR fixes or works on following ticket(s): [OX-11785](https://scireum.myjetbrains.com/youtrack/issue/OX-11785)

Sidebar Overlay - Allow to place it on the right side of the screen

---

src/main/resources/assets/design-system/flex.scss
src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-grid.css

- This PR fixes or works on following ticket(s): [OX-11974](https://scireum.myjetbrains.com/youtrack/issue/OX-11974)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/12221

Implements new css variables for the justify-items styling information

---

src/main/resources/assets/design-system/icons.scss
src/main/resources/assets/images/icons/fontawesome/copy.svg

- This PR fixes or works on following ticket(s): [OX-11984](https://scireum.myjetbrains.com/youtrack/issue/OX-11984)

Add new copy icon from frontawesome free

---

src/main/resources/assets/design-system/icons.scss
src/main/resources/assets/images/icons/fontawesome/table-cells.svg

- This PR fixes or works on following ticket(s): [SE-14588](https://scireum.myjetbrains.com/youtrack/issue/SE-14588)

add svg icon for table/matrix-view from fontawesom

---

pom.xml
src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
src/main/java/sirius/web/http/WebServerHandler.java
src/main/java/sirius/web/util/LinkBuilder.java

Fix small issues found by Sonarqube regarding NPE safeness.
- This PR fixes or works on following ticket(s): [SE-14326](https://scireum.myjetbrains.com/youtrack/issue/SE-14326)

Fix small issues found by Sonarqube 

---

pom.xml
src/main/java/sirius/web/http/DispatcherPipeline.java
src/main/java/sirius/web/http/WebServer.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

Upgrading library versions. 
Mostly netty has notable changes. See commit message for details. 
Our mail dkim library is no longer maintained. We switched to the successor. See commit message for details. 
- This PR fixes or works on following ticket(s): [SIRI-1072](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1072)

3rd party library upgrades and switching utils-mail-dkim library

---

.drone.yml
pom.xml

Upgrades to java24 and sirius kernel
- This PR fixes or works on following ticket(s): [SIRI-1027](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1027)

Upgrades to java24 and sirius kernel

---

src/main/java/sirius/web/mails/SendMailTask.java
src/main/java/sirius/web/security/oauth/OAuth.java
src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
src/main/java/sirius/web/security/oauth/ReceivedTokens.java

Some fixes and improvements I implemented while implementing OAuth mail authentication (future commit).
- This PR fixes or works on following ticket(s): [SIRI-1060](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1060)

OAuth Fixes and Minor Improvements

---

src/main/resources/default/templates/system/api.html.pasta

Fix outbreaking layout
before vs now

enhance displaying api documentation

---

src/main/resources/default/assets/common/scripts/slider.js.pasta

- This PR fixes or works on following ticket(s): [OX-12065](https://scireum.myjetbrains.com/youtrack/issue/OX-12065)

Accessibility - Banner Slider - Add tabIndex to slider navigation arrows for accessibility
