scireum/sirius-web

pom.xml
src/main/java/sirius/web/http/Response.java

the "filename*=UTF-8''" notation will be honored by modern browsers and ignored by older browsers, which will use the "filename" value as the fallback.
http://greenbytes.de/tech/tc2231/#attfnboth

Content-Disposition filename also gives a UTF-8 encoded Filename

---

src/main/resources/default/assets/wondergem/stylesheets/utilities.scss

Chrome-Fix: Use also word-break to break long words in Tables

Word-break in Tables

---

pom.xml
src/main/java/sirius/web/security/Permissions.java

If multiple annoations of a type are present, one has to check for the container annotation, not the type itself (PermissionList instead of Permission)

Fixed "funny" behaviour of Java annotations API

---

src/main/resources/default/view/wondergem/template-script.html

Routes with JSONcall=true throwing exception output the error-message in json.message and json.error=true and so should every other json-call.
Through this fix, the Usermessage shown after an upload fails is the actual error message instead of just 'true'.

output the error message when fileUpload / imageUpload fails

---

src/main/java/sirius/web/mails/Mails.java

Prevents mails being sent to a .local address
This can be used for testing purposes. Addresses ending in .local
will not receive mails (but being simulated)...
Patchnote: eMails with .local will no longer receive emails

Prevents mails being sent to a .local address

---

src/main/java/sirius/web/http/WebServerHandler.java

Adds Access-Control-Allow-Credentials: true as CORS header
If the default facility handles CORS requests, we also allow credentials, as
this is required when making ajax calls while relying on cookies. Otherwise
cookies will be omitted from the call.

Adds Access-Control-Allow-Credentials: true as CORS header

---

pom.xml

Updates sirius-kernel to the latest version
Also removes the LATEST reference to the test-jar as maven is
too intelligent to do this corrently. We now resort to a version range.

Updates sirius-kernel to the latest version

---

pom.xml
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/security/ScopeDefaultConfigController.java
src/main/java/sirius/web/security/UserContext.java

Updates to the latest kernel and implements proper fork behaviour
A UserContext must not be shared between two threads as this
leads to intransparent behaviour, if one thread switches the user.
Therefore a copy is created, so that they initially share the same user
but can change it independently.

Updates to the latest kernel and implements proper fork behaviour

---

pom.xml
src/main/resources/default/view/wondergem/template.html
src/test/java/sirius/web/http/TestResponse.java
src/test/java/sirius/web/security/UserContextHelper.java

Provides access to the UserContext which was active while creating a test response.
This can be used to ensure that no / or proper error messages were created
while handling a request.

Provides access to the UserContext which was active while creating a test response.

---

src/main/resources/default/assets/wondergem/stylesheets/tables.scss

Font awesome uses an extra class (.fa-fw) for spacing which we try to avoid so we don't have to change so many templates.

Sets fixed icon width in tables

---

pom.xml
src/main/java/sirius/web/controller/ControllerDispatcher.java
src/main/java/sirius/web/services/ServiceCall.java

Ignores ClosedChannelExceptions, as they only pollute the log without adding any insight

Ignores ClosedChannelExceptions, as they only pollute the log without adding any insight

---

pom.xml
src/main/java/sirius/web/templates/rythm/RythmConfig.java

Always removes pre-compiled templates from the cache directory.
Sometimes rythm doesn’t recompile changed templates, therefore
a startup should provide a clean environment.

Always removes pre-compiled templates from the cache directory.

---

src/main/resources/default/assets/wondergem/stylesheets/navs.scss

Used to be in copy color; now also in white like link text. Enhances visibleness.

Fixes icon color on hover, focus and active in nav-list

---

pom.xml
src/main/java/sirius/web/security/UserContext.java

Tests sometimes failed because they expected no [Messages](http://sirius-lib.net/apidocs/sirius-web/sirius/web/controller/Message.html) to be present in the response, but got some `System state is ...`-Messages

Disables the system state messages in testing environments

---

src/test/java/sirius/web/security/UserContextHelper.groovy

the Groovy method's name is `every`, not `all`

Fixes "Modifies the UserContextHelper so that one can see the actual messages if an assertion fails"

---

pom.xml
src/main/java/sirius/web/security/ScopeInfo.java

Adds a fallback for composites based on the ScopeInfo directly instead of the inner scope object
This is required by SellSite which attaches some components to the ScopeInfo, which is
not changed when the inner scope object (Shop) is refreshed

Adds a fallback for composites based on the ScopeInfo directly instead of the inner scope object

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/buttons.scss

Links that'll use .external-link will have an double-angle-right icon next to the link text

Adds external-link CSS helper

---

pom.xml
src/main/resources/default/view/wondergem/template.html

namely
```
11:09:13.832 ERROR [web-mvc-3|654ms] rythm - Ein Fehler ist aufgetreten: Failed to render the template 'view/wondergem/error.html': Cannot find extended template by name "view.wondergem.template.html"
Template: default:///view/wondergem/error.html
Relevant template source lines:
-------------------------------------------------
4: *
5: *  Copyright by scireum GmbH
6: *  http://www.scireum.de - info@scireum.de
7: *@
8: @args String message
>> 9: @extends(view.wondergem.template.html, title: NLS.get("BasicController.error"))
10: @render(head) {
11: <style>
12:     .breadcrumb {
13:         display: none;
14:     }
15: </style>
```

Removes an unnecessary comment in a rythm template which caused parse exceptions

---

pom.xml
src/main/java/sirius/web/security/UserInfo.java

This can be used as a better default for permissions configs
(leaving the values empty would yield the same but be less descriptive).

Adds another permission "enabled" which is always granted.

---

pom.xml
src/main/java/sirius/web/controller/ControllerDispatcher.java

As long as the user is logged in.
Up to know it was not possible to call a route without the necessary permission, log in and save the login information into the session.
As soon as the user left the 403 Page (or reloaded) the login was lost.

Attaches session even if some permission is missing

---

pom.xml
src/test/java/sirius/web/http/TestRequest.java

**Controller:**
```
@Routed(value = "/files/upload", preDispatchable = true)
public void uploadFile(final WebContext ctx, InputStreamHandler upload) {
...
```
**Test:**
```
InputStream resource = getClass().getResourceAsStream("/file.dat")
TestResponse response = TestRequest.POST("/files/upload", resource).asPreDispatched().executeAndBlock()
...
```

Makes it possible to test preDispatchable routes with the TestRequest class

---

src/main/java/sirius/web/dispatch/HelpDispatcher.java

e.g. (help/de/index) renders help/de/index.pasta if available, else it tries help/de/index.html

Makes HelpDispatcher able to find a matching template from a URI without file extensions 

---

src/main/java/sirius/tagliatelle/tags/ExtensionsTag.java

The downside is, that strings need to be put in
like 'this'

Makes i:expression accept all kinds of attributes.

---

src/main/java/sirius/tagliatelle/macros/EnumValuesMacro.java
src/main/java/sirius/tagliatelle/macros/InlineResourceMacro.java

We need this, as .values() is a static method, which we cannot invoke
in Tagliatelle due to security considerations.

Provides a macro to fetch all enum values of a given enum class.

---

src/main/resources/default/taglib/w/deleteLink.html.pasta
src/test/java/sirius/web/health/SystemControllerSpec.groovy

Default is null and this will not change the behavior
If page is set the query string containing the active facets is appended to the delete url
Fixes also a test of a ported template

Adds a page parameter to the deleteLink

---

src/main/resources/default/taglib/w/page.html.pasta

Some extensions used template- instead.

Use templates- for all extensions

---

src/main/java/sirius/tagliatelle/Tagliatelle.java
src/main/java/sirius/tagliatelle/tags/IncludeTag.java

Tagliatelle now happily compiles and invokes all .pasta files
as they're obviously meant to be templates.
However, for includes, only /assets is accepted, as this is the
directory(tree) to put files for inclusions anyway..

Improves security checks.

---

src/main/resources/default/templates/system/scope-config.html.pasta

Adds missing /system prefix in scope-config breadcrumbs.

Adds missing /system prefix in scope-config breadcrumbs

---

src/main/java/sirius/tagliatelle/compiler/CompileException.java

This can be used to tu fuel the error reporting of the ACE editor.

Adds a JSON output for CompileErrors.

---

src/main/java/sirius/tagliatelle/expression/MethodCall.java

Previously, we only checked, that the target method accepts all
given parameters, but we did not verify that all required parameters
are present.
This leads to an especially funny behaviour with overloaded methods,
as the order of methods is not defined, so this issue only occurs
randomly...

Ensures, that a method call actually supplies enough parameters.

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/alerts.scss

To make them more readable
tags: css
Before:
Now:
(Leftmost is hover state)

Changes the color of links inside of danger alerts

---

pom.xml
src/main/java/sirius/tagliatelle/compiler/Compiler.java

When using @if(){...} containing e.g. a javascript expression or function, the compiler couldn't find the correct ending
of the @if-block, as the first found closing "}" is used to detect the end of the if-block.
Example code:
@if (...) {
if () {
...;
}
}

Fix if-handler for static content

---

pom.xml
src/main/java/sirius/web/data/ExcelExport.java

It is now possible to render images in exported Excel sheets. As Excel is kind of special in handling images, the height and width of the cell containing the image are set separately.

Images for Excel export

---

pom.xml
src/main/java/sirius/web/data/ExcelExport.java

The calculation was correct in the linked stackoverflow. Dividing the width by two will result in distorted or overlapping images. This division was introduced due to wrong values in testing the export.

Don't divide Excel column with by 2

---

pom.xml
src/main/resources/default/view/wondergem/template.html

In legacy templates (rythm) we still included the minified css.
As we now use a single js and css with all libraries, we use the non
minified version as we hat to fix some relative paths.

Fixes a url for fontawesome in legacy templates.

---

pom.xml
src/main/java/sirius/web/http/WebContext.java

Some scenarios require the original order of the parameters (e.g. implementing the paypal ipn listener)

Uses a LinkedHashSet to not change the order of the request parameters

---

pom.xml
src/main/java/sirius/web/data/ExcelExport.java

Images can now be resized so images which are wider than the column they should be inserted in get resized to fit in.

Resizing of images in Excel export

---

pom.xml
src/main/java/sirius/web/health/console/HTTPCommand.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/http/WebServer.java
src/main/resources/component-web.conf

Otherwise we might complain about long running requests due
to slow (mobile) clients.
Also, we now use the correct CallContext when reporting the error and
made some shared variables volatile.

Separates the response time from the time to first byte.

---

pom.xml
src/main/java/sirius/web/resources/Resource.java

As OSX matches files case insensitive but linux case sensitive
typos in template names are only found in test or even worse
production systems. Therefore we detect this case and gently warn
the developer.

Warns if a resource with different casing is used.

---

pom.xml
src/main/java/sirius/tagliatelle/Template.java

If tagliatelle is used to render PDFs, we internally use HTML and
flying saucer to create those. Therefore we have to enable the appropriate
escaper.

Escape HTML entities in PDF (flying saucer) sources.

---

pom.xml
src/main/java/sirius/web/http/Response.java

However, we only do this, if CORS handling is enabled and also if
no conflicting header has already been set and of course if a CORS
request (origin) is present.

Apparently ACCESS_CONTROL_ALLOW_CREDENTIALS must always be set to true and not just for preflight requests.

---

pom.xml
src/main/java/sirius/web/templates/ContentHelper.java
src/main/java/sirius/web/templates/DefaultGlobalContextExtender.java

The new method strips XML from a given string. Furthermore, the ContentHelper can now be accessed in templates and scripts.

Method for stripping XML

---

pom.xml
src/main/resources/default/taglib/w/page.html.pasta
src/main/resources/default/templates/wondergem/page-electron.html.pasta

This shouldn't have andy side effects on non-npm / electron apps and
can also be overwritten by customizing page-electron.html.pasta

Adds a mini JS hack which is required to use jQuery inside an electron app.

---

pom.xml
src/main/java/sirius/web/http/WebContext.java

The bug occured by calling isContentProbablyXML() followed by getContent().
The first method call would change the readerindex of the byteBuf object and getContent would always return an empty byte array

Makes WebContext.getContent() reusable

---

pom.xml
src/test/java/sirius/web/health/ConsoleServiceSpec.groovy
src/test/java/sirius/web/health/NodeInfoServiceSpec.groovy
src/test/java/sirius/web/health/SystemControllerSpec.groovy
src/test/java/sirius/web/http/TestRequest.java
src/test/java/sirius/web/http/TestResponse.java
src/test/java/sirius/web/mails/MailsMock.java

+ adds support for all HTTP methods and shortcut method for `DELETE`
+ adds support for URL parameters in request other than GET
+ renames `execute` to `executeAsync` and `executeAndBlock` to `execute` , because `executeAndBlock` is the "normal" behaviour (used in 99.9% of all cases)
+ makes MailsMock thread-safe

Improves the TestRequest and MailsMock class

---

pom.xml
src/test/java/sirius/web/mails/MailsMock.java

The mail-sending Thread often isn't the same one (e.g. `web-mvc-5`) as the reading Thread (usually `main`).
Because we cannot know which Thread actually sends the mail, we cannot distinguish the mails this way.
Instead, we need to synchronize all mails-sending tests or do not verify the number of total sent mails.

Revert: "Enables MailsMock to be used by parallized tests" because it didn't work

---

pom.xml
src/main/java/sirius/web/tasks/ManagedTask.java

Now uses the correct css class for Tasks that are in the warning State.
Bumps the version.

Fixes incorrect css class reference for tasks in warning state

---

pom.xml
src/main/java/sirius/web/http/WebServerHandler.java

The TraceData in Sirius-Biz saves the origin of a change. This contains the system string from the corresponding task context. As some requests might contain long parameters, this would also be saved. However, as the field has only a size of 150, longer calls with many and long request parameters result in an exception. As the requesrt uri also might contain sensitive data, this is now stripped by only setting the uri without the request parameters in the TaskContext in the WebServerHandler like the ControllerDispatcher already does.

Shorten uri written to TaskContext as job

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/event-keys.html.pasta
src/main/resources/default/templates/wondergem/scripts/polyfill.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Bugfixes and Documentation
- Polyfills for better IE support
- adds a spinner option which indicates the waiting for response status of the autocomplete service
- adds multiple autocomplete instances per page option (including a shared cache)
- fixes a bug related to the autocomplete.hide method
- moves sirius.keys into own template file

Autocomplete Update

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

Also fixes a bug where the completions are shown even though the associated input field already lost its focus
Also adds a hide Method the library user can actually call.
- Fixes: SE-3401

Implements a method to get the current selection of the autocomplete

---

pom.xml
src/main/java/sirius/tagliatelle/macros/EscapeJSMacro.java

Single backslashes in strings raised a Javascript Error when they are parsed by `JSON.parse()` or `eval()`

Escapes backslashes in the EscapeJSMacro

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/event-keys.html.pasta

The bug happend only on some mobile devices because clicking on a completions element would
trigger a scroll event of the page before the click event was triggered.
The following click event would hold the completions div as target instead of the selected row.

Fixes a bug where the click event is not triggered

---

pom.xml
src/main/java/sirius/web/mails/MailSender.java

The language to use was only set when really sending the mail but rendering happened right when setting the template to use so the generated html and text content was always untranslated.

Fixes the nls support for sent mails

---

pom.xml
src/main/resources/default/templates/system/scripting.html.pasta

Because the default ID of w:codeEditor is no longer "editor", the variable on line 120 was undefined

Fixes Bug in /system/scripting 

---

pom.xml
src/main/java/sirius/web/data/XLSProcessor.java

Necessary, because SmartLineBasedProcessor will throw an exception, if a "Data"-row has more columns than the "Headings"-row. And we don't want that to be caused by empty columns in an excel file.

Trims trailing empty cells in excel imports

---

pom.xml
src/main/java/sirius/web/http/WebServerHandler.java

Firefox seems to omit this header in some cases and since it is
an otherwise unused OPTIONS request and must contain another CORS
header, we're pretty sure it is a preflight request.

Removes the check for the "Origin" header in a CORS pre-flight request.

---

pom.xml
src/main/java/sirius/tagliatelle/compiler/Compiler.java
src/main/java/sirius/tagliatelle/compiler/EvalExpressionHandler.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/resources/templates/macroSyntax.html
src/test/resources/templates/macroSyntax.html.pasta

this allows us to call ___macroName instead of @macroName
Necessary is this to use tagliatelle macros within js.pasta files without destroying the code
with the intellij code format

Implements second macro calling syntax

---

pom.xml
src/test/java/sirius/web/http/TestRequest.java
src/test/java/sirius/web/http/TestResponse.java

```
OXOMITestRequest.POST("/page?param1=value1")
.withParameter("param2", "value2")
```
Before: `/page?param1=value1?value2=value2`
After: `/page?param1=value1&value2=value2`
-----
The `Content-Disposition` header can now be tested:
`assert response.headers().get(HttpHeaders.CONTENT_DISPOSITION) == "attachment;filename=\"catalogs.xls\";filename*=UTF-8''catalogs.xls"`

Fixes a bug when creating the query string and sends the Content-Disposition header in TestRequests 

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

if no query parameter was set the init would fail and the allTokens array would be undefined
This would lead to an error when calling appendTokens
- Fixes: SE-3862

Corrects the tokenfield init

---

pom.xml
src/main/java/sirius/web/http/WebContext.java
src/test/java/sirius/web/http/WebContextSpec.groovy

The ControllerDispatcher uses the raw uri to determine the correct route for a request. Now this raw uri is also updated when withCustomURI or withCustomPath are used to rewrite the request.

Fixes rewriting the URI in the WebContext

---

pom.xml
src/main/java/sirius/web/controller/Message.java

Until now, only info, warn and error messages could be created via the Message class. However, sometimes it is needed to create a success message. To avoid creating these messages manually, this message type is now introduced for the Message class.

Introduce messages of type success

---

pom.xml
src/main/resources/default/assets/wondergem/stylesheets/tables.scss

when there is much content in the other cells, the first cell didn't always get what it deserves 
before:
after:

Forces the 10px width of colorized tables' first column

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Adds an clickable icon to the input field to allow for easier clearing of the tokens.
Until now tokens could only be cleared one by one.
Adds an onSpinnerHide and an onSpinnerShow event to the autocompleter to be able to prevent two icons at once.
Autoformating of some functions.

Tokenfield: Allow removal of all search tokens at once

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Templates using the tokenfield from Sirius Web might have some own handling of tokens. Therefore there also has to be a possibility to get notice of all tokens being cleared. This is now provided via an event.
Tags: tokenfield

Event for clearing tokens in the token field

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Corrects for a possible rounding error mistake of jquery width() which could cause two rows being displayed when there should only be one.
Version bump to 14.4.1

Always render Spinner and TokenRemovalIcon correctly

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

ios can't handle spans with click events.
Instead of just doing nothing it will blow up your whole browser. I guess thats how you tell
a user that the function does not work
- Fixes: SE-4033

Fixes an ios bug where the page freezes

---

pom.xml
src/main/java/sirius/web/services/RawServiceCall.java
src/main/java/sirius/web/services/ServiceCall.java
src/main/java/sirius/web/services/StructuredService.java
src/test/java/sirius/web/service/DefaultErrorService.java
src/test/java/sirius/web/service/ServiceErrorSpec.groovy
src/test/java/sirius/web/service/SpecialErrorService.java

In case Services need to create error responses using a specific format (e.g.) soap fault, webu, etc.
we need to be able to overwrite the default error handling.
By default nothing changes, which is why i implemented an interface default method rather then changing the interface to an abstract class.

Provides the possibility to overwrite the default error handling respons

---

pom.xml
src/main/java/sirius/web/http/Response.java

When the client closes the connection while we try to respond with assets, the channel is closed, the handlers are removed and we can not add a ChunkedWriteHandler before our default handler "handler"

Handle client-side connection-closes better

---

pom.xml
src/main/java/sirius/tagliatelle/macros/EscapeJSMacro.java
src/test/resources/templates/js-template.html
src/test/resources/templates/js-template.html.pasta

hab in MIO, OX und Sellsite keine Stelle gefunden, wo `escapeJS` nicht so vorkam: `var x = '@escapeJS(blubb)'`
`<w:jsTemplate>` hatte gar keine Usages

Preserves linebreaks in the EscapeJSMacro

---

pom.xml
src/main/java/sirius/web/controller/Page.java
src/test/java/sirius/web/controller/PageSpec.groovy

The code in the new Page item method was used many times as boilerplate code. To avoid this the code is now used in the class itself.
Tags: page

Easier item method for Page

---

pom.xml
src/main/java/sirius/tagliatelle/expression/MethodCall.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/java/sirius/tagliatelle/GenericTestObject.java
src/test/java/sirius/tagliatelle/TestObject.java

Using a real "getMethod" call takes generic type parameters
into account and selects the proper one. If this approach fails,
we use our own resolver using coercions etc.

Adds support so resolving generically overloaded methods.

---

pom.xml
src/main/resources/default/templates/wondergem/page-electron.html.pasta

- Revises electron integration to support injection via preloading script
- Allows to run web content with node integration disabled, thus improving security

Electron Integration

---

pom.xml
src/main/java/sirius/web/tasks/ManagedTaskExecution.java

Executed tasks counted the number of processed lines wrong. They relied on the count of the underlying average which was reseted after reaching its max value. Now the average also has a total count which can be used to count processed lines in jobs.
Tags: jobs

Use totalCount for TaskExecution

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

On tokenfield.clearTokens the allTokens array should be cleared as well as it contains all currently set tokens. If not resetted, after adding a token to the tokenfield would lead to the previous tokens plus the added token instead of the added token alone.
Tags: tokenfield

Clear tokenfield correctly

---

pom.xml
src/main/resources/default/templates/wondergem/page-script.html.pasta

Default behavior of select2 is to attach the dropdown to the body. But because modals block events on the body, the search field can't be used anymore. Fixes this by attaching the dropdown to the parent of the original select element.

 Fixes select2 inside modals

---

src/main/java/sirius/web/http/CSRFHelper.java
src/test/java/sirius/web/http/CSRFTokenSpec.groovy
src/test/java/sirius/web/http/TestRequest.java

Adds a SAFEPOST Request which allows for testing of Requests which require a valid CSRF Token.
Adds a dummy session to the TestRequestClass since a TestRequest itself has no ChannelHandlerContext.
Changes Visibility of LAST_CSRF_RECOMPUTE static string in CSRFHelper.
Adds a CSRFTokenSpec test whether SAFEPOST attaches a valid CSRF Token to the request.

Adds SafePost Testrequests with an attached CSRF Token

---

src/main/resources/default/assets/wondergem/stylesheets/navs.scss

Prevents ugly sub navs, where the sub-nav text extends past the menu boundary.

Tiny css Fix for sub navs

---

src/main/resources/default/assets/wondergem/fileupload/fileuploader.js

Corrects onComplete handler in Fileuploader.js, self._onComplete has to be run first or else firefox fires _options.onComplete too soon. Does not change functionality elsewhere

Firefox fix for fileuploaderjs

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/test/java/sirius/web/dispatch/AssetsDispatcherSpec.groovy
src/test/resources/assets/test/test.js.pasta
src/test/resources/assets/test/test.scss
src/test/resources/assets/test/test.txt

Currently invoking the dispatcher without any settings, should have applied a no-cache header.
This failed whenever we delivered a file (scss / static file) as this applied a cache setting by itself.
Also it turned out to be quite a bad decision not to cache assets at all.
We now apply the following policy:
- plain URLs (/assets/....) are cached for 1h by default
- dynamic urls (/assets/dynamic/TOKEN/...) are cached FOREVER
as the token will chance with the next patch / release
- /assets/no-cache/... will not be cached at all.

Cleans up the caching used by AssetsDispatcher.

---

src/main/java/sirius/web/http/CSRFHelper.java
src/main/java/sirius/web/http/WebContext.java
src/main/resources/component-web.conf

Currently the CSRF tokens can expire by staying on a page for a few minutes in the time window they expire. A request in this scenario would submit an expired CSRF token which can cause errors. Therefore CSRF tokens will now be recomputed in advance to avoid them expiring while staying a few minutes on a site.
Tags: csrf

Recompute CSRF tokens in advance

---

src/main/java/sirius/web/http/WebContext.java
src/test/java/sirius/web/controller/TestController.java
src/test/java/sirius/web/http/WebContextSpec.groovy

When setting a session value and determining if this modified the session, we ignored if other values already modified it. This especially happens when setting a value to null that already was null.

Properly detect if a session was modified

---

src/main/java/sirius/tagliatelle/compiler/CompilationContext.java
src/main/java/sirius/tagliatelle/compiler/IfHandler.java
src/main/java/sirius/tagliatelle/emitter/ConditionalEmitter.java
src/main/java/sirius/tagliatelle/tags/ElseTag.java
src/main/java/sirius/tagliatelle/tags/IfTag.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/java/sirius/tagliatelle/LocalScopeSpec.groovy
src/test/java/sirius/tagliatelle/TestHelper.java
src/test/resources/taglib/e/scope.html.pasta
src/test/resources/templates/invoke-scope.html.pasta

This commit changes the cleanup of local variables after a if-else using the if-handler ('@if') or if-tag('<i:if>').
The problem was, no elements were popped of the stack, when leaving such a block.

Proper cleanup of locals after if-else blocks

---

src/main/java/sirius/web/http/WebServerHandler.java

Otherwise upstream headers like X-Forwarded-Proto are never evaluated.

Only toggles the SSL flag if we know to be an SSL endpoint.

---

src/main/resources/default/templates/wondergem/page-script.html.pasta

On IE for wondergem singleSelects the selected item could not be deleted. This commit should fix the misbehaviour. The placeholder should only be disabled for autocompletes, not for normal selects.
Tags: IE, select2

Fix singleSelect on IE

---

src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/mails/SMTPConfiguration.java

The settings from the conf files were not taken into account anymore, because Value#asString(defaultValue) does not return the default value if the value is an empty string.
This misbehaviour was created in #524

Fixes the SMTPConfiguration class.

---

src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/security/UserManager.java

this methods binds the given user info the the user context and enables us to
extend the logic within the user manager.
This is necessary if we want to execute code after the user was sucessfully logged in
- Fixes: SE-4967

Moves the setCurrentUser Logik into the UserManager

---

src/main/java/sirius/web/http/CSRFHelper.java
src/main/java/sirius/web/http/WebContext.java
src/main/resources/component-web.conf
src/test/java/sirius/web/controller/TestController.java
src/test/java/sirius/web/http/CSRFTokenSpec.groovy

Previously, with unlucky timing and tabbed browsing a CSRF token provided could be invalid just seconds later. Storing the previous CSRF Token after recomputing ensures that a delivered token stays valid for at least of 1x the duration of http.csrfTokenLifetime and maximum 2x the duration of http.csrfTokenLifetime
Fixes: OX-4581

Stores the previous CSRF Token in the Session to ensure a minimal lifetime

---

src/main/java/sirius/web/security/UserInfo.java

We will use this to modify the permissions in the userManager.verifyUser method of the current user.
We need to create the userInfo here because we need access to the settingsSupplier and the userSupplier.
- Fixes: SE-5247

Provides an easy method to create a new userInfo from an existent one

---

src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Needs double-@ or else `"@return"` and `"@param"` will be interpreted as tagliatelle variables

Fixes tagliatelle errors in the documentation

---

src/main/java/sirius/web/http/MimeHelper.java

Fonts have their own MIME types. Some browsers expect the correct MIME type for a font therefore they are now introduced.
Tags: mime, font

MIME types for fonts

---

src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

Replace Element.scrollIntoView as this does not work in IE11 or older

 Replaces the method used to scroll the selected autocomplete row in view

---

src/main/resources/default/assets/wondergem/font-awesome/css/font-awesome.css

Some browsers (namely IE 11) sometimes do not load fonts if they are served with a query string.
Tags: ie, font, fontawsome

Remove query string for Fontawsome

---

src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

"configured" was never correctly set, and we check on "configured" before calling the "load"-method (see line 82 of this file). without calling the load method we never request data from the server... -> never show an autocomplete...

Fix Bug in 'service' of autocomplete

---

src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

If no name for the hidden input fields is defined, they should not be refreshed as they would be generated with undefinded as name. In addition some products rely on their on logic to handle these input fields.
Tags: tokenfield

Refresh on hidden fields can be disabled

---

src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/resources/component-web.conf

The setting value has to be in upper case.
Tags: smtp, configuration

Use valid default for SMTP protocol

---

src/main/resources/default/templates/wondergem/page-script.html.pasta
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta
src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

Previously, tokens were added because the tokenField lost focus and the *selectedRow*s value was written to the tokenField, which creates the token for this value when it loses value.
Without a total rewrite, we now add the token by hand just before the autocomplete gets hidden and we have a *selectedRow*

Adds Tokens to tokenfield from autocomplete without rendering them in the tokenfield

---

src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

When using the scrollbar in IE, the focus changes from the autocomplete input field to the autocomplete wrapper. In this case we just give the focus back to the input field to prevent focus loss.

Stops autocomplete from closing when scrolling in IE

---

src/main/resources/default/templates/wondergem/page-script.html.pasta

The automatic type conversion is leading to errors with data which is only numbers

Uses .attr instead of .data to avoid automatic type conversion of .data

---

src/main/resources/default/assets/wondergem/stylesheets/navs.scss

Disregarding Chinese,Japanese and Korean text, overflow-wrap(prior named word-wrap) is always superior. word-break always breaks at the current char and overflow-wrap first looks at break oppurtinities before breaking at the current char as a last resort.
Fixes: SIRI-31

Uses overflow-wrap instead of word-break to break sub-navs

---

src/main/java/sirius/web/mails/MailSender.java
src/test/java/sirius/web/mails/MailsSpec.groovy
src/test/resources/test_de.properties
src/test/resources/test_fr.properties

Using .textTemplate()/.htmlTemplate() together with .setLang(), its easy to forget to also translate the String provided to .subject() into the mail's correct language manually. This new method uses the language given in .setLang() automatically.

Adds Method to provide a nls key and optionally parameters as a mail subject.

---

src/main/java/sirius/tagliatelle/macros/I18nMacro.java
src/test/java/sirius/tagliatelle/I18nMacroSpec.groovy
src/test/resources/test_de.properties

NLS.get() supports a 'numeric' parameter which can be used to switch e.g. between singulara and plural version of a translation key.

Adds parameter to the i18n macro

---

src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

the removal of the element kills the event listener and needs to be added
again

Bugfixes the token removal element

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

Because browser-back-button already adds some tokens, but with wrong labels

Clear tokens before adding the initial selection

---

src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

Selecting an autocomplete suggestion via the keyboard keeps the input field focused so the user can keep typing.
Clinking inside the field after selecting a filtered suggestion reopened the previously filtered completions again without resetting the filter.
This is now done by executing the same code as when the input field gains focus when the field is clicked and the completions are not already visible.
Fixes: OX-5120

Resets completion filter when focused input field is clicked

---

pom.xml
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

When repostioning the autocomplete-wrapper during init, the wrapper might still have 'position: static'. jQuery adds position:relative to static elements when .offset(x) is called on them.
Since reposition is called anyway when the wrapper is shown, we don't actually need to reposition the wrapper during init.
> The .offset() setter method allows us to reposition an element. The element's border-box position is specified relative to the document. If the element's position style property is currently static, it will be set to relative to allow for this repositioning.

SIRI-61: Fixes autocomplete-wrapper getting position:relative style attribute

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js
src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

"this.delay = config.delayTime || this.delay;" sets delay to "this.delay" (400) if "config.delayTime" is 0, but we actually want to be able to set it to 0

Fix usage and reading of delayTime

---

src/main/resources/default/templates/wondergem/scripts/tokenfield.html.pasta

That we did not do this before, led to the underlying "select"-tag not being refreshed for w:xxxSelect when removing a token by clicking on an autocomplete entry

Call "onRemovedToken" handler when removing tokens programmatically

---

src/main/resources/default/templates/wondergem/scripts/autocomplete.html.pasta

The '.is(":focus")' check fails in Safari, when the field was focused via the '.focus()' method.

Use plain JavaScript for check if input field is focused

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

Because in Safari this still can have focus after being hidden, unlike other browsers

Also blur input field of SingleSelect after adding a token

---

src/main/resources/default/templates/wondergem/page-script.html.pasta

This also wasn't the case with the old library. And because it fires the change event, this leads to problems when the current day is actually forbidden.

Prevents date fields from filling automatically

---

src/main/java/sirius/web/security/UserContext.java

Allows for installing and verifying a user into the current Context directly.
Splits up the old bindUserToRequest logik into two seperate functions.

Allow for installing a user into the context directly 

---

src/main/java/sirius/web/security/UserContext.java

Or else the Messages of the MessageProvider and MaintenanceInfo will be added to the list everytime "public List<Message> getMessages()" is called, and therefore will be in the list multiple times if the method is called multiple times.
Messages where displayed twice, because sirius-biz calls "validate" which calls "getMessages()", when displaying a tenant, so "getMessages()" was called twice.
https://github.com/scireum/sirius-biz/blob/master/src/main/java/sirius/biz/tenants/TenantController.java#L145

Do not add Messages from MessageProviders to List in UserContext

---

src/main/java/sirius/web/security/Permissions.java
src/main/resources/component-web.conf
src/test/java/sirius/web/security/PermissionsSpec.groovy

Also permission profiles can now have complex names like
permission1+permission2,permission3 to reflect complex requirements
on when to provide a permission.

Applies permission profiles in order instead of randomly.

---

src/main/java/sirius/tagliatelle/Tagliatelle.java
src/main/java/sirius/web/templates/Templates.java
src/test/java/sirius/tagliatelle/TestGlobalContextExtender.java

Otherwise if a value is non-null at compile time but becomes null at render time,
the computed indices might change and the wrong variables will be accessed.

Removes filtering on null values.

---

src/main/java/sirius/web/data/ExcelExport.java

Could be called like this:
```
ExcelExport excelExport = ExcelExport.asXSLX(false)
excelExport.createSheet("test-sheet-1")
excelExport.addRow("sheet1-row1-col1", "sheet1-row1-col2", "sheet1-row1-col3")
excelExport.addRow("sheet1-row2-col1", "sheet1-row2-col2", "sheet1-row2-col3")
excelExport.createSheet("test-sheet-2")
excelExport.addRow("sheet2-row1-col1", "sheet2-row1-col2")
excelExport.addRow("sheet2-row2-col1", "sheet2-row2-col2")
excelExport.addRow("sheet2-row3-col1", "sheet2-row3-col2")
excelExport.writeToStream(new FileOutputStream("file-sheets.xlsx"))
```
or this:
```
ExcelExport excelExport = ExcelExport.asXSLX()
excelExport.addRow("row1-col1", "row1-col2")
excelExport.addRow("row2-col1", "row2-col2")
excelExport.addRow("row3-col1", "row3-col2")
excelExport.writeToStream(new …
```

Add possibility to add sheets to the ExcelExport

---

src/main/java/sirius/web/http/WebContext.java

This is e.g. possible if the toString method is called in an async job

Fixes an npe if the request is null

---

src/main/java/sirius/web/security/Permissions.java
src/main/java/sirius/web/security/Profile.java
src/main/resources/component-web.conf
src/test/java/sirius/web/security/PermissionsSpec.groovy
src/test/java/sirius/web/security/ProfileSpec.groovy
src/test/java/sirius/web/security/ProfileTest.groovy
src/test/resources/component-test-web.conf

... in which profiles are applied.
```
14:01:18.926 WARN  [main|20ms] permissions - Profile 'test-cascade-to-target-with-equal-priority' refers to a profile wich is applied ealier than itself ('cascade-target'). Therefore the profiles will not be resolved completely. Fix this by adding priorities.
14:01:18.928 WARN  [main|22ms] permissions - Profile 'test-cascade-to-target-with-lower-priority' refers to a profile wich is applied ealier than itself ('cascade-target'). Therefore the profiles will not be resolved completely. Fix this by adding priorities.

Adds warning when 'profile cascading' wont work, because of the order

---

src/main/java/sirius/web/data/ExcelExport.java

The SXSSF workbook is useful when writing large amounts of data which exceeds the amount of available heap. In contrast to the normal XSSF workbook which would eat up all heap and then fail the SXSSF workbook writes the exported rows to disk periodically which drastically relieves the heap usage and allows to export huge data sets.
One caveat is that the streaming mode can in some cases produce excel files that are incompatible with some clients. Because of this the SXSSF implementation is not used by default but the accessor of the exporter API has to make the choice which implementation is to be used.
Fixes: OX-5454

Adds the streaming XLSX workbook mode to the excel exporter

---

src/main/java/sirius/web/data/ExcelExport.java
src/test/java/sirius/web/data/ExcelExportTest.groovy

With the new Version of Apache-POI column-widths must be explicitly tracked if you want to be able to call "Sheet#autoSizeColumn(int column)" (like in ExcelExport#autosizeColumns)

Fix autosizing for cells in streaming ExcelExports

---

src/main/java/sirius/web/data/ExcelExport.java
src/test/java/sirius/web/data/ExcelExportSpec.groovy

"rows" was incremented, so it's not a valid row number for sheets which exeeded the row limit. This throws an exception when adding an auto-filter

Fix bug in createSheet method when max number of rows is reached

---

src/main/java/sirius/web/http/WebContext.java

The intention was to log this as this might be a security
breach / attempt. However, it turned out that in most of the cases,
the user just used multiple tabs or did other wired stuff with their
browser - therefore there is no need to jam the system log with these
messages.
Fixes: SIRI-81

Does not log an invalid CSRF token into the system log.

---

src/main/java/sirius/web/data/CSVProcessor.java
src/main/java/sirius/web/data/XLSProcessor.java

Ensures that after a file has been fully read, a final state
with the proper row count is emitted. As while processing,
the state update is frequency limited, this might end with
an invalid count which might confuse a user.
Fixes: SIRI-126

Outputs the proper row counter after processing a file.

---

src/main/java/sirius/tagliatelle/Tagliatelle.java

Previously the output was:
Some warningTemplate: xxx
now it is:
Some warning - Template: xxx

Fixes a typo when outputting tagliatelle warnings.

---

src/main/resources/default/taglib/w/imageUpload.html.pasta
src/main/resources/default/templates/wondergem/page-script.html.pasta

Using this, the file picker window will only allow to select a single file and when dropping multiple files into the upload area only the first file is uploaded.
The default behaviour when this parameter is not given is NOT changed.
Fixes: OX-5358

Adds a optional js parameter to restrict image upload box to a single file

---

src/main/java/sirius/web/data/ExcelExport.java

If a completely empty file is created, we must not attempt to
specify a range for the autofilters as these would result in a
"negative" range.

Only tries to create auto-filters if at least one row is present.

---

src/main/java/sirius/tagliatelle/compiler/Parser.java
src/main/java/sirius/tagliatelle/expression/Expression.java
src/main/java/sirius/tagliatelle/expression/MethodCall.java
src/main/java/sirius/tagliatelle/expression/TenaryOperation.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy
src/test/java/sirius/tagliatelle/TestObject.java

Especially for entities which have a reference like
`SQLEntityRef<OtherEntity> ref`;
Tagliatelle now knows that `entity.getRef().fetchValue()` is of type
`OtherEntity`.

Adds support for propagating generic types down a call chain.

---

src/main/java/sirius/tagliatelle/tags/BlockTag.java
src/main/java/sirius/tagliatelle/tags/ExtraBlockTag.java
src/main/java/sirius/tagliatelle/tags/RenderTag.java
src/test/java/sirius/tagliatelle/CompilerSpec.groovy

We have now support for `<i:extraBlock>` which directly puts an extra block into the GlobalRenderContext.
Also `<i:render />` is now detected as NOOP and an error is reported suggesting to use
`<i:render name=body" />` - which is most probably what the user wanted.

Adds a new tag handler and an error message for a common pitfall.

---

src/main/java/sirius/web/security/UserContext.java

When trying to invoke bindUserIfPresent(WebContext) while we're
already resolving the current user, we must abort to prevent an
endless recursion.
This happened in SellSite where we tried to obtain a database,
which in its constructor created a formatter, which in turn detected
the current language which then eventually invoked this method
when then again tried to resolve the current user, ending up trying
to obtain the same database again.
As databases are kept as ConcurrentHashMap, re-entering computeIfAbsent()
runs into an endless recursion.

Installs a circuit breaker.

---

src/main/java/sirius/tagliatelle/expression/MethodCall.java

Resolves the class from its direct parent type and not the generic declaration. For example: casting Tenant (E) in a MongoEntity<E>, and not the upper class BaseEntityRef<I, E>

Tagliatelle cast fix

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/WebContext.java
src/test/java/sirius/web/http/CompletionPromiseTestController.java
src/test/java/sirius/web/http/TestResponse.java
src/test/java/sirius/web/http/WebContextSpec.groovy

Sometimes we want to perform some tasks (i.e. statistics)
if a request was completely handled - this can be used by
attaching handlers on the newly created promise.

Permits to attach completion callbacks in WebContexts.

---

src/main/java/sirius/web/templates/ImageReplacedElementFactory.java

The code will be prepended with a 0 to ensure an even number of digits.

SE-9538 Allows rendering interleaved 2 of 5 barcodes in PDFs

---

pom.xml
src/main/java/sirius/web/controller/ControllerDispatcher.java
src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/dispatch/DefaultDispatcher.java
src/main/java/sirius/web/dispatch/HelpDispatcher.java
src/main/java/sirius/web/http/DispatcherPipeline.java
src/main/java/sirius/web/http/WebDispatcher.java
src/main/java/sirius/web/http/WebServerHandler.java
src/main/java/sirius/web/services/ServiceDispatcher.java
src/test/java/sirius/web/dispatch/TestDispatcher.java
src/test/java/sirius/web/http/TestRequest.java

This will simplify the internal handling of requests and also significantly reduce the length of the stack traces.

BREAKING CHANGE: Uses a loop instead of a recursive call

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

if you want to edit the text in the field but there is more than one word, you had no chance to select only one of them with the mouse. Now you can edit the text without problems
- fixes: SE-9586

do not select whole text if keepInputOnSelect is set

---

src/main/java/sirius/web/controller/BasicController.java

This is especially useful in .orElseThrow() statements of Optionals

Makes a unknownObjectException available to all controllers

---

pom.xml
src/main/java/sirius/web/data/XLSProcessor.java

- former call to XSSFWorkbook constructor with input stream loading the whole thing in memory to provide random cell access which required a large amount of heap space
- now we are streaming the input xlsx file at XLSProcessor where we iterate row-wise anyhow
- unfortunately xls cannot be streamed

Read in POI Workbook as stream within XLSProcessor

---

pom.xml

We do this to prevent regressions until we find a fix for the ByteBuf resource leaks occurring with the latest netty version.
Fixes: SIRI-252

Downgrades netty to version without resource leaks

---

src/main/java/sirius/tagliatelle/compiler/CompileException.java
src/main/java/sirius/tagliatelle/compiler/Compiler.java

SIRI 227: Make the error reporting for ACE more generic, so it can be re-used

---

src/main/java/sirius/web/http/Response.java

Client errors however (like a 404) may still be cached if the application
requests to do so.

Suppresses any caching of errors (HTTP 500+).

---

src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/resources/component-web.conf
src/main/resources/scope-conf/mail.conf

We need to accept ssl certificates based on host or domain names to initialize a TLS smtp connection. Added configuration key and corresponding logic that per default doesn't accept any certificates!

Added 'mail.smtp.ssl.trust' to mail session properties

---

src/main/java/sirius/web/security/HelperFactory.java
src/main/java/sirius/web/security/ScopeInfo.java
src/main/java/sirius/web/security/UserContext.java
src/test/java/sirius/tagliatelle/ExampleHelper.java
src/test/java/sirius/web/security/AnotherExampleHelper.java
src/test/java/sirius/web/security/ExampleHelper.java
src/test/java/sirius/web/security/FactoryExampleHelper.java
src/test/java/sirius/web/security/ScopeInfoSpec.groovy

Removes the ability to reference a helper by its name.
This is essentially a deprecated approach which was left over
from the JSF days. We actually never did reference helpers by
their name and we probably will never, as we'd instantly loose
all benefits of Tagliatelle and its static compilation capabilities.
Note that now that HelperFactories are quite trivial as these are
only glorified constructors, we also permit to instantiate a helper
via its constructor (which might take ScopeInfo as parameter).
Note that a factory can still be used and will always be preferred
as we might use this to overwrite / change helpers in customizations.
Also note, that while refactoring the new instance creation, we also
added support for circular references across helpers and also made
sure that each …

Simplifies creating helpers.

---

src/main/java/sirius/web/health/LoadInfoProvider.java

This is done as most LoadInfoProviders subclass CachingLoadInfoProvider so
without the annotation the LoadInfoProvider had to be placed in each
@Register annotation. This way one can get away with a simple @Register...

Makes the LoadInfoProvider AutoRegister.

---

src/main/java/sirius/pasta/noodle/ClassAliasProvider.java
src/main/java/sirius/pasta/noodle/SiriusClassAliasProvider.java
src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java

This is mainly used by sirius biz which automatically provides an alias for each helper
and entity. However, if an application already uses an alias, we ignore the entity
or helper.

Permits to supply optional class aliases.

---

src/main/resources/default/templates/tycho/page-footer.html.pasta
src/main/resources/default/templates/wondergem/page-footer.html.pasta

- Fixes verbatim `CallContext.getNodeName()` in footer

Fix: Verbatim Code in Default Template

---

src/main/java/sirius/pasta/noodle/Invocation.java

Just like Tagliatelle did earlier, we handle null.someMethod()
to simply return null instead of crashing with an NPE.

Makes Noodle null-safe again.

---

src/main/java/sirius/pasta/noodle/InterpreterCall.java
src/main/java/sirius/pasta/noodle/Invocation.java
src/main/java/sirius/pasta/noodle/MethodPointer.java
src/main/java/sirius/pasta/noodle/SharedConstantPool.java
src/main/java/sirius/pasta/noodle/compiler/Assembler.java
src/main/java/sirius/pasta/noodle/compiler/Parser.java
src/main/java/sirius/pasta/noodle/compiler/SourceCodeInfo.java
src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java

We kept all referenced MethodHandles in the shared constant pool. Now as MethodHandle doesn't support "equals", each compilation increased the pool size more and more.
Now that we store bytecodes as 32 bit ints, where the upper 16 bits index the OpCode and the lower 16 bit can represent an index into the constant table or the shared constant pool.
As we didn't validate these indices and also didn't impose any limits on the shared constant pool, the index bits which are "OR"'ed into the opcode bits, effectively changed the op code which was eventually executed. This lead invalid sequences of op codes and thus to crashes of Noodle (with more or less funny causes).
The fixes in this PR all try to fix and prevent errors of this class in the future. As the impact of this error is pretty high, …

Fixes an internal overflow of the SharedConstantPool.

---

src/main/java/sirius/web/security/UserInfo.java

This allows subclasses of `UserInfo` to only override `getUserName()` without modifying the field.

Fix: User Info

---

pom.xml

First and foremost we want to control which netty version is in use. Second we include the
nettly-all and async http client enumerates all netty jars by itself. Therefore both versions
end up in the classpath which might/will lead to runtime linking issues.

Excludes the netty dependency brought by async-http-client.

---

src/main/resources/default/assets/wondergem/autocomplete/multiselect.js

Previously it only did that when the token was not already present which missed a case for the singleselect input when the selected suggestion is changed in the underlying select input via code.
More descriptive the following way of events did not trigger a change on the select:
$select::change -> tokenfield.appendTokens -> tokenfield::onBeforeCreateToken (token already present)
This was a problem as the internal `currentInput` field wasnt reset this way which resulted in no event being triggered when the user selects the old value the next time.
Sample: singleselect value item1 -> code changes value to item2 -> user selects item1 again -> no event was triggered for change from item2 to item1
Fixes: OX-6499

Checks whether change event has to be triggered on token create

---

src/main/java/sirius/web/http/WebContext.java
src/main/resources/component-web.conf

- a change of cookie settings (e.g. samesite, domain, ...) might break the attachment of session pin cookie to session cookie and so invalidate all pinned sessions
- this can be prevented using a new pinning cookie name and fallback names
- see config key description for details

SIRI-306: Make session pinning work with cookie changes

---

src/main/java/sirius/web/health/CachingLoadInfoProvider.java
src/main/resources/component-web.conf

The annotation in subclasses will produce a startup warning "...is already autoregistered..."

remove a comment, because classes are already autoregistered +typos

---

src/main/resources/default/assets/common/common-polyfills.js
src/main/resources/default/templates/wondergem/scripts/polyfill.html.pasta

IE 11 actually doesnt support this. We chose the concise variant as according to MDN this is actually the way some browsers implement NodeList.forEach.
Fixes: SIRI-266

Adds polyfill for forEach function of NodeList

---

pom.xml

Netty has reported a security issue and thus needs to be updated:
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-21290
Fixes: SIRI-269

Updates to the latest netty.

---

src/main/java/sirius/web/templates/Generator.java
src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java
src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/QrCodePdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/ResourcePdfReplaceHandler.java

This allows for easy integration of custom logic (for example embedding blobs without the use of http).
Migration:
If internal resources (assets) are used via relative URLs these need to be prepended with resource://.
Barcodes and QR codes using the type attribute in the img tag are now instead generated by using the barcode:// and qr:// URI protocols.

Extracts the PDF image replace logic into separate handlers

---

src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy
src/test/java/sirius/pasta/tagliatelle/TestObject.java

The problem surfaces when we try to resolve the type of a method call. In the case of `Optional<String>.empty().orElse(null)` we already know the return type (T) will be String. But our logic throws this info away and replaces it with void when propagating the type of the null parameter value.

SIRI-321 Fix Optional<T>.orElse(null) resulting in return type void

---

src/main/java/sirius/web/data/ExcelExport.java
src/test/java/sirius/web/data/ExcelExportSpec.groovy

A new method allow us to select the Sheet to add rows, needed when we need to jump back and forth across sheets.
Note that this won't change the actual visible sheet once Excel opens. The first sheet remains as the visible one. A method could be added to change the current visible sheet if the need arrises.
Fixes: OX-6630

Allows to add rows into sheets already created

---

src/main/java/sirius/pasta/noodle/compiler/Assembler.java
src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java

The current construct is hard to understand. Also the bug fixed with #827 showed that this method could be called with type = Long and otherType = Object, which would fulfill the first if and then the Long would be falsely cast to Double.

Simplifies the coercing of numbers when evaluating binary operations

---

src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java

The code itself was and if safe in the way we call it. However, Java9+
throws an exception for concurrent modifications within computeIfAbsent
as it fears infinite recursions for the same key (which isn't the case
in our scenario).

Avoids a ConcurrentModificationException in Java9+.

---

src/main/java/sirius/web/security/Permissions.java
src/test/java/sirius/web/security/PermissionsSpec.groovy

This means, that 'enabled' and 'disabled' can be used as part of a permission expression.
For example: 'a+enabled,!disabled+b' works now as expected and is equivalent to 'a,b'

The enabled/disabled check is now applied after expression parsing

---

src/main/java/sirius/pasta/noodle/LambdaHandler.java
src/main/java/sirius/pasta/noodle/compiler/Parser.java
src/main/java/sirius/pasta/noodle/compiler/ir/LambdaNode.java
src/main/java/sirius/web/http/TunnelHandler.java
src/main/resources/default/templates/system/state.html.pasta
src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java

We now support zero-arg lambdas like `NoodleExample.invokeUnitOfWork(|| x = 42);`.
Also an error message and a color-code has been fixed as drive-by bug fixes.

Fixes zero-arg lambdas in Noodle and provides two minor improvements.

---

src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java

These methods are synthesized by the javac compiler to handle covariant
return types. Sadly this creates a method list which cannot be created
in a sane environment (e.g. two methods can have the same name and
arguments but different return types). These methods are only generated
to coerce calls to covariant superclass methods.
We're generally not interested in these methods, as these also wipe out
any generic infos.
Note that we cannot provide a test for this fix, as the method list of
a class is unordered (ordering is sheer luck). Therefore most of the
time the bridge methods are placed after the "real" methods and thus
this fix would not be needed. However in *some* circumstances, most
commonly in production, the order seems to be flipped.

Fixes a seemingly random type interference bug when bridge methods are generated out of order.

---

src/main/java/sirius/web/controller/Facet.java
src/main/java/sirius/web/controller/FacetItem.java
src/main/java/sirius/web/controller/FacetRange.java
src/main/java/sirius/web/controller/Page.java

- Dropped some overly complex or unused methods
- A FacetItem now properly checks if it is active instead of doing
so only once during its construction (which was more than often the
wrong point in time).

BREAKING: Cleanup of the Page/Facet/FacetItem framework.

---

pom.xml
src/main/java/sirius/pasta/noodle/macros/ExpandMessagesMacro.java
src/main/java/sirius/web/ErrorCodeException.java
src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/controller/Controller.java
src/main/java/sirius/web/controller/ErrorMessageTransformer.java
src/main/java/sirius/web/controller/Message.java
src/main/java/sirius/web/controller/MessageExpander.java
src/main/java/sirius/web/controller/MessageExpanders.java
src/main/java/sirius/web/controller/PreserveErrorMessageTransformer.java
src/main/java/sirius/web/dispatch/HelpDispatcher.java
src/main/java/sirius/web/health/ClusterMessageProvider.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/services/StructuredService.java
src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/taglib/t/helpbox.html.pasta
src/main/resources/default/taglib/t/textarea.html.pasta
src/main/resources/default/templates/tycho/page-disaster.html.pasta
src/main/resources/default/templates/tycho/page-messages.html.pasta
src/main/resources/default/templates/wondergem/page-disaster.html.pasta
src/main/resources/default/templates/wondergem/page-messages.html.pasta

We previously more or less expected messages to be in plain text and
to optionally contain a single link.
We now refactored to inner workings of the whole framework to
essentially support any HTML contents as message. We also provide a
builder to properly control and decide if HTML content is present or
if plain text is being output (which requires proper escaping).
This also opens up the possibility to further process some error
messages (e.g. those by Tagliatelle) to ensure proper rendering.

Refactors error handling and UserContext/Messages in general.

---

src/main/java/sirius/web/controller/Facet.java
src/main/java/sirius/web/controller/Page.java
src/test/java/sirius/pasta/tagliatelle/ReportBrokenTemplates.java

- Removes / simplifies some methods in Facet
- Only checks local templates and not ones brought in by dependencies.

Further improves the Facet API and ReportBrokenTemplates

---

src/main/java/sirius/web/controller/AutocompleteHelper.java

The legacy support of the enhanced autocomplete helper needs to include all fields that the old autocomplete helper wrote to the JSON response so already existing autocomplete fields in the UI are not broken.
Fixes: OX-7001

Ensures already existing autocompletes are still working

---

src/main/resources/default/assets/wondergem/stylesheets/forms.scss

We need to use position absolute here as it would push other form elements around when shown otherwise.
Fixes: SIRI-369

Renders token autocomplete suggestions floating above other content

---

src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
src/main/resources/default/assets/tycho/styles/buttons.scss
src/main/resources/default/taglib/t/datacard.html.pasta
src/main/resources/default/taglib/t/navbox.html.pasta
src/main/resources/default/taglib/t/navboxLink.html.pasta

We previously forced the list of extensions for a given point to be
empty, if one of the templates failed during compilation. We now
permit the developer to fix the template and we'll then recompile all
extensions properly.
Note that we still keep the empty list around in prod systems, as there
is no way of healing a broken template.

Permits to fix and reload broken extensions in dev systems.

---

src/main/java/sirius/web/controller/AutocompleteHelper.java

When not filled, the completion label falls back to the fieldLabel which is more accurate than using the value for cases where the completionLabel has not been set.

No longer assigns the autocomplete value to the completionLabel

---

src/main/java/sirius/web/security/UserContext.java

Returns the current user, only if they are logged in. 
Otherwise, calls without active login were resolved with an incorrect and inconsistent language (e.g. login page displayed in German -> submit invalid user data -> login page switched to English)
Fixes: SIRI-376

Only binds logged in user to the context

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java

The SCSS Caching breaks as soon as you use an `@include`, because the lastModified check does not check the included files.
In production environments, the scss files should not change usually, so it is enough to recompile them in dev environments.
(actually, scss files should not change in staging/prod environments at all, except on a redeploy, which is handled already)

Disable scss caching in dev environments

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/resources/Resource.java
src/main/resources/default/taglib/t/codeEditor.html.pasta

This was already present in the Wondergem template and then falsely considered as "not needed".

Permits to disable syntax checking within the ACE editor.

---

src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/taglib/t/page.html.pasta
src/main/resources/default/taglib/t/pageHeader.html.pasta

While this makes it so that we never have a fixed navbar on IE11 this makes it way easier to implement, as we don't have to add additional padding (possibly changing) to the page.
Also adds a new parameter to the pageHeader to better control the display of the additionalActions by forwarding classes

Replaces navbar fixed-top with sticky-top

---

src/main/java/sirius/web/controller/ControllerDispatcher.java
src/main/java/sirius/web/controller/Route.java
src/main/java/sirius/web/services/PublicService.java
src/main/resources/component-web.conf

Services can now signal, that they should not be called during system
maintenance (which commonly tries to keep the system in a read-only
mode).
This is done via PublicService.enforceMaintenanceMode().
If a service is called during maintenance, a proper error (503) along
with a retry header are sent.
Fixes: SIRI-413

Enforces the maintenance mode on public services (if requested).

---

pom.xml
src/main/resources/default/assets/tycho/styles/misc.scss
src/main/resources/default/assets/tycho/styles/typeface.scss
src/main/resources/default/taglib/t/backButton.html.pasta
src/main/resources/default/taglib/t/dropdown.html.pasta
src/main/resources/default/taglib/t/dropdownItem.html.pasta
src/main/resources/default/taglib/t/filterbox.html.pasta
src/main/resources/default/taglib/t/formBar.html.pasta
src/main/resources/default/taglib/t/heading.html.pasta
src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
src/main/resources/default/taglib/t/infobox.html.pasta
src/main/resources/default/taglib/t/menuDropdown.html.pasta
src/main/resources/default/taglib/t/menuItem.html.pasta
src/main/resources/default/taglib/t/navbox.html.pasta
src/main/resources/default/taglib/t/navboxLink.html.pasta
src/main/resources/default/taglib/t/pagination.html.pasta
src/main/resources/default/taglib/t/sidebar.html.pasta
src/main/resources/default/taglib/t/smartFormatTemporal.html.pasta
src/main/resources/default/templates/system/tag.html.pasta
src/main/resources/default/templates/system/tags-state.html.pasta
src/main/resources/default/templates/system/tags.html.pasta

Some tags used "label" and others used "title" for the same purpose.
We now switched all tags to "label" with the exception or real titles
like for "page" or "modal".
Also, we previously auto-added a "fa" prefix to all icon attributes.
This has now been removed (as some icons require "far" as prefix).
In short, to migrate these changes, change titleKey/title to
labelKey/label where ever the compiler complains and add a "fa " to
all icon attributes of all Tycho tag invocations.

Performs some consistency work on Tycho and minor cleanups.

---

src/main/resources/default/assets/tycho/styles/forms.scss

It looks a bit nicer if the blue focus glow on input fields is cut off on sides where are -append or -prepend is present

Limits the box shadow of input fields if they have siblings

---

src/main/resources/component-web.conf
src/main/resources/default/assets/tycho/scripts/history.js
src/main/resources/default/assets/wondergem/tycho-history.js
src/main/resources/default/assets/wondergem/wondergem.js.pasta
src/main/resources/default/taglib/t/page.html.pasta
src/main/resources/default/taglib/w/page.html.pasta

If you're not using tycho yet, you should disable tycho history in wondergem via config.
The goal of the own history handling:
- Skip over multiple entries of the same page
- Skip over entries that explicitly want to be skipped (e.g. historyUri = '' in t:page)
- Redirect to a different historyUri
As the browser history API is pretty restricted and popstate calling is pretty inconsistent we implement this by reading state on page load and redirecting / skipping over urls as instructed.
This leads to some restrictions:
- Forward Navigation will only work once
- When reloading a page which already has multiple entries, a forward button will be shown, which doesn't do anything
- Navigation using the back menu (more than one step back) might fail in some rare circumstances

Enhances history handling and make it cross-compatible with wondergem

---

src/main/resources/default/assets/tycho/scripts/history.js

Previously, links to the same side where behaving incorrectly as in triggering an unwanted back operation. This was the case because unlike posts to the same site, links to the same site will in most browser not append a new history entry, but instead replace the current state (with null). Therefore we store the length of the browser history together with our own array, so we know with which history entry the last url corresponds.
Fixes: SIRI-421

Makes tycho history work with links to the same site

---

src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css

Includes the changes of https://github.com/scireum/token-autocomplete/pull/36
Fixes: OX-7398

Updates token-autocomplete to hide text overflow

---

src/main/resources/default/taglib/t/filterbox.html.pasta
src/main/resources/default/taglib/t/navboxLink.html.pasta

adjust css-classes to not crash the layout on small lists with long titles

---

pom.xml

net.markenwerk has 1.5.5 as dependency, depending on the system one or the other will be used. 1.4.7 always falls back to TLSv1.0 if the mail.smtp.ssl.protocols property is not set, but not all servers still support 1.0. Version 1.5.5 will use TLSv1.2 or TLSv1.3 by default.

Replace javax.mail from 2013 with a version from 2015

---

src/main/resources/default/taglib/t/navboxLink.html.pasta

Allows the browser to break long navbar links if necessary

---

src/main/resources/default/assets/tycho/styles/page.scss

By giving all direct descendants of .d-flex and .d-inline-flex a min-width or min-height, they will be able to actually shrink, as else they often will have a width/height: auto, which also implies a flex-basis of auto - which prevents shrinking/limiting the width/height of the flex item.
Fixes: OX-7614
Before
After
Also happend in all layouts with a sidebar and searchheader
See https://developer.mozilla.org/en-US/docs/Web/CSS/flex-basis for some more info

Prevents flex items becoming bigger than the flex container

---

src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
src/main/java/sirius/web/util/BarcodeController.java

This is commonly used to create barcodes for GTINs with 14 digits used for certain types of packaging (see https://en.wikipedia.org/wiki/ITF-14).
`BarcodePdfReplaceHandler` and `BarcodeController` now both use `zxing` to generate barcodes (except for `interleaved2of5checksummed` in PDF templates, which remains unchanged).
**NOTE:** `BarcodePdfReplaceHandler` did generate barcodes for such GTINs, but they were unreliable when scanning.
Example:
The previous PDF replace produced a barcode for `<img src="barcode://ean/12345678987654"/>`, that cannot be reliably resolved back to "12345678987654":
With these changes, the produced barcode looks like this and can be scanned reliably:
Fixes: SIRI-487

Properly supports barcodes for GTIN-14 using the ITF format

---

src/main/java/sirius/pasta/noodle/compiler/Parser.java
src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy

The most common case is a missing ".class" like in a @part(MyClass)
(instead of @part(MyClass.class).
We now report a proper error for this case.

Improvs reporting for leftover raw class literals.

---

src/main/resources/default/assets/common/core.js.pasta

We have a scrollable table where each cell needs to trigger an event once it becomes visible. In order for this to work in scrollable containers, we need to enable capturing on the scroll event.

Adds support for scrollable containers to the visible event listener

---

src/main/resources/default/assets/tycho/styles/sirius-colors.scss

Before it was more some kind of purple:
Now it's actually light blue:
The color now matches the borders from sirius-search (e.g. https://github.com/scireum/sirius-search/blob/f6dbb2a83481f82dab6e9d110667d7ee1c64d5b7/src/main/resources/assets/es-head/src/app/ui/menuPanel/menuPanel.css#L2).

Fixes color code for sirius-blue-light

---

src/main/java/sirius/web/data/ExcelExport.java

As addRow accepts a Object..., it can easily be invoked with a List or
the like. This leads to sort of undefined / unexpected behavior. Thus
we renamed the methods to match the naming of CSVWriter.
Fixes: OX-8240

Uses amore consistent naming for addRow / addRowAsList.

---

src/main/java/sirius/web/services/JSONStructuredOutput.java
src/test/java/sirius/web/service/JSONStructuredOutputTest.java

- previous endResult required an open object
- now e.g. [{}] can be created

Makes JSONStructuredOutput create jsons without objects on root level

---

src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/assets/tycho/styles/typeface.scss
src/main/resources/default/taglib/t/datacard.html.pasta

The previous change was also intended to limit the card title, however,
it screwed up icons etc. by applying a min-width on almost any element
within a card.
We now provide a proper overflow to limit the title width.
(Previous ticket: SIRI-470)
Fixes: OX-8388

Removes a broadly applied style and replaces it with a more local limit.

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/WebServer.java
src/main/resources/component-web.conf

If a channel is not writeable, we actually block and await for it to
become writable. As we figured, this might slow down tunneling in
high load conditions, we added some loggings to check if there is a
correlations.

Records and outputs contention blocks.

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/TunnelHandler.java

...while avoiding changing the visibility of `headers()` from `protected` to `public`.
Fixes: OX-8364

Allows accessing the value of a specific response header

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

Adds a beforeOnUnload event listener for uploading files

---

src/main/java/sirius/web/http/InputStreamHandler.java

Consistently throws InterruptedIOException when input is closed

---

src/main/resources/default/taglib/t/iconInlineInfo.html.pasta

The iconInlineInfo component is most of the time used inside of cards to show various information about the entity the card is about.
Having long text (like a url or filename) without easy ways for CSS to determine where to wrap the text meant those could easily break out of the card body.
We now tell CSS it can break the value wherever necessary.
Fixes: OX-8531

Prevents long iconInlineInfo values from breaking out of cards

---

src/main/java/sirius/web/security/SAMLHelper.java

> https://scireum.myjetbrains.com/youtrack/issue/OX-8635
- Fixes namespace support (enabling third-party SAML Authentication Servers – provided they can be convinced to us a hashing algorithm other than SHA1)
- Fixes time check
- Prepares interface for unit testing
**A unit test will be added once anonymised data is available.**

SAML: Namespaces Fix (OX-8635)

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/TunnelHandler.java
src/main/java/sirius/web/http/WebContext.java
src/main/java/sirius/web/http/WebServer.java

This hopefully reduces the size of WebContext and Response a bit
(which are too large anyway). Also it gets rid of uses of Calendar
and Date while providing a generic helper for parsing HTTP dates
(RFC 1123)
Also:
We observed horrible behavior of downstream proxies if both, set-cookie
and Cache-Control/Expires headers (which instruct a proxy to cache the
response) are present. As per HTTP a response containing a set-cookie
header must never be publicly cached, however, some did.
We therefore built a detection to recognize and warn about hazardous
header combination. However, this check was too harsh and warned about
some "safe" scenarios.

Improves detection of hazardous header combinations.

---

src/main/resources/default/assets/common/core.js.pasta

**BREAKING CHANGE:** This is potentially breaking when existing calls to `postJSON` are made with `undefined` parameters that are expected to be passed on the server-side.
But current calls to `postJSON` in our projects don't seem to pass empty parameters.
This is quite useful when building complex request payloads as no extensive filtering has to occur outside of the postJSON call.
Fixes: OX-8650

BREAKING: Aligns behaviour of postJSON with the one of replaced jQuery AJAX

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/SendFile.java

This prevents an NPE in edge cases.

Only removes a chunked write handler if it has been properly installed before.

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

The use-cases of this could be described as edge cases but it is quite necessary for how the OXOMI frontend used the history to store its state and navigation.
This new method can be used to override the path that is included in the generated history state URL externally. For example when sub-navigation occurs that should be reflected in the path.
Fixes: OX-8795

Continuity: Allows to override the path that is used to generate deep-links

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

The new startup parameter allows to disable the automatic alteration of the current URL via the state parameter to generate deep-links. This is mainly useful for pages where deep-links are already generated by other means.
Fixes: OX-8795

Continuity: Allows to automatic disable the generation of deep-links entirely

---

src/main/resources/default/assets/common/scripts/overlay.js.pasta

We trigger the `sci-overlay-destroyed` in the following scenarios:
- Overlay closed via x button
- Overlay closed via background click
- Overlay closed via ESC key
- Overlay closed as new one was opened
The last one of these is the only one that is not triggered by the user actively trying to close the overlay but can also occur when the currently open overlay triggers a new overlay that replaces the old one.
To differentiate these we now trigger a new event `sci-overlay-dismissed` in those 3 cases where the user tries to close the overlay.
Fixes: OX-8917

Overlay: Allows to detect an overlay actively being closed by the user

---

src/main/resources/default/assets/common/core.js.pasta

This could cause unwanted behaviour when switching from jQuery to the sirius functionality.
Fixes: OX-8997

Sirius JS: Won't send null value parameters via postJSON to server

---

src/main/java/sirius/pasta/tagliatelle/Template.java
src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
src/main/java/sirius/pasta/tagliatelle/emitter/CompositeEmitter.java
src/main/java/sirius/pasta/tagliatelle/emitter/ConstantEmitter.java
src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy

> https://scireum.myjetbrains.com/youtrack/issue/SIRI-618
- Trims HTML and XML templates after parsing, in order to enable punctuation without whitespace after custom tags
- **JavaDoc will be done** once we agree on the entire thing 😅

Trimming of Parsed HTML Templates (SIRI-618)

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

We now allow to choose between the two modes:
- plain text (including escaped curly braces, ...) which is the default mode
- base64 encoded (a bit longer but normal characters and non readable)
Sample of plain text mode:
```
https://oxomi.test.scireum.com/p/3000470/products?oxHistory=%7B%22navPro%22%3A%7B%22view%22%3A%22filtered%22%2C%22filters%22%3A%7B%22brand%22%3A%5B%227QG3KIAUULBC476FCR7RE322L4%22%5D%2C%22metaclass%22%3A%5B%22metaclass%7CEC011550%22%5D%7D%2C%22query%22%3A%22%22%2C%22hiddenFilters%22%3A%7B%7D%7D%2C%22overlay%22%3A%7B%22type%22%3A%22openProductDatasheet%22%2C%22args%22%3A%7B%22productId%22%3A%22T7UAJHAIVIVIVG38IHVVHQTR7G%22%2C%22supplierItemNumber%22%3A%2203005000001%22%2C%22supplierNumber%22%3A%22DUHO80%22%2C%22supplierNumbers%22%3A%22DUHO80%2CDU%22%7D%7D%7D
```
Sample …

Continuity: Allows to base64 encode the history state param

---

src/main/java/sirius/web/http/WebServer.java

Exposes the current heap and direct memory used by the pooled byte buffer allocation, converted in MB.
Note that we are not defining threshold limits in the config (they are initialized with zero), and system can set those if needed as they strongly depend on the actual amount of memory allocated to both heap and direct memory.
Fixes: [OX-9027](https://scireum.myjetbrains.com/youtrack/issue/OX-9027)

Exposes pooled byte buffer mem usage

---

src/main/java/sirius/web/data/ExcelExport.java

Sadly the SQL Array class does not provide proper toString implementations which means its object identifier is exported instead. This improvement will most likely apply when directly exporting ClickHouse events.
Fixes: SIRI-636

Transforms sql string arrays when exporting to excel

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Previously this crashed hard. We now recover from the failure by ignoring the invalid parameter value. We additionally call a error handler callback function when defined so custom error handling logic can be executed.
Example for Error Handler:
```js
initialStateParseErrorHandler: function () {
oxomi.withConfig(function () {
oxomi.showMessageInDialog(
oxomi.translate('history.deeplinkParsingFailed.title'),
oxomi.translate('history.deeplinkParsingFailed.message')
);
});
}
```
Fixes: OX-9093

Continuity: Properly handles parsing failures of the initial state url parameter

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/WebServer.java

Both look almost the same except that 822 always uses UTC as zone where 1123 might output an offset like +0200.
This issue has been reported by the AWS driver for S3Ninja and the largest data center provider in the world is always right :)

We now use RFC 822 date formats instead of RFC 1123 ones.

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Needed to specify the error in the catch block.

Makes continuity.js.pasta IE11 compatible

---

src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/TunnelHandler.java

Previously millis and seconds got confused which resulted in wrong header timestamps.
Before:
> last-modified: Tue, 20 Jan 1970 07:30:31 +0100
After:
> last-modified: Thu, 06 Oct 2022 06:47:39 GMT
Fixes: [SIRI-592](https://scireum.myjetbrains.com/youtrack/issue/SIRI-592)

Correctly tunnels through last modified header

---

src/main/resources/default/assets/tycho/styles/sirius-colors.scss

These match the naming scheme of the scireum CSS design system. They are added as alternative class names to make this change non-breaking.
Fixes: OX-9142

Adds aliases for sirius color classes

---

src/main/resources/default/assets/tycho/styles/sirius-colors.scss

This allows to overwrite the border colors of other classes (for example sci-btn-outline) by applying one of the border color classes of this file. This also matches the behaviour of the text and background color classes.
Fixes: OX-9142

Marks colors set by border color classes as important

---

pom.xml

initial, poi-shared-strings was added extra to fix security-issues shipped with excel-streaming-reader in an older version. Now with https://github.com/pjfanning/excel-streaming-reader/compare/v4.0.2...v4.0.3 poi-shared-strings was updated to the newest version and in the old version 2.5.4 there is CVE-2022-42889. Fixed now with https://github.com/pjfanning/poi-shared-strings/pull/53/files - details see https://commons.apache.org/proper/commons-text/security.html

update dependencies, remove extra-import for poi-shared-strings

---

src/main/java/sirius/web/http/WebContext.java

Calling toString in a released buffer (refCnt = 0) throws an IllegalReferenceCountException, which will write an unnecessary exception in the system logs. If the buffer has been released, very likely the connection was already destroyed.
Fixes: [OX-9250](https://scireum.myjetbrains.com/youtrack/issue/OX-9250)

Ignores IllegalReferenceCountException transforming HTTP data

---

src/main/resources/default/templates/system/console.html.pasta

with removing the 100vh in https://github.com/scireum/sirius-web/pull/1118/files this does not work anymore, so we add it here in custom styles only for the console-page.
-->

make console work again scrollable and also for small widths

---

src/main/resources/default/assets/tycho/styles/border.scss
src/main/resources/default/taglib/t/helpbox.html.pasta

If an element using `left-border border-sirius-someColor` is assigned other borders, their color would be changed as well. This happens since the border-sirius colors were marked as `!important` in #1121.

Provides more specific styles for colored left borders

---

src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/controller/ControllerDispatcher.java

This reverts commit 5ffd5b9e53238c76421b7c3531ad55f641ff198a.
The reverted commit caused some problems, and we don't want to take it in so close before a new major version.
This commit was initially part of #1126 and the change will be re-introduced with #1129

Revert "Changes the response codes used when reporting exceptions"

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java

Previously directly calling /assets/dynamic - either by accident or when generating an invalid ID - rendered an excessive error page and also logged an ERROR to the system log.
We now just don't handle such a call via the asset dispatcher and let the controller dispatcher tell the user that no controller will handle the URL.
Before:
After:
Fixes: [SIRI-669](https://scireum.myjetbrains.com/youtrack/issue/SIRI-669)

Properly "handles" calling /assets/dynamic

---

src/main/java/sirius/web/controller/ControllerDispatcher.java

> [OX-9400](https://scireum.myjetbrains.com/youtrack/issue/OX-9400), [MIO-5896](https://scireum.myjetbrains.com/youtrack/issue/MIO-5896)

Revises Handling of `ClosedChannelException` (OX-9400/MIO-5896)

---

pom.xml
src/main/java/sirius/web/controller/ControllerDispatcher.java
src/main/java/sirius/web/controller/Route.java
src/main/java/sirius/web/services/PublicServices.java

Service documentations could register multiple times during the initial collection of routes. This is an attempt to ensure that this collection and the accompanying Controller parsing is performed in a safe manner.
Fixes: [SIRI-680](https://scireum.myjetbrains.com/youtrack/issue/SIRI-680)

PublicServices: Prevents recording service documentations multiple times

---

src/main/java/sirius/pasta/noodle/macros/FormatDateTimeWithoutSecondsMacro.java
src/main/java/sirius/web/dispatch/HelpDispatcher.java
src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/security/GenericUserManager.java
src/main/java/sirius/web/security/PublicUserManager.java
src/main/java/sirius/web/security/ScopeInfo.java
src/main/java/sirius/web/security/UserContext.java
src/main/java/sirius/web/security/UserInfo.java
src/main/java/sirius/web/templates/DefaultGlobalContextExtender.java

BREAKING CHANGE:
- Subclasses of `UserInfo` that access the internal `lang` (without using the getter function) have to be changed to access the `language` field, as it was renamed.
- Subclasses of `ScopeInfo` that access the internal `lang` (without using the getter function) have to be changed to access the `language` field, as it was renamed.
- Subclasses of `GenericUserManager` that overwrite the internal `computeLang` have to be changed to overwrite the `computeLanguage` method instead, as it was renamed.

BREAKING: Uses new variants of renamed lang methods

---

src/main/java/sirius/web/services/ServiceCall.java

This is a cherry-pick of #1146

ServiceCall: Properly handles `ClosedChannelExceptions`

---

src/main/resources/component-web.conf

Although this setting will most probably be overwritten in all products, this is at least a good source of inspiration...

Properly links to the /licenses page in the footer.

---

src/main/resources/default/taglib/t/fileUpload.html.pasta

Before:
After:
Fixes: [9321](https://scireum.myjetbrains.com/youtrack/issue/OX-9321/Video-Modernisierung-Backend-User-Interface-Teil-3-Weitere-Seiten)

Adds margin bottom to the dropzone bar/indicator in order to improve the look and feel of the bar

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Otherwise continuity affects the URL by appending a useless '?'.
Old behavior:
- visiting `/system/dashboard`
- URL automatically changes to `/system/dashboard?`
New behavior:
- visiting `/system/dashboard`
- URL stays `/system/dashboard`
Fixes: [SIRI-638](https://scireum.myjetbrains.com/youtrack/issue/SIRI-638)

Continuity: Only appends history params when any are present

---

src/main/java/sirius/pasta/noodle/sandbox/Sandbox.java
src/test/java/sirius/pasta/noodle/sandbox/SandboxExample.java
src/test/java/sirius/pasta/noodle/sandbox/SandboxExample2.java
src/test/java/sirius/pasta/noodle/sandbox/SandboxSpec.groovy

The approach however is simplified and doesn't support methods of interfaces that override the method of an extended interface (which isn't common case anyway). An example would be if Macro would override Named#getName.

Allows whitelisting interface methods

---

src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
src/test/java/sirius/pasta/noodle/sandbox/SandboxSpec.groovy

This allows the inlineResource macro in sandboxes, but only if static resources are referenced. It should never be required for user-created templates to inline tagliatelle resources.

Whitelists the inlineResource macro

---

src/main/java/sirius/web/http/Response.java

Calling `createFullResponse()` passes along all present headers. Unfortunately, the cache headers were not properly initialized before, so values provided via `cachedForSeconds()` were not copied to the new response.
Fixes: [OX-9491](https://scireum.myjetbrains.com/youtrack/issue/OX-9491)

Response: pass provided cache headers to redirect response

---

src/main/java/sirius/web/http/Response.java

The `content-length` is currently automatically set. This is usually fine, but at times, we want to decide ourselves. For instance, when responding to a `HEAD` request, the body will be empty, but the `content-length` should be set to a non-zero value.
This PR no longer overwrites manually set `content-length` headers.

Fix: Content-Length

---

src/main/resources/default/taglib/w/textarea.html.pasta

This is useful when we don't want to allow resizing the text area. Also, it makes the tag much more flexible and be in line with other tags that allow classes or even styles.
Note, that while we can declare the parameters on multiple lines, we mustn't add spaces to the value of the tag as the spaces or line breaks will propagate the to the displayed value otherwise!

SIRI-727: Adds class and style properties to w:textarea

---

src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/taglib/t/page.html.pasta
src/main/resources/default/taglib/t/pageHeader.html.pasta
src/main/resources/default/templates/system/console.html.pasta

(details see commits)
before change (on windows):
after change (on windows):

make tycho more responsive on small windows and fix ugly windows view

---

src/main/resources/default/assets/tycho/styles/forms.scss

Removes the box-shadow of an upload-file when it's positioned in a card.

removes the box shadow of upload file when in card

---

src/main/resources/default/taglib/t/editForm.html.pasta

An ID on a form can be useful for registering inputs outside the form.

Adds ID property to tycho editForm

---

src/main/resources/default/assets/tycho/scripts/history.js.pasta

Bug scenario:
1. Opening `/system/jobs` in a new tab
2. Selecting a job from the list that has required parameters
3. Trying to start the job without any parameters
4. Reloading the page
5. ⚡ Chrome would jump back to the jobs list instead of staying on the job page
Previously working behaviour in FireFox:
Previously broken behaviour in Chrome:
Fixes: [SIRI-716](https://scireum.myjetbrains.com/youtrack/issue/SIRI-716)

Tycho: Prevents duplicate back navigation on page reload

---

src/main/resources/default/assets/common/styles/overlay.scss

Before:
After:
Fixes: [OX-9715](https://scireum.myjetbrains.com/youtrack/issue/OX-9715)

Prevents overlay content from being able to overlap the close button

---

src/main/resources/default/taglib/t/sidebar.html.pasta

on pages with content the missing mb-4 on small screens crashes the layout
before vs now
- fixes: SIRI-761

Adjusts Styling of Tycho Sidebar

---

src/main/resources/default/taglib/t/searchHeader.html.pasta

before vs after change
- fixes: SIRI-769

enhance css to not break layout on long buttons with more than one word

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Allows to remove a entry from the current history state by calling `continuity.replaceStateEntry('entryType', null)` or `continuity.pushStateEntry('entryType', null)`
Allows to unregister a state entry handler previously registered via `continuity.registerStateEntryHandler('entryType', ...)` by calling `continuity.unregisterStateEntryHandler('entryType')`
Allows to use so called sub-scopes for entryTypes by using `continuity.registerStateEntryHandler('entryType|subScope', ...)` and `continuity.pushStateEntry('entryType|subScope', ...)` which allows to have unique state entries and handlers that share the same `entryType` configuration.
Example for where this may be useful:
Single page with multiple similar elements (e.g. multiple paginator-lists) could be registered as an entry type …

Continuity: Sub-Scopes & Removal of Handlers and Entries

---

pom.xml
src/main/java/sirius/web/services/JSONStructuredOutput.java

Extracts handler-method to abstract superclass in sirius-kernel
- https://github.com/scireum/sirius-kernel/pull/448
Note: `ClosedChannelException` extends `IOException`, so we don't need separate catch clauses here.
Fixes: [SIRI-766](https://scireum.myjetbrains.com/youtrack/issue/SIRI-766)

JSONStructuredOutput: unifies handling of ClosedChannelExceptions

---

src/main/java/sirius/web/services/DefaultErrorResponsesJson.java

Fixes: [OX-9704](https://scireum.myjetbrains.com/youtrack/issue/OX-9704/Fehler-in-KBA-INT63-Berechnung-bei-API-Token-ist-falsch)

Beautifies the response documentation by adding whitespaces for the DefaultErrorResponsesJson

---

src/main/resources/assets/design-system/design-system.scss
src/main/resources/assets/design-system/form.scss
src/main/resources/assets/design-system/misc.scss

Sample usage:
This uses:
- New input style
- Overwrites for hiding right border
- Overwrites for resetting border radius to 0
Fixes: [OX-9740](https://scireum.myjetbrains.com/youtrack/issue/OX-9740)

Expands CSS Design System slightly

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

This allows for some more complex scenarios where a single history entry also has multiple history sub-entries and popping the entry should undo all of the sub states at once.
Depth counting is currently done manually where necessary.
The depth is always omitted from the deeplink URL as opening a deeplink won't include all previous history states (that were open when creating the deeplink), so jumping back multiple states at once would lead somewhere completely wrong.
Example:
Search that writes a new state each time a filter is changed, rendered within an overlay. Popping (closing) the overlay should not simply undo a single search state change but undo them all at once so the overlay is actually closed.
Fixes: [OX-9814](https://scireum.myjetbrains.com/youtrack/issue/OX-9814)

Continuity: Allows to jump back multiple history states when entry contains depth counter

---

src/main/resources/default/taglib/t/dropdownItem.html.pasta

This is useful when wanting to force the opening of a new tab on clicking the link via target "_blank".

Allows to specify an alternate target for the dropdown item link

---

src/main/resources/default/assets/tycho/scripts/charts.js.pasta

> https://scireum.myjetbrains.com/youtrack/issue/SIRI-803
Internal and external users report issues concerning the tooltip in data explorer graphs. In order to clarify, the tooltip now shows values for all graphs for the current month (current value and value from the chosen reference point).
https://github.com/scireum/sirius-web/assets/36069303/f2dd9da1-5eab-4790-b55a-f18a090bf7d3
https://github.com/scireum/sirius-web/assets/36069303/d2453760-8ec0-4880-afae-d956dcaac802

Data Explorer: Tooltips (SIRI-803)

---

src/main/resources/assets/design-system/misc.scss

This matches the pill used for filter counts displayed in the Navigator Pro of OXOMI.
Fixes: [OX-9981](https://scireum.myjetbrains.com/youtrack/issue/OX-9981)

Design System: Adds a small pill component class

---

src/main/resources/default/taglib/t/sidebar.html.pasta

Automatically grows the contents next to the sidebar to 100% height.

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta

This is our own component so we wont break anything when we enable our font classes here. This prevents having to mark each content rendered in the dialog with "sci-enable-font" which is highly likely to be forgotten at some point.
Fixes: [OX-9378](https://scireum.myjetbrains.com/youtrack/issue/OX-9378)

Dialogs: Always enables our own font stack when rendering a dialog

---

src/main/resources/assets/design-system/misc.scss
src/main/resources/default/assets/common/scripts/dialog.js.pasta

This has to be used rather than absolute positioning as it be offset by a scrolling parent container.
**Before:**
**After:**
Fixes: [OX-9378](https://scireum.myjetbrains.com/youtrack/issue/OX-9378)

Dialog: Uses fixed positioning for the background

---

src/main/resources/default/taglib/t/emptyCheck.html.pasta

In case of an "empty" block the card used to show excessive top margin. This PR moves the top-margin setting to the default heading.
See space above video.
| Without | With |
|-|-|
| ![Screenshot 2023-06-28 at 20 59 00](https://github.com/scireum/sirius-web/assets/36069303/dcaf9f60-d4ef-4ccf-a21e-122f7bb1b0d1) | ![Screenshot 2023-06-28 at 20 58 00](https://github.com/scireum/sirius-web/assets/36069303/902b9a78-7c4b-4063-8bb5-5801b1fa4699) |

Empty Check: Top Margin

---

src/main/resources/default/taglib/t/booleanSelect.html.pasta

Fixes: [OX-8902](https://scireum.myjetbrains.com/youtrack/issue/OX-8902)
BREAKING:
The default auto-generated ID selector for booleanSelect-fields changes from e.g. `singleselect-1` to `booleanselect-1`. Either adjusts existing JS code relying on the old selector to use the new one, or assign the old selector manually as ID in the template code.

Tycho boolean select now properly supports ID parameter

---

src/main/java/sirius/web/sass/Generator.java
src/test/java/sirius/web/sass/SassTest.java
src/test/resources/sass/functions.css
src/test/resources/sass/functions.scss

This is required, as some functions are defined in both CSS and SCSS but with different parameters (and semantics).
One example is "opacity" which can also be a CSS value for "filter".

Passes unparsed / malformed function calls through

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/common/scripts/continuity.js.pasta

Optimized the 'handleStateChange' function to ensure that the state handler is only called when there is a real change in the state. For this a deep comparison function 'deepEqual' was also added to make sure the changes in the nested properties of objects are correctly detected. This should improve the "optical stability" of the page as state handlers aren't executing code that recreate the currently visible state (e.g. by executing the same search again).
Fixes: [OX-10141](https://scireum.myjetbrains.com/youtrack/issue/OX-10141)

Continuity: Only calls state handler restore when entry is actually changed

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Fixes: [OX-10185](https://scireum.myjetbrains.com/youtrack/issue/OX-10185)

Allows to skip the change check and always call the handler

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Chrome has some weird behaviour where it sometimes completes running all code of the current execution context (everything that wasn't postponed by setTimeout or async calls). This introduced a bug in the continuity history handling where a popStateEntry could actually be reverted automatically as the handleStateChange code ran after back navigation was intended and the back navigation and state change restore would cancel each other. We now use a simple flag to ensure the handleStateChange logic does not get executed when we previously issued a back navigation in popStateEntry.
This is heavily inspired by commit 7c0894290e30e050f276576a5209d7ae52165ce7 which did the same in the tycho history logic.
Fixes: [OX-10192](https://scireum.myjetbrains.com/youtrack/issue/OX-10192)

Continuity: Prevents history change handling when back navigation is already queued

---

src/main/resources/default/assets/common/core.js.pasta

Changed the fallback mechanism for silent form submission.
Originally, the functionality directly called `HTMLFormElement.submit` in cases when the `HTMLFormElement.requestSubmit` was not supported by the browser.
However, this bypassed triggering the 'onsubmit' event and constraint validation, and there was no way to prevent the page from reloading.
Now, a hidden submit button is created dynamically to handle the submission instead, ensuring 'onsubmit' event, validation, and prevention of page reload. This change enhances compatibility with older browsers like IE 11.
Fixes: [OX-10197](https://scireum.myjetbrains.com/youtrack/issue/OX-10197)

IE 11: Correctly applies fallback logic for silent form submit

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta

For some reason IE 11 would render the close button icon with an excessive height when no specific height is given. Because of this we now specify a height (the icon is square anyway).
**Before:**
**After:**

IE 11: Fixes excessively large dialog header height

---

src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta

Taglib parameters only support either string literals (`class="foo bar"`) or noodle expressions (`class="@Class"`), but not both together. We need to use `@apply` to concatenate everything together.

Fixes t:dropdownDeleteItem

---

src/main/resources/default/templates/system/api.html.pasta
src/main/resources/default/templates/system/service-format-tag.html.pasta

Provides a better overview of the service capabilities in the table of contents. Also eliminates name conflicts if documentation exists for the same service with different content types (e.g. json vs xml as in the 2nd screenshot).
Before:
After:

API Docs: shows method and content type in toc instead of generic icon

---

src/main/resources/default/assets/common/core.js.pasta

This is useful for allowing to insert new lines via Shift + Enter in text areas.

Sirius JS: Allows to suppress enter listener when shift is pressed

---

src/main/resources/default/templates/system/api.html.pasta

Allows the use of HTML in descriptions of more API-related fields. (Parameters already supported HTML descriptions before.)

API Documentation: More HTML

---

src/main/java/sirius/web/security/GenericUserManager.java

decrease default sso-time to 4 hours

---

src/main/resources/default/assets/tycho/styles/forms.scss

The default style specified above has a rather unspecific selector and therefore was overwritten by the rule that set the default gray border color of the field.
Fixes: [SIRI-876](https://scireum.myjetbrains.com/youtrack/issue/SIRI-876)

Tycho: Correctly shows error state on token autocomplete fields

---

src/main/resources/default/assets/tycho/scripts/form.js.pasta

In cases where the submit button does not reside inside a form and thus the page is probably not going to be reloaded automatically, it is more likely that multiple submissions are okay and that t:formBar was simply invoked without a 'singleClick' parameter.
This is an alternative solution to https://github.com/scireum/sirius-biz/pull/1845
Fixes: SE-13063

SE-13063: Only prevent multiple clicks if it would lead to a form submission

---

src/main/resources/default/assets/tycho/scripts/history.js.pasta

This is useful when a page has internal states that don't correlate with page loads.

Allows to inject new history states via tycho history

---

src/main/resources/default/assets/common/core.js.pasta

Handles the reload of an image. This could come in handy if the image source is not available immediately (since its processing takes some time).
<ul>
<li>Tries to reload the image up to three times</li>
<li>There is a one-second delay between each try</li>
<li>Shows a placeholder with a three-dotted-animation while waiting</li>
</ul>
Fixes: [OX-10093](https://scireum.myjetbrains.com/youtrack/issue/OX-10093)

Adds a function which handles the reload of an image while showing a three-dotted-animation

---

src/main/resources/assets/design-system/button.scss

This allows us to also apply our button classes to button elements. Previously this looked hideous as the default styles of the button elements introduced a border that we did not override. So the classes were only suitable for anchor, div or span elements.
**Before:**
**After:**
**Disabled Style:**
Fixes: [OX-10460](https://scireum.myjetbrains.com/youtrack/issue/OX-10460)

Design System: Correct Border Rules & Dsiabled Style for Buttons

---

src/main/resources/default/assets/common/core.js.pasta

sirius.isEmpty returned always ture if a dom element was provided. This clearly was a bug and not intended
Fixes: SIRI-886

Fixes sirius.isEmpty not working for dom elements

---

src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

This lead to problems when customers created folders with single ticks (') in their names. Which is quite common in some languages.
Fixes: [SIRI-807](https://scireum.myjetbrains.com/youtrack/issue/SIRI-807)

Tycho: Escapes single ticks in the dropzone upload URLs

---

src/main/resources/default/assets/common/core.js.pasta

The previous implementation checked for a function that is only present on JQuery DOM objects.
Fixes: [SIRI-880](https://scireum.myjetbrains.com/youtrack/issue/SIRI-880)

Sirius JS: Actually make helper work with plain DOM elements

---

src/main/java/sirius/pasta/noodle/compiler/VariableScoper.java
src/main/java/sirius/pasta/tagliatelle/tags/ArgTag.java
src/main/resources/default/taglib/t/datefield.html.pasta
src/main/resources/default/taglib/t/textfield.html.pasta
src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy
src/test/resources/templates/duplicateArgument.html.pasta

Defining two arguments with the same name are pretty pointless (rather a mistake) and therefore emit a warning
Fixes: SIRI-879

Prevents duplicate arguments

---

src/main/java/sirius/web/services/JSONCall.java

Adds a supplier to enable or disable the json-call fine-logging for specific scenarios on the fly.
Fixes: SIRI-849

Adds a supplier to enable or disable the json-call fine-logging

---

src/main/java/sirius/web/dispatch/HelpDispatcher.java

- `/help` -> OK
- `/help/` -> OK
- `/help/...` -> OK
- `/help2`-> FAIL
```stacktrace
sirius.kernel.health.HandledException: An unexpected exception occurred: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null (java.lang.NullPointerException)
at sirius.kernel.health.Exceptions$ErrorHandler.handle(Exceptions.java:246)
at sirius.kernel.health.Exceptions.handle(Exceptions.java:411)
at sirius.web.http.DispatcherPipeline.handleInternalServerError(DispatcherPipeline.java:106)
at sirius.web.http.DispatcherPipeline.dispatch(DispatcherPipeline.java:97)
at sirius.web.http.DispatcherPipeline.lambda$dispatch$1(DispatcherPipeline.java:65)
at sirius.kernel.async.ExecutionBuilder$TaskWrapper.run(ExecutionBuilder.java:122)
at …
```

Fixes a possible NPE navigating to /help

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/http/Response.java

If the asset has been modified before the [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) requested date, we return a 304 NOT_MODIFIED return code with am empty body.
This logic was implemented for tagliatelle templates, but not for static assets or compiled CSS files, although a bug has been fixed here and the portion of code never really worked. See 1st. commit for details.
Fixes: [SIRI-729](https://scireum.myjetbrains.com/youtrack/issue/SIRI-729)

Supports If-Modified-Since HTTP header delivering assets

---

src/main/resources/default/assets/common/core.js.pasta

This is not a definitive way (as there are many more ways to manipulate a node to not show up, like size, opacity, ...) but its a useful way to determine whether a node is shown or hidden via our most used measures:
- manual display none
- sci-d-none
Fixes: [OX-10422](https://scireum.myjetbrains.com/youtrack/issue/OX-10422)

JS: Adds helper for checking if a DOM node is probably visible

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/http/SendFile.java
src/main/java/sirius/web/http/TunnelHandler.java
src/main/resources/component-065-web.conf
src/test/java/sirius/web/dispatch/AssetsDispatcherSpec.groovy

Key: `http.response.defaultClientCacheTTL`
This is basically what lands in Cache-Control's max-age HTTP header.
**BREAKING**: The `Response.HTTP_CACHE` is gone. Use `Response.obtainClientDurationInSeconds()` instead.
Configurable with the key: `http.response.defaultStaticAssetTTL`
This header can be used by reverse proxies, e.g [Varnish](varnish-cache.org), to set a different TTL (time-to-leave) value than the one provided with the standard HTTP headers, such as `Cache-Control`.
Configurable with the key: `http.response.defaultCustomProxyTTL`
Fixes: [SIRI-728](https://scireum.myjetbrains.com/youtrack/issue/SIRI-728)

Revamps asset caching

---

src/main/resources/assets/design-system/icons.scss

Adds the following css icon classes:
Fixes: OX-10532

Adds multiple sci-icons 

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/http/Response.java
src/main/resources/component-065-web.conf
src/test/java/sirius/web/dispatch/AssetsDispatcherSpec.groovy

as proxy configuration is getting overly complex and demands "hacks" in order to alter the Date and Expires headers since we would deliver a file already expired as we cache longer than its age.
In fact, we see no need for a reverse-proxy to cache an asset longer than what we already set in its "Expire" and "Cache-Control" headers.
Fixes: [SIRI-728](https://scireum.myjetbrains.com/youtrack/issue/SIRI-728)

Removes the X-Custom-TTL header

---

src/main/java/sirius/web/security/UserInfo.java

Adds a method that permits to create synthetic administrator users. The functionality has been taken from [`Tenants.java`](https://github.com/scireum/sirius-biz/blob/fee262b935e9bb28539ea3eff81e23a50d7af425/src/main/java/sirius/biz/tenants/Tenants.java#L564) and adapted for re-use.

Helper for Synthetic Administrators

---

src/main/resources/default/taglib/t/singleSelect.html.pasta

If the selection options of a SingleSelect are dependent on the selection of another SingleSelect, this can now be specified via a dependencyField and the dependent fields can be determined via autocomplete.
Whenever we select a classification system, only the classes that belong to it will be specified as an option.

Adds the possibility to create dependencies between two SingleSelects

---

src/main/java/sirius/web/http/Response.java

Nowadays, it's unsafe to reveal which server is being used behind a web-site, such as Apache, nginx etc. (in our case we claim to use Netty) as attackers might profit from known security flaws in a specific product.
Therefore, we no longer advertise what we use in background. For debugging purposes, we do keep the host name delivering the content.

Do not reveal product in http.server header

---

src/main/java/sirius/web/dispatch/AssetsDispatcher.java
src/main/java/sirius/web/dispatch/HelpDispatcher.java

They most probably contain user specific info (like the user and tenant when switching to a user or tenant) and should therefore not be cached at all.
Fixes: [SIRI-912](https://scireum.myjetbrains.com/youtrack/issue/SIRI-912)

Do not cache help pages, caches help assets longer

---

src/main/resources/default/taglib/t/fileUpload.html.pasta
src/main/resources/default/taglib/t/imageUpload.html.pasta

The default type of a button is "submit", leading the upload button to submit an entire form when wrapped in one. This rendered the button unusable in such cases.

Bugfix: Image Upload Button Must Not Submit Forms

---

pom.xml
src/main/java/sirius/web/services/JSONStructuredOutput.java
src/test/java/sirius/web/service/JSONStructuredOutputTest.java

Let Jackson serialize it's own object types as a Json lib should be quite capable of doing so. This gives us the capability of building complex structures with Jackson objects using their 'pojo mechanism'
Depends on: https://github.com/scireum/sirius-kernel/pull/508

Let Jackson serialize it's own object types

---

.run/mvn clean test - without nightly.run.xml
pom.xml

update some dependencies

---

src/main/java/sirius/web/services/JSONStructuredOutput.java

- so our common settings get used
- required e.g. for datatypes like java8 dates

Use jackson mapper from sirius kernel at JSONStructuredOutput

---

src/main/resources/default/assets/tycho/lib.css.pasta
src/main/resources/default/assets/wondergem/wondergem.css.pasta

When attempting an upgrade to Bootstrap 5, the non-standard comment signs caused the first CSS rule of the included file not to load. Only `/* … */` is a valid CSS comment.

CSS Comments Fix

---

src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

It was noticeable with particularly high images with a narrow width.
Some of the images ran across several pages of the PDF.
Some images also overlapped areas of the PDF that should not be overlapped:
Before:
After:

Fixes the incorrect calculation of the dimensions

---

.drone.yml

Our sonar executions that run after a tag creation are broken for a while. Propably because this system property is missing.

Sets required system property for test on sonar execution

---

src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
src/test/kotlin/sirius/web/templates/pdf/handlers/PdfReplaceHandlerTest.kt

Depending on how the maximum permitted sizes for an image are specified, it may be that both the width and height are too small and therefore need to be scaled up. If we scale up the width first, it may well be that the height is too high for the specified maximum height.
Example:
Maximum width: 100px
Maximum height: 20px
Image:
50px wide and 15px high
After we have scaled up the width, the image would be :
100px wide and 30px high
The height of the image is now too high and we need to scale it down once.

Checks if we need to downscale the height after upscaling the width

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
src/main/java/sirius/web/templates/pdf/ResourceHandlingSemaphore.java
src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java

If many (more than 100) PDF pages with images are to be rendered, this takes a very long time (sometimes over 90 seconds). This should be improved by separating the resolving and scaling of the image into a separate thread.
Each image requests a slot on a free thread in a common thread pool.
Until the image has been loaded and scaled, it is merely a placeholder with the dimensions of the box in which it is to be placed later.
Fixes: SE-13398

Improves the performance of resolving the images

---

src/main/java/sirius/web/controller/Route.java

This can be useful for logging ClickHouse events or other things.
Fixes: [OX-10830](https://scireum.myjetbrains.com/youtrack/issue/OX-10830)

Allows to retrieve the specified URI pattern of a route

---

src/main/java/sirius/web/controller/ControllerDispatcher.java

The previously logged string representation of the route matching pattern is hard to read and also not as easy to aggregate. Now we actually log the route URI as it is defined in the Routed annotation of each route.
Its known and accepted that this means, that old and new events for the same route are not easily aggregatable together.
Fixes: [OX-10830](https://scireum.myjetbrains.com/youtrack/issue/OX-10830)

Logs aggregatable route in page impression events

---

src/main/resources/default/taglib/t/textarea.html.pasta

Bootstrap 5 requires disabled to have the gray background and readonly textarea should also be disabled like t:textfield and t:datefield.
- fixes: SIRI-936

also set t:textarea to disabled if readonly to have correct css

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
src/main/java/sirius/web/templates/pdf/SemaphoreContext.java

To ensure that users with smaller requests are not blocked by users with large requests, the system waits for a token from the semaphore before starting a new thread. 
This prevents countless threads from running and simply waiting.

Datasheet: Acquires a token before starting the thread

---

src/main/resources/assets/design-system/icons.scss
src/main/resources/assets/images/icons/availability/order-item.svg

Order items are items that a shop usually doesn't keep in stock, but still wants to sell. Rather than showing a red (unfriendly) icon, this commit allows the shop to show a more friendly blue icon.

Introduce an availability icon for order items

---

src/main/resources/default/taglib/t/datefield.html.pasta

In sirius.kernel.commons.AdvancedDateParser#ensureValidYear we only allow values between 1900 - 2100. So we also can do this in the Frontend via min and max values at the date input. Also the oninvalid event must reset the single-click.pending-js on the save button, because otherwise (after an invalid input) we can never press save-button again, The value now will nomore be parsed twice, so we have to fix a breaking change....
HINT: copy-pasting into a datefield is with the date-input no more available (in contrast to the before-bs5-version) and not easy to fix. Maybe a small hack like onpaste()-event could be a solution, but input-sanitizing would be the next problem then...
BREAKING: We have to use @toMachineString(dateFieldValue) for all values in t:datefields now.
- fixes: SIRI-938

Fix t:datefield for bootstrap-5 migration

---

src/main/resources/assets/design-system/form.scss

This is done to match the color scheme of Tycho after the Bootstrap 5 upgrade.
**Before:**
**After:**
Fixes: [OX-10841](https://scireum.myjetbrains.com/youtrack/issue/OX-10841)

Update disabled text input background color

---

src/main/java/sirius/web/mails/SendMailTask.java

We already provide the password via an authenticator implementation (sirius.web.mails.SendMailTask.MailAuthenticator). However SMTPTransport#sendMessage does evaluate the password set this way only after the initial connection.
The transport seems to then normally challenge the client for a password which is after the first round set correctly. However for some SMTP servers (e.g. SMTP relays with strict rules) which require early authentication, this is not enough.
Setting the password at the transport will in turn set the password on a URLName object which **IS** getting evaluated early.
Fixes: SE-13522

Fixes authentication errors against SMTP servers which require early passwords

---

src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java

The previous logic also optimized NLS get calls with multiple parameters (there is a variant with an int for singular/plural and one with a string for a forced language) to the NLS get call with the single string parameter for the key. This meant that the other two variants were not callable in Noodle scripts and Tagliatelle templates.
Fixes: [OX-10611](https://scireum.myjetbrains.com/youtrack/issue/OX-10611)

Noodle - Only detect intrinsic NLS get call for single parameter calls

---

src/main/resources/default/taglib/t/colorpicker.html.pasta

Before:
After:
Fixes: SIRI-940

Colorpicker: Stops displaying color code when no color is set

---

src/main/java/sirius/web/health/SystemController.java

This constant was defined but not used before. Seems to be a copy and paste mistake.

Bind system load route to correct permission

---

src/main/resources/default/taglib/t/helpbox.html.pasta

Before:
After:
Fixes: OX-10891

Changes helpbox to use min width and implements a check if there are any actions that should be rendered

---

src/main/java/sirius/web/http/WebContext.java

For some calls it may not be easy to determine if it contains a JSON body or we want to try to access it anyway. With this change the caller can decide whether to log the thrown exception or not.
Fixes: [OX-10862](https://scireum.myjetbrains.com/youtrack/issue/OX-10862)

Delays logging of error message when invalid JSON content is fetched

---

src/main/java/sirius/pasta/noodle/Environment.java
src/main/java/sirius/pasta/noodle/Invocation.java
src/main/java/sirius/pasta/noodle/LambdaHandler.java
src/main/java/sirius/pasta/noodle/compiler/Parser.java
src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
src/main/java/sirius/pasta/noodle/compiler/ir/LambdaNode.java
src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
src/test/kotlin/sirius/pasta/noodle/compiler/CompilerTest.kt
src/test/kotlin/sirius/web/http/CSRFTokenTest.kt

- We now support lambdas which call themselves recursively or which are invoked in parallel (by having distinct local environments)
- We added the Object protocol to all interfaces, so that methods like getClass() can be invoked on them
- We improved parameter type propagation for lambdas, e.g. for methods like `<E> void foo(Class<E> type, Consumer<E> consumer)` where the first parameter would determine the type for the second (the lambda parameter).

Improves scripting capabilities of Noodle

---

src/main/java/sirius/web/http/Response.java

A minor extension of fields that should be censored, means not written as plain text into log files.

Censures some more field use with oauth

---

src/main/java/sirius/web/http/WebContext.java

For some calls it may not be easy to determine if it contains a JSON body or we want to try to access it anyway. With this change the caller can decide whether to log the thrown exception or not.
The previous solution of commit 0d19e75c1a56a33a22584b05f0d169c11de10ce5 of PR https://github.com/scireum/sirius-web/pull/1395 was incomplete in this regard as Json#parseObject always logs an error message to the main logger.
Fixes: [OX-10940](https://scireum.myjetbrains.com/youtrack/issue/OX-10940)

Delay logging of error message when invalid JSON content is fetched

---

src/main/java/sirius/web/mails/SendMailTask.java
src/main/resources/scope-conf/mail.conf

- the password was introduced recently to fix a specific smtp server error
- it seems to make problems with other mail server implementations
Fixes: SE-13522

Makes mail authentication on transport configurable

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java

In some cases, the image we want to resolve is not yet available. It is therefore important to try again after a short waiting time.
This is the case, for example, when we request a variant of an image that has not yet been created.

Retries resolving image if any exception occurred

---

pom.xml

`flying-saucer-pdf-openpdf` is switched to `flying-saucer-pdf` as the main version of flying saucer switched from itext to openpdf and the old dependency was left to die

Update some dependencies to their latest versions

---

src/main/resources/default/taglib/t/iconInlineInfo.html.pasta

When using `<t:iconInlineInfo>` within `<t:datacard>`, users may want to know more about the information displayed, depending on how obvious the icon is. The new `title` property allows to set such information, which will be displayed as BS tooltip and rendered as ARIA label.
In order to make this work, the tooltip technically needs to become a link, thus overriding the card's own link. It is thus convenient to also pass the link property to allow seamless navigation.

Tooltips for `<t:iconInlineInfo>`

---

pom.xml

Switching from jakarta.mail (which does not have recent releases) to jaka.mail-api (which has recent releases) was done by accident, as the API does not provide any implementation that is required for actually sending mails.

Revert a failed dependency upgrade/switch

---

src/main/java/sirius/web/http/WebServerHandler.java
src/main/resources/component-065-web.conf

And also initially sets a more generous limit for the maximum number of form fields in a request. Netty default was 128, increased to 512. Netty tests internally with a limit of 1024.

Allow to overwrite the new Netty post request limits

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java

The newly implemented option of resolving images that is very efficiently does not work completely reliably in a few cases. For example, if we have URLs that are specified with http but automatically redirect to https. Although this happens very rarely, it should still work. The old, more expensive method via the UserAgentCallback handles this very well. As we only need this in a few exceptions, we only use the fallback if it has not worked twice with the new method.
- This PR fixes or works on following ticket(s): https://scireum.myjetbrains.com/youtrack/issue/SIRI-961/URI-Resolve-Fehler-bei-http-https
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1371

Resolving URLs that uses http but redirects to https

---

src/main/java/sirius/web/templates/pdf/SemaphoreContext.java

On a system with a single processor, 1 divided by 2 equals 0 for integer calculations. As no permits are added but only acquired and released, starting with 0 permits leads to endless waiting.
This resulted in PDFs with images not being created at all.
- This PR fixes or works on following ticket(s): [SIRI-962](https://scireum.myjetbrains.com/youtrack/issue/SIRI-962)
- This PR is related to PR: #1383

Fixes SemaphoreContext for Single Processor

---

src/main/java/sirius/web/http/QueryString.java
src/main/java/sirius/web/http/WebContext.java
src/test/kotlin/sirius/web/http/QueryStringTest.kt

The function `QueryString::get` now behaves the same as `WebContext::get` when requesting a parameter that has multiple values.
Before it always only returned the first value, now it returns all values.
And use it in the `WebContext` class to simplify/extract the logic.
- This PR fixes or works on following ticket(s): [SIRI-963](https://scireum.myjetbrains.com/youtrack/issue/SIRI-963)

Expand the functionality of the query string helper

---

src/main/resources/assets/design-system/text.scss

These are useful in combination with the `sci-text-smaller` and `sci-text-smallest` font sizes in tight spaces.
- This PR fixes or works on following ticket(s): [OX-11018](https://scireum.myjetbrains.com/youtrack/issue/OX-11018)

Add small CSS helpers for 100% and 110% line height

---

src/main/resources/default/assets/tycho/styles/forms.scss
src/main/resources/default/taglib/t/radio.html.pasta

input-required does not exist anymore in BS5, from-text should be form-text Many radio-buttons with a required-* are not useful. With this approach you can add a required-* to a div with a t:radio inside as well, but the * will only occur on the heading label, not at the selectable values.
- This PR fixes or works on following ticket(s): [SE-13684](https://scireum.myjetbrains.com/youtrack/issue/SE-13684)

fix t:radio - correct classes and according selector.

---

src/main/resources/default/taglib/t/singleSelect.html.pasta

This was previously broken as the suggestionsUriBuilder simply appended the query with a ? separator, which breaks when the uri already contains a ? for given parameters.
**Example use:**
```html
<t:singleSelect
name="actionfield-target"
labelKey="GalleryImage.hotspot.action.video"
suggestionUri="/actions/video/autocomplete?suggestCode=true"
optional="true"/>
```
- This PR fixes or works on following ticket(s): [OX-8268](https://scireum.myjetbrains.com/youtrack/issue/OX-8268)

Tycho - Support suggestion uris including predefined parameters

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java

- each virtual thread keeps a CallContext as ThreadLocal
- by adding the ScopeInfo to the UserContext, those objects are kept as references to that ThreadLocal, and so will not be garbage collected
- so we explicitly need to free those resources after the image was loaded
- This PR fixes or works on following ticket(s): [SIRI-974](https://scireum.myjetbrains.com/youtrack/issue/SIRI-974)

Fixes leaking memory on pdf item loading

---

src/main/resources/assets/design-system/display.scss

Adds:
- `sci-d-inline-flex`
- `sci-d-sm-inline-flex`
- `sci-d-md-inline-flex`
- `sci-d-lg-inline-flex`
- This PR fixes or works on following ticket(s): [SIRI-949](https://scireum.myjetbrains.com/youtrack/issue/SIRI-949)

Add CSS helpers for setting inline flex display property

---

src/main/resources/default/assets/common/scripts/dialog.js.pasta

This may be used by receivers of the event to determine whether the dialog was fully closed or just replaced by other content.
- This PR fixes or works on following ticket(s): [OX-11057](https://scireum.myjetbrains.com/youtrack/issue/OX-11057)

Dialog: Indicate whether dialog was replaced in custom event

---

src/main/resources/assets/design-system/form.scss

The token autocomplete CSS was changed when the optional clear button was introduced, requiring this change to fix the layout of our component.
**Before:**
**After:**
- This PR fixes or works on following ticket(s): [OX-11077](https://scireum.myjetbrains.com/youtrack/issue/OX-11077)

Adapt styling of sci-token-single-select component to changes in library

---

src/main/resources/default/assets/common/scripts/overlay.js.pasta

The previous behaviour is a result of this caveat of the click event:
If the button is pressed on one element and the pointer is moved outside the element before the button is released, the event is fired on the most specific ancestor element that contained both elements.
So if a click started within the overlay content and was dragged outside of it to the background (which can happen by accident when content with drag support is displayed inside the overlay) the overlay would suddenly close.
We now use the mousdown event so it only triggers when the click is started outside of the overlay content.
Tested on Desktop Chrome, Android Chrome & IE 11.
- This PR fixes or works on following ticket(s): [OX-11077](https://scireum.myjetbrains.com/youtrack/issue/OX-11077)

Overlay - Prevent closing when click is dragged from within overlay to background

---

src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/resources/component-065-web.conf
src/main/resources/scope-conf/mail.conf

- The default value was changed by angus implementation https://github.com/eclipse-ee4j/angus-mail/pull/14/files
- We keep the more secure default value, but make it configurable if less strict settings are required by mail server
- This PR fixes or works on following ticket(s): [SIRI-983](https://scireum.myjetbrains.com/youtrack/issue/SIRI-983)

Introduces a config option to control smtp server identity check

---

src/main/resources/default/taglib/t/multiSelect.html.pasta
src/main/resources/default/taglib/t/singleSelect.html.pasta

Allows to override the label. Will be used in OX to show the real parameter name along the label:
- This PR fixes or works on following ticket(s): [OX-11038](https://scireum.myjetbrains.com/youtrack/issue/OX-11038)

Adds block based logic to override the labels for single and multiSelect

---

src/main/resources/default/assets/common/scripts/continuity.js.pasta

Shortens encoded deeplink URL parameter value

---

src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java

In the surrounding container, the values text-align and vertical-align can now be used to align the image.
We can now use the CSS properties text-align and vertical-align to align images in a PDF. To do this, we need the image in a container. This can then receive the corresponding CSS rules.
Previously, horizontal and vertical centering was the default. This is still the case now, so nothing should change unless the CSS properties text-align or vertical-align already exist. These properties would now take effect. It is therefore necessary to check whether an alignment is already specified in the CSS.
```
<div class="container">
</div>
```
```
<style>
.container {
vertical-align: bottom;
text-align: center;
}
.container .img {
width: 4cm;
height: 8cm;
}
</style>
```
- This PR fixes or …

Positioning: Images in PDF

---

src/main/resources/assets/design-system/misc.scss

Uses the contents of Bootstraps' stretched-link class
- This PR fixes or works on following ticket(s): [OX-11030](https://scireum.myjetbrains.com/youtrack/issue/OX-11030)

Implements new CSS class for links to be stretched over an element

---

src/main/java/sirius/pasta/tagliatelle/tags/IncludeTag.java
src/main/java/sirius/pasta/tagliatelle/tags/SassTag.java
src/main/java/sirius/pasta/tagliatelle/tags/TagHandler.java
src/main/java/sirius/web/sass/Generator.java
src/main/java/sirius/web/sass/Parser.java
src/main/java/sirius/web/sass/ast/Attribute.java
src/main/java/sirius/web/sass/ast/MediaFilter.java
src/main/java/sirius/web/sass/ast/NamedParameter.java
src/main/java/sirius/web/sass/ast/Number.java
src/main/java/sirius/web/sass/ast/Operation.java
src/main/java/sirius/web/sass/ast/Section.java
src/main/java/sirius/web/sass/ast/Stylesheet.java
src/main/java/sirius/web/sass/ast/Value.java
src/main/java/sirius/web/sass/ast/ValueList.java
src/main/java/sirius/web/sass/ast/VariableReference.java

Provides `<i:sass>` for compiling a SASS file and including the resulting CSS directly into a template. Also includes some code maintenance.
```html
<head>
<style>
<i:sass source="/assets/pdf/datasheet.scss"/>
</style>
</head>
```
- This PR fixes or works on following ticket(s): [OX-10782](https://scireum.myjetbrains.com/youtrack/issue/OX-10782)

`<i:sass>`

---

src/main/resources/default/assets/common/core.js.pasta

Netty seems to replace some characters like commas, colons, semicolons, ... with spaces when reading the multipart form data in `HttpPostMultipartRequestDecoder::getContentDispositionAttribute`. This may be problematic when trying to match the parameter names to data.
To circumvent this in a non breaking fashion we add a new optional parameter that converts the FormData into an URLSearchParams object. This way data is sent with content type `application/x-www-form-urlencoded` instead of `multipart/form-data`.
see:
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java#L875
https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder. …

Core JS - Allow to send POST data as urlencoded instead of multipart form data

---

src/main/resources/default/taglib/t/dateTimeField.html.pasta

Small fix for datetime field
- This PR fixes or works on following ticket(s): [SIRI-1013](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1013)

Fixes min and max default values

---

src/main/java/sirius/web/security/oauth/ReceivedTokens.java

Returns the oauth access token "expires at" date in case the server did return it. 
Providing this information e.g. gives the API caller the possibility to refresh the token if required. The usage is optional, if not set, the implemention in sirius will trigger a refresh if the provided access token could not be used to authenticate at server. 
Technically this is breaking. But it should have no impact on API users as only the framework should use the constructor with the changed parameters.
- This PR fixes or works on following ticket(s): [SE-13502](https://scireum.myjetbrains.com/youtrack/issue/SE-13502)

Returns the oauth access token "expires at" date

---

pom.xml
src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java

The _Flying Saucer_ PDF renderer requires XHTML as input, and we rely on the invoker to provide valid content. However, luckily, the world has moved on from XHTML. In order to relax the requirements and facilitate reuse of HTML templates, this PR introduces an additional processing step that removes problematic elements and ensures XHTML automatically.
Marked as **breaking** as PDF rendering should be checked after upgrading.
- This PR fixes or works on following ticket(s): [OX-10783](https://scireum.myjetbrains.com/youtrack/issue/OX-10783)

HTML Input for PDF Generation

---

src/main/resources/assets/design-system/design-system.scss
src/main/resources/assets/design-system/display.scss

CSS rules of the same specificity (most of our helpers only use a single class, so have the specificity 0,1,0) are applied in the order they are loaded/defined. This means that we should place more specific helpers below more board components to increase the flexibility. Doing so reduces the need for !important markings on rules, which can get quite out of hand.
**Examples of what the proposed changes allow to do:**
1) `sci-button-primary sci-p-1` - allows to reduce the default padding of our button class
2) `sci-d-flex sci-d-none` - Allows to hide an element and show it as soon as the `sci-d-none` is removed (the JS code does not need to know what proper display class has to be added)
**Concrete example:**
- Toggle only shows when `sci-d-none` is removed
- Toggle buttons have reduced …

CSS Design System - Reorder design system rules to enable more flexible overwriting

---

src/main/java/sirius/web/sass/Generator.java
src/main/java/sirius/web/sass/Parser.java
src/main/java/sirius/web/sass/ast/Color.java
src/main/java/sirius/web/sass/ast/Expression.java
src/main/java/sirius/web/sass/ast/FunctionCall.java
src/main/java/sirius/web/sass/ast/MediaFilter.java
src/main/java/sirius/web/sass/ast/Mixin.java
src/main/java/sirius/web/sass/ast/MixinReference.java
src/main/java/sirius/web/sass/ast/NamedParameter.java
src/main/java/sirius/web/sass/ast/Number.java
src/main/java/sirius/web/sass/ast/Operation.java
src/main/java/sirius/web/sass/ast/Section.java
src/main/java/sirius/web/sass/ast/Stylesheet.java
src/main/java/sirius/web/sass/ast/Value.java
src/main/java/sirius/web/sass/ast/ValueList.java
src/main/java/sirius/web/sass/ast/VariableReference.java
src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java

Primarily fixes the way the SASS parser handles the import of other stylesheets. This is now done via a Sirius helper class, `Resources`, in order to also cover files in the `/default/` directory. Along with that, the code of the SASS implementation is generally revised.
- This PR fixes or works on following ticket(s): [OX-10783](https://scireum.myjetbrains.com/youtrack/issue/OX-10783)

SASS Fixes

---

src/main/resources/assets/design-system/misc.scss

Took the most common cursors from [this list](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#keyword) and added them as helper classes next to the already defined `sci-cursor-pointer`.
- This PR fixes or works on following ticket(s): [OX-11120](https://scireum.myjetbrains.com/youtrack/issue/OX-11120)

Add some CSS helper class for common cursor variants

---

src/main/java/sirius/pasta/tagliatelle/macros/IfNotDefinedMacro.java
src/main/java/sirius/pasta/tagliatelle/rendering/GlobalRenderContext.java
src/main/resources/default/taglib/t/ifNotDefined.html.pasta

* Similar to C/C++ `#ifndef`
* Can be used to make sure that certain imports/code is only performed once per template.
- This PR fixes or works on following ticket(s): [SIRI-1019](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1019)

Adds a new Macro which checks whether the given guard string is defined or not

---

src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java

Keeps the `<bookmarks>` element in `<head>` during cleanup. Jsoup moves it to `<body>` during parsing as it is a non-standard header tag required by _flying saucer_ to generate PDF bookmarks (i.e. a PDF table of contents).
- This PR fixes or works on following ticket(s): [OX-10783](https://scireum.myjetbrains.com/youtrack/issue/OX-10783)

PDF Bookmark Support

---

src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
src/main/java/sirius/pasta/tagliatelle/tags/ArgTag.java
src/main/java/sirius/pasta/tagliatelle/tags/BlockTag.java
src/main/java/sirius/pasta/tagliatelle/tags/DefineTag.java
src/main/java/sirius/pasta/tagliatelle/tags/DynamicInvokeTag.java
src/main/java/sirius/pasta/tagliatelle/tags/ExtensionsTag.java
src/main/java/sirius/pasta/tagliatelle/tags/ExtraBlockTag.java
src/main/java/sirius/pasta/tagliatelle/tags/ForTag.java
src/main/java/sirius/pasta/tagliatelle/tags/IfTag.java
src/main/java/sirius/pasta/tagliatelle/tags/IncludeTag.java
src/main/java/sirius/pasta/tagliatelle/tags/InvokeTag.java
src/main/java/sirius/pasta/tagliatelle/tags/LocalTag.java
src/main/java/sirius/pasta/tagliatelle/tags/PragmaTag.java
src/main/java/sirius/pasta/tagliatelle/tags/RenderTag.java
src/main/java/sirius/pasta/tagliatelle/tags/SassTag.java
src/main/java/sirius/pasta/tagliatelle/tags/SwitchTag.java
src/main/java/sirius/pasta/tagliatelle/tags/TagHandler.java
src/main/java/sirius/pasta/tagliatelle/tags/TaglibTagHandler.java

The TemplateCompiler currently ignores if there are missing attributes that are required because of a missing default value. This circumstance ist only detected during the rendering of the page.
The changes to the TemplateCompiler is now checking for these missing attributes as an early warning to the programmer. Especialy if the templates are overwritten by an artefact.
- This PR fixes or works on following ticket(s): [SE-13618](https://scireum.myjetbrains.com/youtrack/issue/SE-13618)

SE-13618: Extend the checks of the TemplateCompiler to include missing required attributes

---

src/main/java/sirius/web/mails/SendMailTask.java

Note that if you're using the "smtps" protocol to access SMTP over SSL, all the properties would be named "mail.smtps.*".
- This PR fixes or works on following ticket(s): [SIRI-1023](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1023)

Fixes config keys for smtps protocol

---

src/main/resources/default/assets/common/core.js.pasta

Sometimes the DOMContentLoaded event is fired after document.readyState already changed to 'interactive'. In this case, the callback is actually called twice with our approach.
This commit ensures that the callback is only called once.
See https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState for possible values
See https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event (actually gives the same code as an example)
- This PR fixes or works on following ticket(s): [SE-14083](https://scireum.myjetbrains.com/youtrack/issue/SE-14083)
- This PR is related to PR: scireum/sellsite/pull/12139

Never fire the callback in sirius.ready twice

---

src/main/java/sirius/web/security/HelperFactory.java

This is useful for Feature-flagged helpers in customizations which are scoped and not enabled in all scopes Without autoRegister the framework warns on the following code: 
```
@Register
public static class SubHelperFactory extends SuperHelperFactory {
@Nonnull
@Override
public SuperHelper make(@Nonnull ScopeInfo scopeInfo) {
if (!UserContext.getCurrentUser().hasPermission("feature-sub")) {
return new SubHelper(scopeInfo);
}
return super.make(scopeInfo);
}
}
```
- This PR fixes or works on following ticket(s): [SE-14106](https://scireum.myjetbrains.com/youtrack/issue/SE-14106)

autoregister helperFactory

---

src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta

FireFox decides to keep the former state of the checkboxes. Sadly without triggering a change event. Therefore, we manually have to clear the checkboxes on sirius.ready. This is fine since this behavior was "extra" all along as any other browser is not keeping the state of input fields...
- This PR fixes or works on following ticket(s): [OX-11093](https://scireum.myjetbrains.com/youtrack/issue/OX-11093)

SelectableTable - Fixes an issue with checkboxes still being checked after refresh in FireFox

---

src/main/resources/assets/design-system/design-system.scss
src/main/resources/assets/design-system/margin-padding.scss
src/main/resources/assets/design-system/misc.scss
src/main/resources/assets/design-system/text.scss

The shape was actually correct as browsers cap the applied border radius to half the height, but this should ensure proper behaviour when overriding font size or base unit.
- This PR fixes or works on following ticket(s): [OX-11040](https://scireum.myjetbrains.com/youtrack/issue/OX-11040)

CSS Design System - Improve calculation of pill border radius

---

src/main/resources/default/taglib/t/dateTimeField.html.pasta

By default the step setting of datetime-local inputs is 60 (seconds), which means seconds are hidden by default and can't be altered. This may be (and is) required in some cases.
- This PR fixes or works on following ticket(s): [OX-11656](https://scireum.myjetbrains.com/youtrack/issue/OX-11656)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/11715

Tycho - Allow to control precision of date time field

---

pom.xml
src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
src/main/java/sirius/web/templates/pdf/InlinedSvgElement.java

Extends the HTML-to-PDF-pipeline to support inline SVGs.
- This PR fixes or works on following ticket(s): [OX-9272](https://scireum.myjetbrains.com/youtrack/issue/OX-9272)

Inline SVGs for PDFs (OX-9272)

---

src/main/resources/default/taglib/t/searchHeader.html.pasta

with md it does not work on small screeens and also moves the search-line some ugly pixels down over content (see screenshot)
- This PR fixes or works on following ticket(s): [SE-14153](https://scireum.myjetbrains.com/youtrack/issue/SE-14153)
- This PR is related to PR: #1473

fix css for sticky t:searchHeader on small screens

---

src/main/resources/assets/design-system/icons.scss

- This PR fixes or works on following ticket(s): [OX-11593](https://scireum.myjetbrains.com/youtrack/issue/OX-11593)
- This PR is related to PR: https://github.com/scireum/oxomi/pull/11727

Implements icons for the new watchlist feature in OX

---

src/main/resources/default/assets/common/core.js.pasta
src/main/resources/default/assets/common/ie-polyfill.js.pasta

This allows the use of `URLSearchParams` and `String` as the 'params' parameter in `sirius.postJson`, which sometimes are easier to build than an object.
The second commit allows `URLSearchParams` in the `fetch` polyfill.
- This PR fixes or works on following ticket(s): [SE-14122](https://scireum.myjetbrains.com/youtrack/issue/SE-14122)

Support the use of URLSearchParams and String in sirius.postJson

---

src/main/resources/default/taglib/t/searchHeader.html.pasta

- Changed the default behavior of the searchHeader as it is now sticky
- This PR fixes or works on following ticket(s): [SIRI-1034](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1034)

Makes the searchHeader sticky by default

---

src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta

- This PR fixes or works on following ticket(s): [SIRI-11094](https://scireum.myjetbrains.com/youtrack/issue/SIRI-11094)

Prevents the row from being selected when clicked on an i-tag

---

.drone.yml
pom.xml
src/main/java/sirius/web/data/ExcelExport.java
src/main/java/sirius/web/templates/pdf/InlinedSvgElement.java
src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
src/main/java/sirius/web/templates/pdf/handlers/QrCodePdfReplaceHandler.java
src/test/kotlin/sirius/web/templates/pdf/handlers/PdfReplaceHandlerTest.kt

Fixes: SIRI-1036
Wait for https://github.com/scireum/sirius-parent/pull/45 and https://github.com/scireum/sirius-kernel/pull/542
**BREAKING CHANGES:**
- org.xhtmlrenderer.extend.FSImage#scale now operates immutable. Means you need to use the returned value. 
- This PR fixes or works on following ticket(s): [SIRI-1036](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1036)

Upgrade library versions

---

src/main/java/sirius/web/http/Response.java

When creating a response marked as not cached (cacheSeconds = 0), no cache headers were added to the response.
With this change, `cache-control: no-cache, max-age=0` will be added to the response headers.
Of course this header is suppressed when no caching time is present.
- This PR fixes or works on following ticket(s): [OX-11230](https://scireum.myjetbrains.com/youtrack/issue/OX-11230)

Sets cache headers for non cached redirect URLs

---

src/main/resources/assets/design-system/misc.scss

A sightly smaller version of the preloader which can be used in tighter spaces
- This PR fixes or works on following ticket(s): [OX-11681](https://scireum.myjetbrains.com/youtrack/issue/OX-11681)

Adds sci-preloader-small

---

src/main/java/sirius/pasta/noodle/macros/XmlProcessingMacro.java
src/main/java/sirius/web/security/SAMLHelper.java
src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java

Fix a potential XXE vulnerability via setting Feature Secure Processing
https://docs.oracle.com/javase/8/docs/technotes/guides/security/jaxp/jaxp.html#feature-for-secure-processing
Nicer and more current documentation:
https://docs.oracle.com/en/java/javase/23/security/java-api-xml-processing-jaxp-security-guide.html
In a nutshell, this prevents access to external entities and set limit while processing xml. As this feature is rarely required and the limits are reasonable high, we expect no problems. But testing the xml processing in products is recommended, after this change got included. 
- This PR fixes or works on following ticket(s): [SIRI-1037](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1037)
- This PR is related to PR:  https://github.com/scireum/sirius-kernel/pull/543

Fix a potential XXE Vulnerability

---

src/main/resources/assets/design-system/button.scss
src/main/resources/assets/design-system/card.scss
src/main/resources/assets/design-system/display.scss
src/main/resources/assets/design-system/flex.scss
src/main/resources/assets/design-system/form.scss
src/main/resources/assets/design-system/margin-padding.scss
src/main/resources/assets/design-system/message.scss
src/main/resources/assets/design-system/misc.scss
src/main/resources/assets/design-system/table.scss
src/main/resources/assets/design-system/text.scss
src/main/resources/default/assets/common/templates/sidebar-overlay.html.mustache

This adds additional classes to the scireum Design System.
Uses of `--sci-margin-05` need to be replaced with `--sci-margin-0_5`.
- This PR fixes or works on following ticket(s): [SE-13735](https://scireum.myjetbrains.com/youtrack/issue/SE-13735)

Design System additions

---

src/main/java/sirius/web/sass/Parser.java
src/main/resources/assets/design-system/grid.scss
src/main/resources/assets/design-system/margin-padding.scss
src/main/resources/assets/design-system/misc.scss

In class names like `sci-m-0.5` the period needs to be escaped, this adds support to the SASS parser and fixes all class names.
- This PR fixes or works on following ticket(s): [SE-13735](https://scireum.myjetbrains.com/youtrack/issue/SE-13735)

Design System: Fix the class names with decimal point

---

src/main/java/sirius/web/controller/MessageLevel.java
src/main/resources/assets/design-system/button.scss
src/main/resources/assets/design-system/form.scss
src/main/resources/assets/design-system/message.scss
src/main/resources/assets/design-system/misc.scss
src/main/resources/assets/design-system/table.scss

Before:
After:
Not Disabled:
Overview:
- This PR fixes or works on following ticket(s): [SE-13735](https://scireum.myjetbrains.com/youtrack/issue/SE-13735)

More design system enhancements

---

src/main/java/sirius/web/http/WebContext.java
src/main/resources/component-065-web.conf

A customer requires `SameSite=None`, which modern browsers no longer support without also setting `Secure`. Unfortunately, this customer still uses http without SSL for some internal services, which forbids the `Secure` attribute.
This introduces a separate setting for configuring the `SameSite` attribute for unsecure connections.
- This PR fixes or works on following ticket(s): [SIRI-1044](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1044)

SIRI-1044 Introduce a setting for SameSite on unsecure http

---

src/main/resources/default/assets/common/core.js.pasta

The logic for copying values via copy-button is quiet weird, but "the-way-to-go" for all browsers and all cases (http, https).
in some rare cases (where scrollPaddingTop is set) the top-scroll value does not fit to the real scroll-position. So vie preventScroll we ask the browser to not scroll on focus. Is also not supported by all browsers, but does not break the functionality

prevent scrolling to the fake-element inserted for copy-buttons

---

src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [OX-11700](https://scireum.myjetbrains.com/youtrack/issue/OX-11700)
- This PR is related to PR: https://github.com/scireum/sirius-biz/pull/2094

File Explorer - Fixes checkbox behaviour when using the back function of the browser

---

src/main/java/sirius/web/http/Response.java

There is no guarantee that search engines respect that, but big players like Google, Bing etc. do.
- This PR fixes or works on following ticket(s): [SIRI-1049](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1049)

Permits to prevent responses from being crawled by search engines

---

src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
src/main/resources/default/taglib/t/additionalActions.html.pasta

Before:
After:
- This PR fixes or works on following ticket(s): [OX-11700](https://scireum.myjetbrains.com/youtrack/issue/OX-11700)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1503

File Explorer - Changes the back function to clear the checkboxes of 'bg-sirius-blue-faint' and fixes behaviour of "more action"-button

---

src/main/resources/default/assets/tycho/styles/page.scss
src/main/resources/default/taglib/t/pageHeader.html.pasta

Restricts page title to two lines. The previous CSS already tried to apply an ellipsis but did not work.
Ellipsis on a single line is a little restrictive on mobile devices, so we utilize webkit box with line clamping. Seems to be supported by all modern browsers.
**Before:**
**After:**
- This PR fixes or works on following ticket(s): [SIRI-1091](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1091)

Tycho - Prevent extremely long title from breaking the layout

---

src/main/resources/default/assets/tycho/scripts/form.js.pasta

- This PR fixes or works on following ticket(s): [OX-11940](https://scireum.myjetbrains.com/youtrack/issue/OX-11940)

Forms - Adapts `confirm-link-js`-EventListener to be able to use inputs from external forms via form id to be passed via webContext

---

src/main/resources/default/templates/system/api.html.pasta

This way a JSON-schema or XSD can be provided to further document an API response.
We use the `@Schema` sub annotation of the swagger `@ApiResponse` annotation for this. A `ref` has to be filled with the downloadable asset URI of the schema. The `name` field can be used to provide an optimized download name for the schema file.
**Example:**
- This PR fixes or works on following ticket(s): [OX-11872](https://scireum.myjetbrains.com/youtrack/issue/OX-11872)

Allow to provide a schema download next to the sample response of an API

---

pom.xml
src/main/java/sirius/pasta/noodle/SiriusClassAliasProvider.java
src/main/java/sirius/pasta/noodle/macros/UrlEncodeMacro.java
src/main/java/sirius/web/http/Response.java
src/main/java/sirius/web/security/OTPVerifier.java
src/main/java/sirius/web/util/LinkBuilder.java
src/main/resources/component-065-web.conf
src/test/java/sirius/web/http/TestRequest.java

- update sirius-kernel
- allow Urls-methods in NoodleSandbox
- add shortHand
- use new methods to fix breaking deprecations
full changelog of kernel: https://github.com/scireum/sirius-kernel/compare/dev-45.1.3...dev-46.3.0
- This PR fixes or works on following ticket(s): [SE-14614](https://scireum.myjetbrains.com/youtrack/issue/SE-14614)

update sirius-kernel, use new common.Urls-methods, allow them

---

src/main/java/sirius/web/services/JSONCall.java

There are known APIs that return a JSON array instead of an Object.
- This PR fixes or works on following ticket(s): [SE-14587](https://scireum.myjetbrains.com/youtrack/issue/SE-14587)

Support JSON Calls that return an Array

---

src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
src/main/resources/default/taglib/t/additionalActions.html.pasta

The previous solution of preventing the click propagation of the additional actions toggle caused its dropdown not closing properly when clicking on a similar toggle in another table row.
**Before/Problem:**
- This PR fixes or works on following ticket(s): [SIRI-1114](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1114)

Tycho - Ensure only relevant clicks toggle the checkbox more safely

---

src/main/java/sirius/web/security/SAMLHelper.java

Previously, we expected the X509Certificate to be the first child of the X509Data structure. For Google SAML, this assumption is wrong as the X509Certificate is the second entry only, leading to an illegal cast. Therefore, we now inspect all children and process the first X509Certificate child.
- This PR fixes or works on following ticket(s): [OX-12034](https://scireum.myjetbrains.com/youtrack/issue/OX-12034)

SAML: Parsing of X509Certificate (OX-12034)

---

src/main/java/sirius/web/controller/BasicController.java
src/main/java/sirius/web/controller/Controller.java
src/main/java/sirius/web/controller/ControllerDispatcher.java

Some controllers (e.g. frontend controllers) may not want to log exceptions to the system log or they want to enrich the exception before logging it, e.g. adding a generic error code so that later on, a more generic error message can be displayed to the user with the error code instead of showing the actual internal error message while still allowing connecting the show error to the internal error via the code (if provided by the user).
By default, the exception is simply handled via the common logic as was the case already. Because handled exceptions are ignored and returned as is when calling Exceptions#handle, we don't have to differentiate between those and unhandled exceptions in the BasicController.
- This PR fixes or works on following ticket(s): …

Allow Controller to Handle Exceptions custom

---

src/main/resources/assets/design-system/misc.scss
src/main/resources/default/assets/common/components.js.pasta
src/main/resources/default/assets/common/components.scss
src/main/resources/default/assets/common/scripts/toast.js
src/main/resources/default/assets/common/styles/toast.scss

This new sirius JS component manages temporary "toast" messages shown to users.
With the following global configuration options:
- position
And the following individual toast configuration options:
- message text
- type (controls color)
- duration of auto removal
- closable by user
- animated show/hide
- This PR fixes or works on following ticket(s): [SIRI-1106](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1106)

JS Toast Component

---

src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/java/sirius/web/security/oauth/OAuthTokenProvider.java
src/main/java/sirius/web/security/oauth/OAuthTokenProviderUtils.java
src/main/resources/component-065-web.conf
src/main/resources/scope-conf/mail.conf

Provides a mechanism to declare an OAuth token by referencing it via a "name" when sending mails.
The tokens themselves must be provided via a custom implementation of `OAuthTokenProvider`.
- This PR fixes or works on following ticket(s): [SIRI-1060](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1060)
- This PR is related to PR: #1546

SIRI-1060:  Mail OAuth

---

src/main/java/sirius/web/security/oauth/OAuth.java
src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
src/main/resources/web_de.properties

Otherwise, error would be ignored and requiring a JSON or web-context parameter would fail later on would throw an exception that is rather useless besides indicating that something went wrong.
- This PR fixes or works on following ticket(s): [SIRI-1060](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1060)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1549

SIRI-1060: OAuth Error Handling

---

src/main/java/sirius/web/mails/MailSender.java
src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/java/sirius/web/services/JSONCall.java
src/main/resources/component-065-web.conf
src/main/resources/scope-conf/mail.conf
src/test/java/sirius/web/mails/MailsMock.java

Microsoft unterstützt OAuth in SMTP nur für bestimmte Legacy Systeme. Stattdessen soll die proprietäre Microsoft Graph API verwendet werden, die Mails per HTTP weiterleitet.
Caveat:
Viele Einstellungen in den Mail Settings sind bei Nutzung der API eigentlich nicht mehr nötig, wir prüfen aber auf deren Existenz (teilweise in den Produkten selbst hinsichtlich ob die Konfig aus den UserSettings oder System Settings genutzt werden soll). Das sollte sinnvoll aufgedröselt werden, ist aber gar nicht so trivial. Hier gibt es auch Sonderfälle wie in `sirius.web.mails.SendMailTask#setupSender`, wo die in dem MailSender hinterlegte `senderEmail` ignoriert wird und nur die Einstellung aus der Config oder aus den System Settings zieht, was eher wie ein Bug statt Feature aussieht.
Eine sinnvollere …

Mail OAuth2: Support Microsoft Graph API

---

src/main/java/sirius/web/mails/SendMailTask.java

…to also set it for mails sent via Microsoft Graph API.
- This PR fixes or works on following ticket(s): [SIRI-1060](https://scireum.myjetbrains.com/youtrack/issue/SIRI-1060)

Sets the success flag outside the SMTP logic 

---

src/main/java/sirius/web/mails/MicrosoftGraphApiConfiguration.java
src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java
src/main/java/sirius/web/mails/SMTPConfiguration.java
src/main/java/sirius/web/mails/SendMailTask.java
src/main/resources/component-065-web.conf
src/main/resources/scope-conf/mail.conf

We must set the Microsoft Graph API settings as part of the SMTPConfiguration (altough that name doesn't match) to have a single point of truth: Do we use the system settings or the scope settings?
Also, the mail sender address has no single point of truth, its either in the MailSender object, the SMTPConfiguration, or in the default system settings...
- This PR fixes or works on following ticket(s): [SE-14716](https://scireum.myjetbrains.com/youtrack/issue/SE-14716)
- This PR is related to PR: https://github.com/scireum/sirius-web/pull/1557

OAuth Mail Config Fixes

---

src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java

This didn't emerge during development because when no name is set, the mail address is also the name :/
- This PR fixes or works on following ticket(s): [SE-14716](https://scireum.myjetbrains.com/youtrack/issue/SE-14716)

Fixes setting wrong receiver mail address.
